
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Nov 18 2025 12:22:11 IST (Nov 18 2025 06:52:11 UTC)

// Verification Directory fv/HA 

module appliances_controller(clk, rst_n, ac_cmd, fan_cmd, light_cmd,
     ac_on, fan_on, lights_on);
  input clk, rst_n, ac_cmd, fan_cmd, light_cmd;
  output ac_on, fan_on, lights_on;
  wire clk, rst_n, ac_cmd, fan_cmd, light_cmd;
  wire ac_on, fan_on, lights_on;
  DFFRHQX1 ac_on_reg(.RN (rst_n), .CK (clk), .D (ac_cmd), .Q (ac_on));
  DFFRHQX1 fan_on_reg(.RN (rst_n), .CK (clk), .D (fan_cmd), .Q
       (fan_on));
  DFFRHQX1 lights_on_reg(.RN (rst_n), .CK (clk), .D (light_cmd), .Q
       (lights_on));
endmodule

module burglar_alarm(clk, rst_n, motion_sensor, door_sensor,
     window_sensor, alarm_arm, alarm_out);
  input clk, rst_n, motion_sensor, door_sensor, window_sensor,
       alarm_arm;
  output alarm_out;
  wire clk, rst_n, motion_sensor, door_sensor, window_sensor, alarm_arm;
  wire alarm_out;
  wire [8:0] delay_counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37;
  DFFRHQX1 \delay_counter_reg[5] (.RN (rst_n), .CK (clk), .D (n_36), .Q
       (delay_counter[5]));
  DFFRHQX1 \delay_counter_reg[8] (.RN (rst_n), .CK (clk), .D (n_34), .Q
       (delay_counter[8]));
  OAI31XL g634(.A0 (n_11), .A1 (delay_counter[6]), .A2 (n_23), .B0
       (n_33), .Y (n_37));
  SDFFRHQX1 \delay_counter_reg[4] (.RN (rst_n), .CK (clk), .D (n_21),
       .SI (n_26), .SE (delay_counter[4]), .Q (delay_counter[4]));
  OAI2BB1X1 g636(.A0N (delay_counter[5]), .A1N (n_29), .B0 (n_25), .Y
       (n_36));
  OAI21X1 g637(.A0 (n_11), .A1 (n_28), .B0 (n_32), .Y (n_35));
  AO22XL g638(.A0 (delay_counter[8]), .A1 (n_31), .B0 (n_7), .B1
       (n_21), .Y (n_34));
  NAND2XL g639(.A (delay_counter[6]), .B (n_30), .Y (n_33));
  NAND2XL g640(.A (delay_counter[7]), .B (n_30), .Y (n_32));
  NAND2XL g641(.A (n_11), .B (n_27), .Y (n_31));
  OAI21XL g643(.A0 (n_11), .A1 (delay_counter[4]), .B0 (n_27), .Y
       (n_29));
  AOI32X1 g644(.A0 (delay_counter[6]), .A1 (n_1), .A2 (n_22), .B0
       (delay_counter[7]), .B1 (n_0), .Y (n_28));
  OAI21X1 g645(.A0 (n_11), .A1 (n_22), .B0 (n_14), .Y (n_30));
  CLKINVX1 g646(.A (n_26), .Y (n_27));
  OAI21X1 g647(.A0 (n_18), .A1 (n_11), .B0 (n_14), .Y (n_26));
  NAND3BX1 g648(.AN (delay_counter[5]), .B (delay_counter[4]), .C
       (n_21), .Y (n_25));
  OAI22XL g649(.A0 (n_11), .A1 (n_20), .B0 (n_14), .B1 (n_2), .Y
       (n_24));
  INVXL g650(.A (n_22), .Y (n_23));
  NOR2BX1 g651(.AN (n_18), .B (n_5), .Y (n_22));
  NOR2BX1 g652(.AN (n_18), .B (n_11), .Y (n_21));
  MXI2XL g654(.A (n_2), .B (delay_counter[3]), .S0 (n_12), .Y (n_20));
  OAI22XL g655(.A0 (n_11), .A1 (n_15), .B0 (n_14), .B1 (n_3), .Y
       (n_19));
  DFFRHQX1 alarm_out_reg(.RN (rst_n), .CK (clk), .D (n_17), .Q
       (alarm_out));
  DFFRHQX1 \delay_counter_reg[1] (.RN (rst_n), .CK (clk), .D (n_16), .Q
       (delay_counter[1]));
  NOR2XL g658(.A (n_2), .B (n_12), .Y (n_18));
  SDFFRHQX1 \delay_counter_reg[0] (.RN (rst_n), .CK (clk), .D (n_10),
       .SI (n_13), .SE (delay_counter[0]), .Q (delay_counter[0]));
  OAI2BB1XL g660(.A0N (alarm_out), .A1N (n_10), .B0 (n_14), .Y (n_17));
  AO22XL g661(.A0 (n_6), .A1 (n_10), .B0 (delay_counter[1]), .B1
       (n_13), .Y (n_16));
  MXI2XL g662(.A (n_3), .B (delay_counter[2]), .S0 (n_4), .Y (n_15));
  INVX1 g663(.A (n_14), .Y (n_13));
  OR2X1 g664(.A (n_9), .B (n_8), .Y (n_14));
  INVX1 g665(.A (n_11), .Y (n_10));
  OR2X1 g666(.A (n_3), .B (n_4), .Y (n_12));
  NAND2BX1 g667(.AN (n_9), .B (n_8), .Y (n_11));
  OAI31X1 g668(.A0 (window_sensor), .A1 (motion_sensor), .A2
       (door_sensor), .B0 (alarm_arm), .Y (n_9));
  OAI211X1 g669(.A0 (delay_counter[2]), .A1 (delay_counter[3]), .B0
       (delay_counter[8]), .C0 (n_7), .Y (n_8));
  NOR3X1 g670(.A (n_0), .B (n_1), .C (n_5), .Y (n_7));
  XOR2XL g671(.A (delay_counter[0]), .B (delay_counter[1]), .Y (n_6));
  NAND2XL g672(.A (delay_counter[4]), .B (delay_counter[5]), .Y (n_5));
  NAND2XL g673(.A (delay_counter[0]), .B (delay_counter[1]), .Y (n_4));
  DFFRX1 \delay_counter_reg[2] (.RN (rst_n), .CK (clk), .D (n_19), .Q
       (delay_counter[2]), .QN (n_3));
  DFFRX1 \delay_counter_reg[3] (.RN (rst_n), .CK (clk), .D (n_24), .Q
       (delay_counter[3]), .QN (n_2));
  DFFRX1 \delay_counter_reg[7] (.RN (rst_n), .CK (clk), .D (n_35), .Q
       (delay_counter[7]), .QN (n_1));
  DFFRX1 \delay_counter_reg[6] (.RN (rst_n), .CK (clk), .D (n_37), .Q
       (delay_counter[6]), .QN (n_0));
endmodule

module door_lock_controller(clk, rst_n, lock_cmd, unlock_cmd,
     pin_input, door_locked, lock_status);
  input clk, rst_n, lock_cmd, unlock_cmd;
  input [3:0] pin_input;
  output door_locked;
  output [1:0] lock_status;
  wire clk, rst_n, lock_cmd, unlock_cmd;
  wire [3:0] pin_input;
  wire door_locked;
  wire [1:0] lock_status;
  wire [1:0] state;
  wire [7:0] timeout_counter;
  wire [2:0] attempt_counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  DFFRHQX1 door_locked_reg(.RN (rst_n), .CK (clk), .D (n_54), .Q
       (door_locked));
  DFFRHQX1 \lock_status_reg[1] (.RN (rst_n), .CK (clk), .D (state[1]),
       .Q (lock_status[1]));
  DFFRHQX1 \lock_status_reg[0] (.RN (rst_n), .CK (clk), .D (state[0]),
       .Q (lock_status[0]));
  OR2XL g754(.A (state[0]), .B (state[1]), .Y (n_54));
  DFFRHQX1 \timeout_counter_reg[7] (.RN (rst_n), .CK (clk), .D (n_53),
       .Q (timeout_counter[7]));
  DFFRHQX1 \timeout_counter_reg[6] (.RN (rst_n), .CK (clk), .D (n_51),
       .Q (timeout_counter[6]));
  NOR2XL g2214(.A (n_27), .B (n_52), .Y (n_53));
  AOI21XL g2215(.A0 (timeout_counter[6]), .A1 (n_48), .B0
       (timeout_counter[7]), .Y (n_52));
  NOR2XL g2216(.A (n_27), .B (n_50), .Y (n_51));
  DFFRHQX1 \timeout_counter_reg[5] (.RN (rst_n), .CK (clk), .D (n_49),
       .Q (timeout_counter[5]));
  MXI2XL g2218(.A (n_48), .B (n_45), .S0 (timeout_counter[6]), .Y
       (n_50));
  NOR2XL g2219(.A (n_47), .B (n_27), .Y (n_49));
  CLKINVX1 g2220(.A (n_45), .Y (n_48));
  DFFRHQX1 \timeout_counter_reg[4] (.RN (rst_n), .CK (clk), .D (n_44),
       .Q (timeout_counter[4]));
  AOI21XL g2222(.A0 (timeout_counter[5]), .A1 (n_41), .B0 (n_46), .Y
       (n_47));
  NOR2XL g2223(.A (timeout_counter[5]), .B (n_41), .Y (n_46));
  NOR2XL g2224(.A (n_43), .B (n_27), .Y (n_44));
  NAND2BX1 g2225(.AN (n_41), .B (timeout_counter[5]), .Y (n_45));
  DFFRHQX1 \timeout_counter_reg[3] (.RN (rst_n), .CK (clk), .D (n_40),
       .Q (timeout_counter[3]));
  AOI21XL g2227(.A0 (timeout_counter[4]), .A1 (n_36), .B0 (n_42), .Y
       (n_43));
  NOR2XL g2228(.A (timeout_counter[4]), .B (n_36), .Y (n_42));
  NOR2XL g2229(.A (n_39), .B (n_27), .Y (n_40));
  NAND2BX1 g2230(.AN (n_36), .B (timeout_counter[4]), .Y (n_41));
  DFFRHQX1 \timeout_counter_reg[1] (.RN (rst_n), .CK (clk), .D (n_32),
       .Q (timeout_counter[1]));
  DFFRHQX1 \timeout_counter_reg[2] (.RN (rst_n), .CK (clk), .D (n_30),
       .Q (timeout_counter[2]));
  AOI21X1 g2237(.A0 (timeout_counter[3]), .A1 (n_21), .B0 (n_34), .Y
       (n_39));
  AO21X1 g2238(.A0 (attempt_counter[0]), .A1 (n_28), .B0 (n_26), .Y
       (n_38));
  OAI22X1 g2239(.A0 (n_19), .A1 (n_15), .B0 (n_5), .B1 (n_29), .Y
       (n_37));
  DFFRHQX1 \timeout_counter_reg[0] (.RN (rst_n), .CK (clk), .D (n_35),
       .Q (timeout_counter[0]));
  NOR2XL g2241(.A (timeout_counter[0]), .B (n_27), .Y (n_35));
  NOR2XL g2242(.A (timeout_counter[3]), .B (n_21), .Y (n_34));
  NAND2BX1 g2243(.AN (n_21), .B (timeout_counter[3]), .Y (n_36));
  OAI221X1 g2244(.A0 (n_2), .A1 (n_22), .B0 (state[0]), .B1 (n_8), .C0
       (n_25), .Y (n_33));
  NOR2XL g2245(.A (n_10), .B (n_27), .Y (n_32));
  NAND2XL g2246(.A (n_19), .B (n_27), .Y (n_31));
  NOR2XL g2247(.A (n_24), .B (n_27), .Y (n_30));
  INVXL g2249(.A (n_28), .Y (n_29));
  OAI21X1 g2250(.A0 (n_4), .A1 (n_19), .B0 (n_11), .Y (n_28));
  OAI21X1 g2251(.A0 (n_18), .A1 (n_22), .B0 (state[1]), .Y (n_27));
  AOI211X1 g2252(.A0 (attempt_counter[1]), .A1 (attempt_counter[2]),
       .B0 (attempt_counter[0]), .C0 (n_19), .Y (n_26));
  OAI21X1 g2253(.A0 (n_9), .A1 (n_16), .B0 (state[0]), .Y (n_25));
  AOI21XL g2254(.A0 (timeout_counter[2]), .A1 (n_6), .B0 (n_20), .Y
       (n_24));
  OAI21X1 g2255(.A0 (n_4), .A1 (n_11), .B0 (n_17), .Y (n_23));
  NOR2XL g2256(.A (timeout_counter[2]), .B (n_6), .Y (n_20));
  AOI31X1 g2257(.A0 (timeout_counter[5]), .A1 (timeout_counter[6]), .A2
       (n_14), .B0 (timeout_counter[7]), .Y (n_22));
  NAND2BX1 g2258(.AN (n_6), .B (timeout_counter[2]), .Y (n_21));
  AOI31X1 g2259(.A0 (timeout_counter[7]), .A1 (timeout_counter[6]), .A2
       (n_0), .B0 (n_1), .Y (n_18));
  NAND3BX1 g2260(.AN (n_9), .B (state[0]), .C (n_16), .Y (n_17));
  NAND3BX1 g2261(.AN (n_9), .B (n_12), .C (state[0]), .Y (n_19));
  NOR2BX1 g2262(.AN (n_12), .B (n_13), .Y (n_16));
  AOI32X1 g2263(.A0 (attempt_counter[0]), .A1 (n_5), .A2 (n_4), .B0
       (attempt_counter[1]), .B1 (n_3), .Y (n_15));
  NAND2BX1 g2265(.AN (timeout_counter[2]), .B (n_7), .Y (n_14));
  AOI21X1 g2266(.A0 (attempt_counter[0]), .A1 (attempt_counter[1]), .B0
       (attempt_counter[2]), .Y (n_13));
  XNOR2XL g2267(.A (timeout_counter[0]), .B (timeout_counter[1]), .Y
       (n_10));
  NAND4BXL g2268(.AN (pin_input[3]), .B (pin_input[0]), .C
       (pin_input[1]), .D (pin_input[2]), .Y (n_12));
  AOI2BB1X1 g2269(.A0N (unlock_cmd), .A1N (n_1), .B0 (state[1]), .Y
       (n_11));
  NAND2XL g2270(.A (lock_cmd), .B (n_2), .Y (n_8));
  NAND2XL g2271(.A (unlock_cmd), .B (n_2), .Y (n_9));
  NOR2XL g2272(.A (timeout_counter[3]), .B (timeout_counter[4]), .Y
       (n_7));
  NAND2XL g2273(.A (timeout_counter[0]), .B (timeout_counter[1]), .Y
       (n_6));
  NAND2BX1 g2(.AN (timeout_counter[5]), .B (n_7), .Y (n_0));
  DFFRX1 \state_reg[1] (.RN (rst_n), .CK (clk), .D (n_31), .Q
       (state[1]), .QN (n_2));
  DFFRX1 \attempt_counter_reg[1] (.RN (rst_n), .CK (clk), .D (n_37), .Q
       (attempt_counter[1]), .QN (n_5));
  DFFRX1 \attempt_counter_reg[2] (.RN (rst_n), .CK (clk), .D (n_23), .Q
       (attempt_counter[2]), .QN (n_4));
  DFFRX1 \attempt_counter_reg[0] (.RN (rst_n), .CK (clk), .D (n_38), .Q
       (attempt_counter[0]), .QN (n_3));
  DFFRX1 \state_reg[0] (.RN (rst_n), .CK (clk), .D (n_33), .Q
       (state[0]), .QN (n_1));
endmodule

module entertainment_system(clk, rst_n, tv_on_cmd, music_on_cmd,
     volume_cmd, tv_on, music_on, volume_level);
  input clk, rst_n, tv_on_cmd, music_on_cmd;
  input [3:0] volume_cmd;
  output tv_on, music_on;
  output [3:0] volume_level;
  wire clk, rst_n, tv_on_cmd, music_on_cmd;
  wire [3:0] volume_cmd;
  wire tv_on, music_on;
  wire [3:0] volume_level;
  wire n_0;
  DFFRHQX1 tv_on_reg(.RN (rst_n), .CK (clk), .D (tv_on_cmd), .Q
       (tv_on));
  DFFRHQX1 music_on_reg(.RN (rst_n), .CK (clk), .D (music_on_cmd), .Q
       (music_on));
  SDFFSHQX1 \volume_level_reg[0] (.SN (rst_n), .CK (clk), .D
       (volume_cmd[0]), .SI (volume_level[0]), .SE (n_0), .Q
       (volume_level[0]));
  SDFFSHQX1 \volume_level_reg[2] (.SN (rst_n), .CK (clk), .D
       (volume_cmd[2]), .SI (volume_level[2]), .SE (n_0), .Q
       (volume_level[2]));
  SDFFRHQX1 \volume_level_reg[1] (.RN (rst_n), .CK (clk), .D
       (volume_cmd[1]), .SI (volume_level[1]), .SE (n_0), .Q
       (volume_level[1]));
  SDFFRHQX1 \volume_level_reg[3] (.RN (rst_n), .CK (clk), .D
       (volume_cmd[3]), .SI (volume_level[3]), .SE (n_0), .Q
       (volume_level[3]));
  NOR4X1 g44(.A (volume_cmd[3]), .B (volume_cmd[2]), .C
       (volume_cmd[1]), .D (volume_cmd[0]), .Y (n_0));
endmodule

module humidity_controller(clk, rst_n, humidity_sensor, humidifier_on,
     dehumidifier_on);
  input clk, rst_n;
  input [7:0] humidity_sensor;
  output humidifier_on, dehumidifier_on;
  wire clk, rst_n;
  wire [7:0] humidity_sensor;
  wire humidifier_on, dehumidifier_on;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  DFFRHQX1 dehumidifier_on_reg(.RN (rst_n), .CK (clk), .D (n_5), .Q
       (dehumidifier_on));
  DFFRHQX1 humidifier_on_reg(.RN (rst_n), .CK (clk), .D (n_4), .Q
       (humidifier_on));
  AOI21X1 g202(.A0 (n_0), .A1 (n_1), .B0 (n_3), .Y (n_5));
  AOI21X1 g203(.A0 (humidity_sensor[5]), .A1 (humidity_sensor[3]), .B0
       (n_2), .Y (n_4));
  INVXL g204(.A (n_2), .Y (n_3));
  OAI2BB1X1 g205(.A0N (humidity_sensor[4]), .A1N (humidity_sensor[5]),
       .B0 (n_0), .Y (n_2));
  OAI211X1 g206(.A0 (humidity_sensor[1]), .A1 (humidity_sensor[0]), .B0
       (humidity_sensor[2]), .C0 (humidity_sensor[3]), .Y (n_1));
  NOR2XL g207(.A (humidity_sensor[7]), .B (humidity_sensor[6]), .Y
       (n_0));
endmodule

module luminosity_controller(clk, rst_n, light_sensor, led_brightness);
  input clk, rst_n;
  input [7:0] light_sensor;
  output [7:0] led_brightness;
  wire clk, rst_n;
  wire [7:0] light_sensor;
  wire [7:0] led_brightness;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  DFFRHQX1 \led_brightness_reg[4] (.RN (rst_n), .CK (clk), .D (n_5), .Q
       (led_brightness[4]));
  DFFRHQX1 \led_brightness_reg[6] (.RN (rst_n), .CK (clk), .D (n_6), .Q
       (led_brightness[6]));
  DFFRHQX1 \led_brightness_reg[7] (.RN (rst_n), .CK (clk), .D (n_7), .Q
       (led_brightness[7]));
  DFFRHQX1 \led_brightness_reg[0] (.RN (rst_n), .CK (clk), .D (n_4), .Q
       (led_brightness[0]));
  DFFRHQX1 \led_brightness_reg[2] (.RN (rst_n), .CK (clk), .D (n_0), .Q
       (led_brightness[2]));
  DFFRHQX1 \led_brightness_reg[5] (.RN (rst_n), .CK (clk), .D (n_1), .Q
       (led_brightness[5]));
  DFFRHQX1 \led_brightness_reg[3] (.RN (rst_n), .CK (clk), .D (n_2), .Q
       (led_brightness[3]));
  DFFRHQX1 \led_brightness_reg[1] (.RN (rst_n), .CK (clk), .D (n_3), .Q
       (led_brightness[1]));
  INVXL g95(.A (light_sensor[7]), .Y (n_7));
  INVXL g96(.A (light_sensor[6]), .Y (n_6));
  INVXL g97(.A (light_sensor[4]), .Y (n_5));
  INVXL g98(.A (light_sensor[0]), .Y (n_4));
  INVXL g99(.A (light_sensor[1]), .Y (n_3));
  INVXL g100(.A (light_sensor[3]), .Y (n_2));
  INVXL g101(.A (light_sensor[5]), .Y (n_1));
  INVXL g102(.A (light_sensor[2]), .Y (n_0));
endmodule

module temperature_controller(clk, rst_n, temp_sensor, temp_setpoint,
     heater_on, cooler_on);
  input clk, rst_n;
  input [7:0] temp_sensor, temp_setpoint;
  output heater_on, cooler_on;
  wire clk, rst_n;
  wire [7:0] temp_sensor, temp_setpoint;
  wire heater_on, cooler_on;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  SDFFRHQX1 cooler_on_reg(.RN (rst_n), .CK (clk), .D (n_64), .SI
       (n_40), .SE (n_69), .Q (cooler_on));
  DFFRHQX1 heater_on_reg(.RN (rst_n), .CK (clk), .D (n_70), .Q
       (heater_on));
  MXI2XL g1650(.A (n_64), .B (n_43), .S0 (n_69), .Y (n_70));
  NOR2BX1 g1651(.AN (n_64), .B (n_68), .Y (n_69));
  AOI211X1 g1652(.A0 (n_59), .A1 (n_60), .B0 (n_66), .C0 (n_67), .Y
       (n_68));
  OAI33X1 g1653(.A0 (temp_sensor[4]), .A1 (n_39), .A2 (n_65), .B0
       (temp_sensor[5]), .B1 (n_48), .B2 (n_62), .Y (n_67));
  AOI211X1 g1654(.A0 (temp_sensor[4]), .A1 (n_39), .B0 (n_45), .C0
       (n_65), .Y (n_66));
  OAI2BB1X1 g1655(.A0N (temp_sensor[5]), .A1N (n_48), .B0 (n_61), .Y
       (n_65));
  AOI21X1 g1656(.A0 (n_6), .A1 (n_55), .B0 (n_63), .Y (n_64));
  AOI211X1 g1657(.A0 (temp_sensor[6]), .A1 (n_54), .B0 (n_58), .C0
       (n_56), .Y (n_63));
  INVXL g1658(.A (n_61), .Y (n_62));
  AOI22X1 g1659(.A0 (temp_sensor[6]), .A1 (n_53), .B0 (temp_sensor[7]),
       .B1 (n_57), .Y (n_61));
  OAI31X1 g1660(.A0 (temp_sensor[7]), .A1 (temp_sensor[6]), .A2 (n_53),
       .B0 (n_57), .Y (n_60));
  OAI21X1 g1661(.A0 (temp_sensor[6]), .A1 (n_53), .B0 (temp_sensor[7]),
       .Y (n_59));
  NOR2XL g1662(.A (n_6), .B (n_55), .Y (n_58));
  AOI21X1 g1663(.A0 (temp_setpoint[6]), .A1 (n_47), .B0
       (temp_setpoint[7]), .Y (n_57));
  AOI211X1 g1664(.A0 (temp_setpoint[6]), .A1 (n_38), .B0 (n_50), .C0
       (n_52), .Y (n_56));
  CLKXOR2X1 g1665(.A (temp_setpoint[7]), .B (n_50), .Y (n_55));
  NAND2XL g1666(.A (n_49), .B (n_51), .Y (n_54));
  AND3X1 g1667(.A (n_2), .B (n_49), .C (n_51), .Y (n_52));
  MXI2XL g1668(.A (temp_setpoint[6]), .B (n_3), .S0 (n_47), .Y (n_53));
  OAI222XL g1669(.A0 (n_36), .A1 (n_46), .B0 (temp_sensor[5]), .B1
       (n_44), .C0 (n_41), .C1 (temp_sensor[4]), .Y (n_51));
  NOR2XL g1670(.A (temp_setpoint[6]), .B (n_38), .Y (n_50));
  NAND2XL g1671(.A (temp_sensor[5]), .B (n_44), .Y (n_49));
  AO21X1 g1672(.A0 (n_4), .A1 (n_32), .B0 (n_47), .Y (n_48));
  NOR2XL g1673(.A (n_4), .B (n_32), .Y (n_47));
  OAI22X1 g1674(.A0 (n_34), .A1 (n_42), .B0 (n_7), .B1 (n_27), .Y
       (n_46));
  AOI21X1 g1675(.A0 (n_30), .A1 (n_31), .B0 (n_37), .Y (n_45));
  OA21X1 g1676(.A0 (n_4), .A1 (n_34), .B0 (n_38), .Y (n_44));
  NAND2XL g1677(.A (n_33), .B (heater_on), .Y (n_43));
  NAND2XL g1678(.A (temp_sensor[4]), .B (n_35), .Y (n_42));
  NOR2BX1 g1679(.AN (n_35), .B (n_34), .Y (n_41));
  AND2X1 g1680(.A (n_33), .B (cooler_on), .Y (n_40));
  AOI221X1 g1681(.A0 (temp_sensor[2]), .A1 (n_19), .B0
       (temp_sensor[3]), .B1 (n_25), .C0 (n_26), .Y (n_37));
  AOI221X1 g1682(.A0 (n_19), .A1 (n_24), .B0 (n_7), .B1 (n_27), .C0
       (n_29), .Y (n_36));
  OAI21X1 g1683(.A0 (temp_setpoint[4]), .A1 (n_20), .B0 (n_32), .Y
       (n_39));
  NAND2XL g1684(.A (n_4), .B (n_34), .Y (n_38));
  NAND2XL g1685(.A (temp_setpoint[4]), .B (n_21), .Y (n_35));
  NOR2XL g1686(.A (temp_setpoint[4]), .B (n_21), .Y (n_34));
  OAI31X1 g1687(.A0 (temp_sensor[2]), .A1 (temp_sensor[3]), .A2 (n_19),
       .B0 (n_25), .Y (n_31));
  NAND4XL g1688(.A (n_0), .B (n_15), .C (n_23), .D (n_28), .Y (n_33));
  NAND2XL g1689(.A (temp_setpoint[4]), .B (n_20), .Y (n_32));
  OAI21X1 g1690(.A0 (temp_sensor[2]), .A1 (n_19), .B0 (temp_sensor[3]),
       .Y (n_30));
  AOI21X1 g1691(.A0 (n_9), .A1 (n_22), .B0 (temp_sensor[2]), .Y (n_29));
  NOR4X1 g1692(.A (n_1), .B (n_16), .C (n_17), .D (n_18), .Y (n_28));
  OAI2BB1X1 g1693(.A0N (n_11), .A1N (n_9), .B0 (n_12), .Y (n_26));
  OAI21X1 g1694(.A0 (n_8), .A1 (n_10), .B0 (n_21), .Y (n_27));
  NAND3X1 g1695(.A (temp_sensor[2]), .B (n_9), .C (n_22), .Y (n_24));
  AOI211X1 g1696(.A0 (n_12), .A1 (n_9), .B0 (n_11), .C0 (n_14), .Y
       (n_23));
  AO21X1 g1697(.A0 (n_8), .A1 (n_13), .B0 (n_20), .Y (n_25));
  NAND2XL g1699(.A (n_12), .B (n_14), .Y (n_22));
  NAND2XL g1700(.A (n_8), .B (n_10), .Y (n_21));
  NOR2XL g1701(.A (n_8), .B (n_13), .Y (n_20));
  NAND2BX1 g1702(.AN (n_10), .B (n_13), .Y (n_19));
  OAI22X1 g1703(.A0 (temp_sensor[5]), .A1 (n_4), .B0 (temp_sensor[6]),
       .B1 (n_3), .Y (n_18));
  OAI22X1 g1704(.A0 (temp_setpoint[5]), .A1 (n_5), .B0
       (temp_setpoint[6]), .B1 (n_2), .Y (n_17));
  MXI2XL g1705(.A (n_6), .B (temp_sensor[7]), .S0 (temp_setpoint[7]),
       .Y (n_16));
  AOI22X1 g1707(.A0 (temp_sensor[3]), .A1 (n_8), .B0
       (temp_setpoint[3]), .B1 (n_7), .Y (n_15));
  NOR2BX1 g1708(.AN (temp_setpoint[0]), .B (temp_sensor[0]), .Y (n_14));
  NAND2XL g1709(.A (temp_setpoint[2]), .B (temp_setpoint[1]), .Y
       (n_13));
  NAND2XL g1710(.A (temp_sensor[1]), .B (temp_setpoint[1]), .Y (n_12));
  NOR2BX1 g1711(.AN (temp_sensor[0]), .B (temp_setpoint[0]), .Y (n_11));
  NOR2XL g1712(.A (temp_setpoint[2]), .B (temp_setpoint[1]), .Y (n_10));
  OR2X1 g1713(.A (temp_sensor[1]), .B (temp_setpoint[1]), .Y (n_9));
  CLKINVX1 g1714(.A (temp_setpoint[3]), .Y (n_8));
  CLKINVX1 g1716(.A (temp_sensor[3]), .Y (n_7));
  INVX1 g1717(.A (temp_sensor[7]), .Y (n_6));
  INVXL g1718(.A (temp_sensor[5]), .Y (n_5));
  CLKINVX1 g1719(.A (temp_setpoint[5]), .Y (n_4));
  CLKINVX1 g1721(.A (temp_setpoint[6]), .Y (n_3));
  INVX1 g1722(.A (temp_sensor[6]), .Y (n_2));
  XOR2XL g2(.A (temp_sensor[4]), .B (temp_setpoint[4]), .Y (n_1));
  XNOR2XL g1723(.A (temp_sensor[2]), .B (temp_setpoint[2]), .Y (n_0));
endmodule

module visitor_counter(clk, rst_n, entry_sensor, exit_sensor, count);
  input clk, rst_n, entry_sensor, exit_sensor;
  output [7:0] count;
  wire clk, rst_n, entry_sensor, exit_sensor;
  wire [7:0] count;
  wire UNCONNECTED, entry_prev, exit_prev, n_0, n_1, n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49;
  DFFRHQX1 \count_reg[2] (.RN (rst_n), .CK (clk), .D (n_46), .Q
       (count[2]));
  DFFRHQX1 \count_reg[4] (.RN (rst_n), .CK (clk), .D (n_49), .Q
       (count[4]));
  INVXL g797(.A (n_48), .Y (n_49));
  AOI222XL g798(.A0 (n_14), .A1 (n_29), .B0 (n_13), .B1 (n_23), .C0
       (n_34), .C1 (count[4]), .Y (n_48));
  DFFRHQX1 \count_reg[7] (.RN (rst_n), .CK (clk), .D (n_41), .Q
       (count[7]));
  DFFRHQX1 \count_reg[1] (.RN (rst_n), .CK (clk), .D (n_40), .Q
       (count[1]));
  INVXL g801(.A (n_44), .Y (n_47));
  INVXL g802(.A (n_43), .Y (n_46));
  OAI2BB1XL g803(.A0N (count[5]), .A1N (n_35), .B0 (n_39), .Y (n_45));
  AOI222XL g804(.A0 (n_18), .A1 (n_29), .B0 (n_17), .B1 (n_23), .C0
       (n_32), .C1 (count[6]), .Y (n_44));
  AOI222XL g805(.A0 (n_9), .A1 (n_29), .B0 (n_8), .B1 (n_23), .C0
       (n_31), .C1 (count[2]), .Y (n_43));
  OAI2BB1XL g806(.A0N (count[3]), .A1N (n_33), .B0 (n_36), .Y (n_42));
  SDFFRHQX1 \count_reg[0] (.RN (rst_n), .CK (clk), .D (n_27), .SI
       (n_26), .SE (count[0]), .Q (count[0]));
  OAI2BB1XL g808(.A0N (n_20), .A1N (n_23), .B0 (n_37), .Y (n_41));
  OAI21X1 g809(.A0 (n_10), .A1 (n_30), .B0 (n_38), .Y (n_40));
  AOI32XL g810(.A0 (n_23), .A1 (n_4), .A2 (n_1), .B0 (n_29), .B1
       (n_15), .Y (n_39));
  AOI22X1 g811(.A0 (count[1]), .A1 (n_26), .B0 (n_10), .B1 (n_23), .Y
       (n_38));
  OAI31XL g812(.A0 (n_23), .A1 (n_19), .A2 (n_26), .B0 (count[7]), .Y
       (n_37));
  AOI32XL g813(.A0 (n_23), .A1 (n_5), .A2 (n_0), .B0 (n_29), .B1
       (n_12), .Y (n_36));
  OAI221XL g814(.A0 (n_14), .A1 (n_30), .B0 (n_1), .B1 (n_22), .C0
       (n_27), .Y (n_35));
  OAI211XL g815(.A0 (n_30), .A1 (n_12), .B0 (n_28), .C0 (n_27), .Y
       (n_34));
  OAI221XL g816(.A0 (n_9), .A1 (n_30), .B0 (n_0), .B1 (n_22), .C0
       (n_27), .Y (n_33));
  OAI211XL g817(.A0 (n_30), .A1 (n_15), .B0 (n_25), .C0 (n_27), .Y
       (n_32));
  OAI211XL g818(.A0 (n_30), .A1 (n_7), .B0 (n_24), .C0 (n_27), .Y
       (n_31));
  CLKINVX1 g819(.A (n_30), .Y (n_29));
  NAND2XL g820(.A (n_11), .B (n_23), .Y (n_28));
  OR2X1 g821(.A (n_21), .B (n_23), .Y (n_30));
  CLKINVX1 g822(.A (n_27), .Y (n_26));
  NAND2XL g823(.A (n_16), .B (n_23), .Y (n_25));
  NAND2XL g824(.A (n_6), .B (n_23), .Y (n_24));
  NAND2XL g825(.A (n_21), .B (n_22), .Y (n_27));
  INVX1 g826(.A (n_23), .Y (n_22));
  AOI211X1 g827(.A0 (count[7]), .A1 (n_20), .B0 (entry_prev), .C0
       (n_3), .Y (n_23));
  OAI211X1 g828(.A0 (count[7]), .A1 (n_19), .B0 (exit_sensor), .C0
       (exit_prev), .Y (n_21));
  NOR2XL g829(.A (n_2), .B (n_16), .Y (n_20));
  INVXL g830(.A (n_19), .Y (n_18));
  NOR2XL g831(.A (count[6]), .B (n_16), .Y (n_17));
  NAND2XL g832(.A (n_2), .B (n_15), .Y (n_19));
  NAND2XL g833(.A (count[5]), .B (n_1), .Y (n_16));
  AND2X1 g834(.A (n_4), .B (n_14), .Y (n_15));
  NOR2BX1 g835(.AN (n_12), .B (count[4]), .Y (n_14));
  NOR2XL g836(.A (count[4]), .B (n_11), .Y (n_13));
  AND2X1 g838(.A (n_5), .B (n_9), .Y (n_12));
  NAND2XL g839(.A (count[3]), .B (n_0), .Y (n_11));
  NOR2BX1 g840(.AN (n_6), .B (n_7), .Y (n_10));
  NOR2BX1 g841(.AN (n_7), .B (count[2]), .Y (n_9));
  NOR2XL g842(.A (count[2]), .B (n_6), .Y (n_8));
  DFFRXL exit_prev_reg(.RN (rst_n), .CK (clk), .D (exit_sensor), .Q
       (UNCONNECTED), .QN (exit_prev));
  DFFRHQX1 entry_prev_reg(.RN (rst_n), .CK (clk), .D (entry_sensor), .Q
       (entry_prev));
  NOR2XL g846(.A (count[0]), .B (count[1]), .Y (n_7));
  NAND2XL g847(.A (count[0]), .B (count[1]), .Y (n_6));
  INVX1 g858(.A (entry_sensor), .Y (n_3));
  NOR2BX1 g2(.AN (count[4]), .B (n_11), .Y (n_1));
  NOR2BX1 g864(.AN (count[2]), .B (n_6), .Y (n_0));
  DFFRX1 \count_reg[3] (.RN (rst_n), .CK (clk), .D (n_42), .Q
       (count[3]), .QN (n_5));
  DFFRX1 \count_reg[5] (.RN (rst_n), .CK (clk), .D (n_45), .Q
       (count[5]), .QN (n_4));
  DFFRX1 \count_reg[6] (.RN (rst_n), .CK (clk), .D (n_47), .Q
       (count[6]), .QN (n_2));
endmodule

module water_level_controller(clk, rst_n, water_level, pump_on,
     valve_close);
  input clk, rst_n;
  input [3:0] water_level;
  output pump_on, valve_close;
  wire clk, rst_n;
  wire [3:0] water_level;
  wire pump_on, valve_close;
  wire n_0, n_1, n_11;
  DFFRHQX1 valve_close_reg(.RN (rst_n), .CK (clk), .D (n_1), .Q
       (valve_close));
  AOI211X1 g81(.A0 (water_level[1]), .A1 (water_level[0]), .B0
       (water_level[3]), .C0 (water_level[2]), .Y (n_0));
  NOR2BXL g2(.AN (n_11), .B (n_0), .Y (n_1));
  SDFFRHQX1 pump_on_reg(.RN (rst_n), .CK (clk), .D (pump_on), .SI
       (n_0), .SE (n_11), .Q (pump_on));
  AO21X1 g82(.A0 (water_level[2]), .A1 (water_level[3]), .B0 (n_0), .Y
       (n_11));
endmodule

module window_treatment(clk, rst_n, auto_mode, light_level,
     manual_open, manual_close, window_state);
  input clk, rst_n, auto_mode, manual_open, manual_close;
  input [7:0] light_level;
  output [1:0] window_state;
  wire clk, rst_n, auto_mode, manual_open, manual_close;
  wire [7:0] light_level;
  wire [1:0] window_state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12;
  DFFRHQX1 \window_state_reg[0] (.RN (rst_n), .CK (clk), .D (n_12), .Q
       (window_state[0]));
  AO22XL g361(.A0 (auto_mode), .A1 (n_11), .B0 (n_2), .B1
       (window_state[0]), .Y (n_12));
  DFFRHQX1 \window_state_reg[1] (.RN (rst_n), .CK (clk), .D (n_10), .Q
       (window_state[1]));
  MXI2XL g363(.A (n_7), .B (n_9), .S0 (light_level[6]), .Y (n_11));
  OAI21X1 g364(.A0 (auto_mode), .A1 (n_3), .B0 (n_8), .Y (n_10));
  NOR2BXL g365(.AN (light_level[7]), .B (n_6), .Y (n_9));
  NAND3BX1 g366(.AN (light_level[6]), .B (auto_mode), .C (n_7), .Y
       (n_8));
  AOI31X1 g367(.A0 (light_level[5]), .A1 (light_level[4]), .A2 (n_4),
       .B0 (light_level[7]), .Y (n_7));
  AOI211X1 g368(.A0 (light_level[3]), .A1 (n_5), .B0 (light_level[5]),
       .C0 (light_level[4]), .Y (n_6));
  NAND2BX1 g369(.AN (light_level[0]), .B (n_1), .Y (n_5));
  NAND2BXL g370(.AN (light_level[3]), .B (n_1), .Y (n_4));
  AOI21X1 g371(.A0 (n_0), .A1 (window_state[1]), .B0 (manual_open), .Y
       (n_3));
  NOR3X1 g372(.A (manual_open), .B (manual_close), .C (auto_mode), .Y
       (n_2));
  NOR2XL g373(.A (light_level[2]), .B (light_level[1]), .Y (n_1));
  INVXL g374(.A (manual_close), .Y (n_0));
endmodule

module HA(clk, rst_n, temp_sensor, temp_setpoint, water_level,
     light_sensor, motion_sensor, door_sensor, window_sensor,
     alarm_arm, entry_sensor, exit_sensor, window_auto_mode,
     window_manual_open, window_manual_close, tv_on_cmd, music_on_cmd,
     volume_cmd, ac_cmd, fan_cmd, light_cmd, door_lock_cmd,
     door_unlock_cmd, pin_input, humidity_sensor, heater_on, cooler_on,
     water_pump_on, water_valve_close, led_brightness,
     burglar_alarm_out, visitor_count, window_state, tv_on, music_on,
     volume_level, ac_on, fan_on, lights_on, door_locked, lock_status,
     humidifier_on, dehumidifier_on, system_status);
  input clk, rst_n, motion_sensor, door_sensor, window_sensor,
       alarm_arm, entry_sensor, exit_sensor, window_auto_mode,
       window_manual_open, window_manual_close, tv_on_cmd,
       music_on_cmd, ac_cmd, fan_cmd, light_cmd, door_lock_cmd,
       door_unlock_cmd;
  input [7:0] temp_sensor, temp_setpoint, light_sensor, humidity_sensor;
  input [3:0] water_level, volume_cmd, pin_input;
  output heater_on, cooler_on, water_pump_on, water_valve_close,
       burglar_alarm_out, tv_on, music_on, ac_on, fan_on, lights_on,
       door_locked, humidifier_on, dehumidifier_on;
  output [7:0] led_brightness, visitor_count, system_status;
  output [1:0] window_state, lock_status;
  output [3:0] volume_level;
  wire clk, rst_n, motion_sensor, door_sensor, window_sensor,
       alarm_arm, entry_sensor, exit_sensor, window_auto_mode,
       window_manual_open, window_manual_close, tv_on_cmd,
       music_on_cmd, ac_cmd, fan_cmd, light_cmd, door_lock_cmd,
       door_unlock_cmd;
  wire [7:0] temp_sensor, temp_setpoint, light_sensor, humidity_sensor;
  wire [3:0] water_level, volume_cmd, pin_input;
  wire heater_on, cooler_on, water_pump_on, water_valve_close,
       burglar_alarm_out, tv_on, music_on, ac_on, fan_on, lights_on,
       door_locked, humidifier_on, dehumidifier_on;
  wire [7:0] led_brightness, visitor_count, system_status;
  wire [1:0] window_state, lock_status;
  wire [3:0] volume_level;
  wire [3:0] pin_input_r;
  wire [1:0] lock_status_int;
  wire [3:0] volume_cmd_r;
  wire [3:0] volume_level_int;
  wire [7:0] humidity_sensor_r;
  wire [7:0] light_sensor_r;
  wire [7:0] led_brightness_int;
  wire [7:0] temp_sensor_r;
  wire [7:0] temp_setpoint_r;
  wire [7:0] visitor_count_int;
  wire [3:0] water_level_r;
  wire [1:0] window_state_int;
  wire ac_cmd_r, ac_on_int, alarm_arm_r, burglar_alarm_out_int,
       cooler_on_int, dehumidifier_on_int, door_lock_cmd_r,
       door_locked_int;
  wire door_sensor_r, door_unlock_cmd_r, entry_sensor_r, exit_sensor_r,
       fan_cmd_r, fan_on_int, heater_on_int, humidifier_on_int;
  wire light_cmd_r, lights_on_int, motion_sensor_r, music_on_cmd_r,
       music_on_int, tv_on_cmd_r, tv_on_int, water_pump_on_int;
  wire water_valve_close_int, window_auto_mode_r,
       window_manual_close_r, window_manual_open_r, window_sensor_r;
  assign system_status[0] = cooler_on;
  assign system_status[1] = heater_on;
  assign system_status[2] = lights_on;
  assign system_status[3] = fan_on;
  assign system_status[4] = ac_on;
  assign system_status[5] = door_locked;
  assign system_status[6] = water_pump_on;
  assign system_status[7] = burglar_alarm_out;
  appliances_controller u_appliances(.clk (clk), .rst_n (rst_n),
       .ac_cmd (ac_cmd_r), .fan_cmd (fan_cmd_r), .light_cmd
       (light_cmd_r), .ac_on (ac_on_int), .fan_on (fan_on_int),
       .lights_on (lights_on_int));
  burglar_alarm u_burglar(.clk (clk), .rst_n (rst_n), .motion_sensor
       (motion_sensor_r), .door_sensor (door_sensor_r), .window_sensor
       (window_sensor_r), .alarm_arm (alarm_arm_r), .alarm_out
       (burglar_alarm_out_int));
  door_lock_controller u_door_lock(.clk (clk), .rst_n (rst_n),
       .lock_cmd (door_lock_cmd_r), .unlock_cmd (door_unlock_cmd_r),
       .pin_input (pin_input_r), .door_locked (door_locked_int),
       .lock_status (lock_status_int));
  entertainment_system u_entertainment(.clk (clk), .rst_n (rst_n),
       .tv_on_cmd (tv_on_cmd_r), .music_on_cmd (music_on_cmd_r),
       .volume_cmd (volume_cmd_r), .tv_on (tv_on_int), .music_on
       (music_on_int), .volume_level (volume_level_int));
  humidity_controller u_humidity(.clk (clk), .rst_n (rst_n),
       .humidity_sensor (humidity_sensor_r), .humidifier_on
       (humidifier_on_int), .dehumidifier_on (dehumidifier_on_int));
  luminosity_controller u_lum_ctrl(.clk (clk), .rst_n (rst_n),
       .light_sensor (light_sensor_r), .led_brightness
       (led_brightness_int));
  temperature_controller u_temp_ctrl(.clk (clk), .rst_n (rst_n),
       .temp_sensor (temp_sensor_r), .temp_setpoint (temp_setpoint_r),
       .heater_on (heater_on_int), .cooler_on (cooler_on_int));
  visitor_counter u_visitor(.clk (clk), .rst_n (rst_n), .entry_sensor
       (entry_sensor_r), .exit_sensor (exit_sensor_r), .count
       (visitor_count_int));
  water_level_controller u_water_ctrl(.clk (clk), .rst_n (rst_n),
       .water_level (water_level_r), .pump_on (water_pump_on_int),
       .valve_close (water_valve_close_int));
  window_treatment u_window(.clk (clk), .rst_n (rst_n), .auto_mode
       (window_auto_mode_r), .light_level (light_sensor_r),
       .manual_open (window_manual_open_r), .manual_close
       (window_manual_close_r), .window_state (window_state_int));
  DFFRHQX1 water_valve_close_r_reg(.RN (rst_n), .CK (clk), .D
       (water_valve_close_int), .Q (water_valve_close));
  DFFRHQX1 tv_on_r_reg(.RN (rst_n), .CK (clk), .D (tv_on_int), .Q
       (tv_on));
  DFFRHQX1 music_on_r_reg(.RN (rst_n), .CK (clk), .D (music_on_int), .Q
       (music_on));
  DFFRHQX1 dehumidifier_on_r_reg(.RN (rst_n), .CK (clk), .D
       (dehumidifier_on_int), .Q (dehumidifier_on));
  DFFRHQX1 \led_brightness_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[2]), .Q (led_brightness[2]));
  DFFRHQX1 \led_brightness_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[7]), .Q (led_brightness[7]));
  DFFRHQX1 \lock_status_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (lock_status_int[1]), .Q (lock_status[1]));
  DFFRHQX1 \lock_status_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (lock_status_int[0]), .Q (lock_status[0]));
  DFFRHQX1 humidifier_on_r_reg(.RN (rst_n), .CK (clk), .D
       (humidifier_on_int), .Q (humidifier_on));
  DFFRHQX1 \led_brightness_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[4]), .Q (led_brightness[4]));
  DFFRHQX1 \led_brightness_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[3]), .Q (led_brightness[3]));
  DFFRHQX1 \led_brightness_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[6]), .Q (led_brightness[6]));
  DFFRHQX1 \led_brightness_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[0]), .Q (led_brightness[0]));
  DFFRHQX1 \led_brightness_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[1]), .Q (led_brightness[1]));
  DFFRHQX1 \led_brightness_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[5]), .Q (led_brightness[5]));
  DFFRHQX1 lights_on_r_reg(.RN (rst_n), .CK (clk), .D (lights_on_int),
       .Q (lights_on));
  DFFRHQX1 door_locked_r_reg(.RN (rst_n), .CK (clk), .D
       (door_locked_int), .Q (door_locked));
  DFFRHQX1 ac_on_r_reg(.RN (rst_n), .CK (clk), .D (ac_on_int), .Q
       (ac_on));
  DFFRHQX1 fan_on_r_reg(.RN (rst_n), .CK (clk), .D (fan_on_int), .Q
       (fan_on));
  DFFRHQX1 \volume_level_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (volume_level_int[3]), .Q (volume_level[3]));
  DFFRHQX1 \volume_level_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (volume_level_int[1]), .Q (volume_level[1]));
  DFFRHQX1 \volume_level_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (volume_level_int[0]), .Q (volume_level[0]));
  DFFRHQX1 \volume_level_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (volume_level_int[2]), .Q (volume_level[2]));
  DFFRHQX1 water_pump_on_r_reg(.RN (rst_n), .CK (clk), .D
       (water_pump_on_int), .Q (water_pump_on));
  DFFRHQX1 \humidity_sensor_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[7]), .Q (humidity_sensor_r[7]));
  DFFRHQX1 alarm_arm_r_reg(.RN (rst_n), .CK (clk), .D (alarm_arm), .Q
       (alarm_arm_r));
  DFFRHQX1 door_unlock_cmd_r_reg(.RN (rst_n), .CK (clk), .D
       (door_unlock_cmd), .Q (door_unlock_cmd_r));
  DFFRHQX1 \volume_cmd_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (volume_cmd[0]), .Q (volume_cmd_r[0]));
  DFFRHQX1 motion_sensor_r_reg(.RN (rst_n), .CK (clk), .D
       (motion_sensor), .Q (motion_sensor_r));
  DFFRHQX1 fan_cmd_r_reg(.RN (rst_n), .CK (clk), .D (fan_cmd), .Q
       (fan_cmd_r));
  DFFRHQX1 \pin_input_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (pin_input[1]), .Q (pin_input_r[1]));
  DFFRHQX1 \visitor_count_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[1]), .Q (visitor_count[1]));
  DFFRHQX1 window_auto_mode_r_reg(.RN (rst_n), .CK (clk), .D
       (window_auto_mode), .Q (window_auto_mode_r));
  DFFRHQX1 \visitor_count_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[5]), .Q (visitor_count[5]));
  DFFRHQX1 \visitor_count_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[4]), .Q (visitor_count[4]));
  DFFRHQX1 \visitor_count_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[2]), .Q (visitor_count[2]));
  DFFRHQX1 \visitor_count_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[3]), .Q (visitor_count[3]));
  DFFRHQX1 \temp_sensor_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[1]), .Q (temp_sensor_r[1]));
  DFFRHQX1 \visitor_count_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[0]), .Q (visitor_count[0]));
  DFFRHQX1 \window_state_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (window_state_int[1]), .Q (window_state[1]));
  DFFRHQX1 \window_state_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (window_state_int[0]), .Q (window_state[0]));
  DFFRHQX1 \temp_sensor_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[0]), .Q (temp_sensor_r[0]));
  DFFRHQX1 \temp_sensor_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[2]), .Q (temp_sensor_r[2]));
  DFFRHQX1 \visitor_count_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[7]), .Q (visitor_count[7]));
  DFFRHQX1 \visitor_count_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[6]), .Q (visitor_count[6]));
  DFFRHQX1 \temp_sensor_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[7]), .Q (temp_sensor_r[7]));
  DFFRHQX1 window_manual_close_r_reg(.RN (rst_n), .CK (clk), .D
       (window_manual_close), .Q (window_manual_close_r));
  DFFRHQX1 light_cmd_r_reg(.RN (rst_n), .CK (clk), .D (light_cmd), .Q
       (light_cmd_r));
  DFFRHQX1 ac_cmd_r_reg(.RN (rst_n), .CK (clk), .D (ac_cmd), .Q
       (ac_cmd_r));
  DFFRHQX1 window_manual_open_r_reg(.RN (rst_n), .CK (clk), .D
       (window_manual_open), .Q (window_manual_open_r));
  DFFRHQX1 \temp_setpoint_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[7]), .Q (temp_setpoint_r[7]));
  DFFRHQX1 window_sensor_r_reg(.RN (rst_n), .CK (clk), .D
       (window_sensor), .Q (window_sensor_r));
  DFFRHQX1 \temp_setpoint_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[6]), .Q (temp_setpoint_r[6]));
  DFFRHQX1 \temp_setpoint_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[5]), .Q (temp_setpoint_r[5]));
  DFFRHQX1 \temp_setpoint_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[4]), .Q (temp_setpoint_r[4]));
  DFFRHQX1 \temp_setpoint_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[3]), .Q (temp_setpoint_r[3]));
  DFFRHQX1 cooler_on_r_reg(.RN (rst_n), .CK (clk), .D (cooler_on_int),
       .Q (cooler_on));
  DFFRHQX1 \light_sensor_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (light_sensor[7]), .Q (light_sensor_r[7]));
  DFFRHQX1 burglar_alarm_out_r_reg(.RN (rst_n), .CK (clk), .D
       (burglar_alarm_out_int), .Q (burglar_alarm_out));
  DFFRHQX1 heater_on_r_reg(.RN (rst_n), .CK (clk), .D (heater_on_int),
       .Q (heater_on));
  DFFRHQX1 \water_level_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (water_level[2]), .Q (water_level_r[2]));
  DFFRHQX1 \temp_sensor_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[4]), .Q (temp_sensor_r[4]));
  DFFRHQX1 \temp_sensor_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[5]), .Q (temp_sensor_r[5]));
  DFFRHQX1 \temp_setpoint_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[0]), .Q (temp_setpoint_r[0]));
  DFFRHQX1 \temp_setpoint_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[1]), .Q (temp_setpoint_r[1]));
  DFFRHQX1 \temp_setpoint_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[2]), .Q (temp_setpoint_r[2]));
  DFFRHQX1 \temp_sensor_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[3]), .Q (temp_sensor_r[3]));
  DFFRHQX1 \temp_sensor_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[6]), .Q (temp_sensor_r[6]));
  DFFRHQX1 \water_level_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (water_level[1]), .Q (water_level_r[1]));
  DFFRHQX1 \water_level_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (water_level[3]), .Q (water_level_r[3]));
  DFFRHQX1 \water_level_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (water_level[0]), .Q (water_level_r[0]));
  DFFRHQX1 door_lock_cmd_r_reg(.RN (rst_n), .CK (clk), .D
       (door_lock_cmd), .Q (door_lock_cmd_r));
  DFFRHQX1 \volume_cmd_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (volume_cmd[2]), .Q (volume_cmd_r[2]));
  DFFRHQX1 door_sensor_r_reg(.RN (rst_n), .CK (clk), .D (door_sensor),
       .Q (door_sensor_r));
  DFFRHQX1 entry_sensor_r_reg(.RN (rst_n), .CK (clk), .D
       (entry_sensor), .Q (entry_sensor_r));
  DFFRHQX1 exit_sensor_r_reg(.RN (rst_n), .CK (clk), .D (exit_sensor),
       .Q (exit_sensor_r));
  DFFRHQX1 \humidity_sensor_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[0]), .Q (humidity_sensor_r[0]));
  DFFRHQX1 \humidity_sensor_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[1]), .Q (humidity_sensor_r[1]));
  DFFRHQX1 \humidity_sensor_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[2]), .Q (humidity_sensor_r[2]));
  DFFRHQX1 \humidity_sensor_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[3]), .Q (humidity_sensor_r[3]));
  DFFRHQX1 \humidity_sensor_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[4]), .Q (humidity_sensor_r[4]));
  DFFRHQX1 \humidity_sensor_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[5]), .Q (humidity_sensor_r[5]));
  DFFRHQX1 \humidity_sensor_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[6]), .Q (humidity_sensor_r[6]));
  DFFRHQX1 \volume_cmd_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (volume_cmd[3]), .Q (volume_cmd_r[3]));
  DFFRHQX1 music_on_cmd_r_reg(.RN (rst_n), .CK (clk), .D
       (music_on_cmd), .Q (music_on_cmd_r));
  DFFRHQX1 \pin_input_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (pin_input[0]), .Q (pin_input_r[0]));
  DFFRHQX1 \pin_input_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (pin_input[2]), .Q (pin_input_r[2]));
  DFFRHQX1 \pin_input_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (pin_input[3]), .Q (pin_input_r[3]));
  DFFRHQX1 tv_on_cmd_r_reg(.RN (rst_n), .CK (clk), .D (tv_on_cmd), .Q
       (tv_on_cmd_r));
  DFFRHQX1 \volume_cmd_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (volume_cmd[1]), .Q (volume_cmd_r[1]));
  DFFRHQX1 \light_sensor_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (light_sensor[3]), .Q (light_sensor_r[3]));
  DFFRHQX1 \light_sensor_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (light_sensor[1]), .Q (light_sensor_r[1]));
  DFFRHQX1 \light_sensor_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (light_sensor[2]), .Q (light_sensor_r[2]));
  DFFRHQX1 \light_sensor_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (light_sensor[4]), .Q (light_sensor_r[4]));
  DFFRHQX1 \light_sensor_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (light_sensor[5]), .Q (light_sensor_r[5]));
  DFFRHQX1 \light_sensor_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (light_sensor[6]), .Q (light_sensor_r[6]));
  DFFRHQX1 \light_sensor_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (light_sensor[0]), .Q (light_sensor_r[0]));
endmodule

