
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Oct 27 2025 19:01:30 IST (Oct 27 2025 13:31:30 UTC)

// Verification Directory fv/HA 

module appliances_controller(clk, rst_n, ac_cmd, fan_cmd, light_cmd,
     ac_on, fan_on, lights_on, DFT_sdi, DFT_sen);
  input clk, rst_n, ac_cmd, fan_cmd, light_cmd, DFT_sdi, DFT_sen;
  output ac_on, fan_on, lights_on;
  wire clk, rst_n, ac_cmd, fan_cmd, light_cmd, DFT_sdi, DFT_sen;
  wire ac_on, fan_on, lights_on;
  SDFFRHQX1 ac_on_reg(.RN (rst_n), .CK (clk), .D (ac_cmd), .SI
       (DFT_sdi), .SE (DFT_sen), .Q (ac_on));
  SDFFRHQX1 fan_on_reg(.RN (rst_n), .CK (clk), .D (fan_cmd), .SI
       (ac_on), .SE (DFT_sen), .Q (fan_on));
  SDFFRHQX1 lights_on_reg(.RN (rst_n), .CK (clk), .D (light_cmd), .SI
       (fan_on), .SE (DFT_sen), .Q (lights_on));
endmodule

module burglar_alarm(clk, rst_n, motion_sensor, door_sensor,
     window_sensor, alarm_arm, alarm_out, DFT_sdi, DFT_sen, DFT_sdo);
  input clk, rst_n, motion_sensor, door_sensor, window_sensor,
       alarm_arm, DFT_sdi, DFT_sen;
  output alarm_out, DFT_sdo;
  wire clk, rst_n, motion_sensor, door_sensor, window_sensor,
       alarm_arm, DFT_sdi, DFT_sen;
  wire alarm_out, DFT_sdo;
  wire [8:0] delay_counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40;
  SDFFRHQX1 \delay_counter_reg[5] (.RN (rst_n), .CK (clk), .D (n_39),
       .SI (delay_counter[4]), .SE (DFT_sen), .Q (delay_counter[5]));
  SDFFRHQX1 \delay_counter_reg[6] (.RN (rst_n), .CK (clk), .D (n_40),
       .SI (delay_counter[5]), .SE (DFT_sen), .Q (delay_counter[6]));
  SDFFRHQX1 \delay_counter_reg[8] (.RN (rst_n), .CK (clk), .D (n_37),
       .SI (delay_counter[7]), .SE (DFT_sen), .Q (DFT_sdo));
  SDFFRHQX1 \delay_counter_reg[7] (.RN (rst_n), .CK (clk), .D (n_38),
       .SI (delay_counter[6]), .SE (DFT_sen), .Q (delay_counter[7]));
  OAI31X1 g634(.A0 (delay_counter[6]), .A1 (n_13), .A2 (n_25), .B0
       (n_35), .Y (n_40));
  SDFFRHQX1 \delay_counter_reg[4] (.RN (rst_n), .CK (clk), .D (n_32),
       .SI (delay_counter[3]), .SE (DFT_sen), .Q (delay_counter[4]));
  OAI31X1 g636(.A0 (delay_counter[5]), .A1 (n_1), .A2 (n_24), .B0
       (n_36), .Y (n_39));
  OAI21X1 g637(.A0 (n_13), .A1 (n_29), .B0 (n_34), .Y (n_38));
  OAI21X1 g638(.A0 (n_9), .A1 (n_24), .B0 (n_33), .Y (n_37));
  NAND2XL g639(.A (delay_counter[5]), .B (n_31), .Y (n_36));
  NAND2XL g640(.A (delay_counter[6]), .B (n_30), .Y (n_35));
  NAND2XL g641(.A (delay_counter[7]), .B (n_30), .Y (n_34));
  OAI2BB1X1 g642(.A0N (n_13), .A1N (n_28), .B0 (DFT_sdo), .Y (n_33));
  OAI22X1 g643(.A0 (n_1), .A1 (n_28), .B0 (delay_counter[4]), .B1
       (n_24), .Y (n_32));
  OAI21XL g644(.A0 (n_13), .A1 (delay_counter[4]), .B0 (n_28), .Y
       (n_31));
  SDFFRHQX1 \delay_counter_reg[3] (.RN (rst_n), .CK (clk), .D (n_27),
       .SI (delay_counter[2]), .SE (DFT_sen), .Q (delay_counter[3]));
  AOI32X1 g646(.A0 (delay_counter[6]), .A1 (n_2), .A2 (n_26), .B0
       (delay_counter[7]), .B1 (n_0), .Y (n_29));
  OAI21X1 g647(.A0 (n_13), .A1 (n_26), .B0 (n_15), .Y (n_30));
  AOI21X1 g648(.A0 (n_21), .A1 (n_12), .B0 (n_16), .Y (n_28));
  OAI22XL g649(.A0 (n_13), .A1 (n_23), .B0 (n_15), .B1 (n_3), .Y
       (n_27));
  INVXL g650(.A (n_26), .Y (n_25));
  NOR2XL g651(.A (n_6), .B (n_21), .Y (n_26));
  OR2X1 g652(.A (n_21), .B (n_13), .Y (n_24));
  SDFFRHQX1 \delay_counter_reg[2] (.RN (rst_n), .CK (clk), .D (n_22),
       .SI (delay_counter[1]), .SE (DFT_sen), .Q (delay_counter[2]));
  MXI2XL g654(.A (n_3), .B (delay_counter[3]), .S0 (n_14), .Y (n_23));
  OAI22XL g655(.A0 (n_13), .A1 (n_17), .B0 (n_15), .B1 (n_4), .Y
       (n_22));
  SDFFRHQX1 alarm_out_reg(.RN (rst_n), .CK (clk), .D (n_20), .SI
       (DFT_sdi), .SE (DFT_sen), .Q (alarm_out));
  SDFFRHQX1 \delay_counter_reg[1] (.RN (rst_n), .CK (clk), .D (n_19),
       .SI (delay_counter[0]), .SE (DFT_sen), .Q (delay_counter[1]));
  OR2X1 g658(.A (n_3), .B (n_14), .Y (n_21));
  SDFFRHQX1 \delay_counter_reg[0] (.RN (rst_n), .CK (clk), .D (n_18),
       .SI (alarm_out), .SE (DFT_sen), .Q (delay_counter[0]));
  OAI2BB1X1 g660(.A0N (alarm_out), .A1N (n_12), .B0 (n_15), .Y (n_20));
  AO22X1 g661(.A0 (n_7), .A1 (n_12), .B0 (delay_counter[1]), .B1
       (n_16), .Y (n_19));
  MXI2XL g662(.A (n_13), .B (n_15), .S0 (delay_counter[0]), .Y (n_18));
  MXI2XL g663(.A (n_4), .B (delay_counter[2]), .S0 (n_5), .Y (n_17));
  CLKINVX1 g664(.A (n_16), .Y (n_15));
  NOR2XL g665(.A (n_11), .B (n_10), .Y (n_16));
  INVX1 g666(.A (n_13), .Y (n_12));
  OR2X1 g667(.A (n_4), .B (n_5), .Y (n_14));
  NAND2BX1 g668(.AN (n_11), .B (n_10), .Y (n_13));
  OAI31X1 g669(.A0 (window_sensor), .A1 (motion_sensor), .A2
       (door_sensor), .B0 (alarm_arm), .Y (n_11));
  OAI211X1 g670(.A0 (delay_counter[2]), .A1 (delay_counter[3]), .B0
       (DFT_sdo), .C0 (n_8), .Y (n_10));
  INVXL g671(.A (n_8), .Y (n_9));
  NOR3X1 g672(.A (n_0), .B (n_2), .C (n_6), .Y (n_8));
  XOR2XL g673(.A (delay_counter[0]), .B (delay_counter[1]), .Y (n_7));
  NAND2XL g674(.A (delay_counter[4]), .B (delay_counter[5]), .Y (n_6));
  NAND2XL g675(.A (delay_counter[0]), .B (delay_counter[1]), .Y (n_5));
  INVX1 g676(.A (delay_counter[2]), .Y (n_4));
  INVX1 g677(.A (delay_counter[3]), .Y (n_3));
  INVX1 g678(.A (delay_counter[7]), .Y (n_2));
  INVX1 g679(.A (delay_counter[4]), .Y (n_1));
  INVX1 g680(.A (delay_counter[6]), .Y (n_0));
endmodule

module door_lock_controller(clk, rst_n, lock_cmd, unlock_cmd,
     pin_input, door_locked, lock_status, DFT_sdi, DFT_sen, DFT_sdo);
  input clk, rst_n, lock_cmd, unlock_cmd, DFT_sdi, DFT_sen;
  input [3:0] pin_input;
  output door_locked, DFT_sdo;
  output [1:0] lock_status;
  wire clk, rst_n, lock_cmd, unlock_cmd, DFT_sdi, DFT_sen;
  wire [3:0] pin_input;
  wire door_locked, DFT_sdo;
  wire [1:0] lock_status;
  wire [2:0] attempt_counter;
  wire [1:0] state;
  wire [7:0] timeout_counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  SDFFRHQX1 door_locked_reg(.RN (rst_n), .CK (clk), .D (n_54), .SI
       (attempt_counter[2]), .SE (DFT_sen), .Q (door_locked));
  SDFFRHQX1 \lock_status_reg[1] (.RN (rst_n), .CK (clk), .D (state[1]),
       .SI (lock_status[0]), .SE (DFT_sen), .Q (lock_status[1]));
  SDFFRHQX1 \lock_status_reg[0] (.RN (rst_n), .CK (clk), .D (state[0]),
       .SI (door_locked), .SE (DFT_sen), .Q (lock_status[0]));
  OR2XL g754(.A (state[0]), .B (state[1]), .Y (n_54));
  SDFFRHQX1 \timeout_counter_reg[7] (.RN (rst_n), .CK (clk), .D (n_53),
       .SI (timeout_counter[6]), .SE (DFT_sen), .Q (DFT_sdo));
  SDFFRHQX1 \timeout_counter_reg[6] (.RN (rst_n), .CK (clk), .D (n_51),
       .SI (timeout_counter[5]), .SE (DFT_sen), .Q
       (timeout_counter[6]));
  NOR2XL g2214(.A (n_27), .B (n_52), .Y (n_53));
  AOI21XL g2215(.A0 (timeout_counter[6]), .A1 (n_48), .B0 (DFT_sdo), .Y
       (n_52));
  NOR2XL g2216(.A (n_27), .B (n_50), .Y (n_51));
  SDFFRHQX1 \timeout_counter_reg[5] (.RN (rst_n), .CK (clk), .D (n_49),
       .SI (timeout_counter[4]), .SE (DFT_sen), .Q
       (timeout_counter[5]));
  MXI2XL g2218(.A (n_48), .B (n_45), .S0 (timeout_counter[6]), .Y
       (n_50));
  NOR2XL g2219(.A (n_47), .B (n_27), .Y (n_49));
  CLKINVX1 g2220(.A (n_45), .Y (n_48));
  SDFFRHQX1 \timeout_counter_reg[4] (.RN (rst_n), .CK (clk), .D (n_44),
       .SI (timeout_counter[3]), .SE (DFT_sen), .Q
       (timeout_counter[4]));
  AOI21XL g2222(.A0 (timeout_counter[5]), .A1 (n_41), .B0 (n_46), .Y
       (n_47));
  NOR2XL g2223(.A (timeout_counter[5]), .B (n_41), .Y (n_46));
  NOR2XL g2224(.A (n_43), .B (n_27), .Y (n_44));
  NAND2BX1 g2225(.AN (n_41), .B (timeout_counter[5]), .Y (n_45));
  SDFFRHQX1 \timeout_counter_reg[3] (.RN (rst_n), .CK (clk), .D (n_40),
       .SI (timeout_counter[2]), .SE (DFT_sen), .Q
       (timeout_counter[3]));
  AOI21XL g2227(.A0 (timeout_counter[4]), .A1 (n_36), .B0 (n_42), .Y
       (n_43));
  NOR2XL g2228(.A (timeout_counter[4]), .B (n_36), .Y (n_42));
  NOR2XL g2229(.A (n_39), .B (n_27), .Y (n_40));
  NAND2BX1 g2230(.AN (n_36), .B (timeout_counter[4]), .Y (n_41));
  SDFFRHQX1 \attempt_counter_reg[0] (.RN (rst_n), .CK (clk), .D (n_38),
       .SI (DFT_sdi), .SE (DFT_sen), .Q (attempt_counter[0]));
  SDFFRHQX1 \attempt_counter_reg[1] (.RN (rst_n), .CK (clk), .D (n_37),
       .SI (attempt_counter[0]), .SE (DFT_sen), .Q
       (attempt_counter[1]));
  SDFFRHQX1 \timeout_counter_reg[1] (.RN (rst_n), .CK (clk), .D (n_32),
       .SI (timeout_counter[0]), .SE (DFT_sen), .Q
       (timeout_counter[1]));
  SDFFRHQX1 \timeout_counter_reg[2] (.RN (rst_n), .CK (clk), .D (n_30),
       .SI (timeout_counter[1]), .SE (DFT_sen), .Q
       (timeout_counter[2]));
  SDFFRHQX1 \state_reg[1] (.RN (rst_n), .CK (clk), .D (n_31), .SI
       (state[0]), .SE (DFT_sen), .Q (state[1]));
  SDFFRHQX1 \state_reg[0] (.RN (rst_n), .CK (clk), .D (n_33), .SI
       (lock_status[1]), .SE (DFT_sen), .Q (state[0]));
  AOI21X1 g2237(.A0 (timeout_counter[3]), .A1 (n_21), .B0 (n_34), .Y
       (n_39));
  AO21X1 g2238(.A0 (attempt_counter[0]), .A1 (n_28), .B0 (n_26), .Y
       (n_38));
  OAI22X1 g2239(.A0 (n_19), .A1 (n_15), .B0 (n_5), .B1 (n_29), .Y
       (n_37));
  SDFFRHQX1 \timeout_counter_reg[0] (.RN (rst_n), .CK (clk), .D (n_35),
       .SI (state[1]), .SE (DFT_sen), .Q (timeout_counter[0]));
  NOR2XL g2241(.A (timeout_counter[0]), .B (n_27), .Y (n_35));
  NOR2XL g2242(.A (timeout_counter[3]), .B (n_21), .Y (n_34));
  NAND2BX1 g2243(.AN (n_21), .B (timeout_counter[3]), .Y (n_36));
  OAI221X1 g2244(.A0 (n_2), .A1 (n_22), .B0 (state[0]), .B1 (n_8), .C0
       (n_25), .Y (n_33));
  NOR2XL g2245(.A (n_10), .B (n_27), .Y (n_32));
  NAND2XL g2246(.A (n_19), .B (n_27), .Y (n_31));
  NOR2XL g2247(.A (n_24), .B (n_27), .Y (n_30));
  SDFFRHQX1 \attempt_counter_reg[2] (.RN (rst_n), .CK (clk), .D (n_23),
       .SI (attempt_counter[1]), .SE (DFT_sen), .Q
       (attempt_counter[2]));
  INVXL g2249(.A (n_28), .Y (n_29));
  OAI21X1 g2250(.A0 (n_4), .A1 (n_19), .B0 (n_11), .Y (n_28));
  OAI21X1 g2251(.A0 (n_18), .A1 (n_22), .B0 (state[1]), .Y (n_27));
  AOI211X1 g2252(.A0 (attempt_counter[1]), .A1 (attempt_counter[2]),
       .B0 (attempt_counter[0]), .C0 (n_19), .Y (n_26));
  OAI21X1 g2253(.A0 (n_9), .A1 (n_16), .B0 (state[0]), .Y (n_25));
  AOI21XL g2254(.A0 (timeout_counter[2]), .A1 (n_6), .B0 (n_20), .Y
       (n_24));
  OAI21X1 g2255(.A0 (n_4), .A1 (n_11), .B0 (n_17), .Y (n_23));
  NOR2XL g2256(.A (timeout_counter[2]), .B (n_6), .Y (n_20));
  AOI31X1 g2257(.A0 (timeout_counter[5]), .A1 (timeout_counter[6]), .A2
       (n_14), .B0 (DFT_sdo), .Y (n_22));
  NAND2BX1 g2258(.AN (n_6), .B (timeout_counter[2]), .Y (n_21));
  AOI31X1 g2259(.A0 (DFT_sdo), .A1 (timeout_counter[6]), .A2 (n_0), .B0
       (n_1), .Y (n_18));
  NAND3BX1 g2260(.AN (n_9), .B (state[0]), .C (n_16), .Y (n_17));
  NAND3BX1 g2261(.AN (n_9), .B (n_12), .C (state[0]), .Y (n_19));
  NOR2BX1 g2262(.AN (n_12), .B (n_13), .Y (n_16));
  AOI32X1 g2263(.A0 (attempt_counter[0]), .A1 (n_5), .A2 (n_4), .B0
       (attempt_counter[1]), .B1 (n_3), .Y (n_15));
  NAND2BX1 g2265(.AN (timeout_counter[2]), .B (n_7), .Y (n_14));
  AOI21X1 g2266(.A0 (attempt_counter[0]), .A1 (attempt_counter[1]), .B0
       (attempt_counter[2]), .Y (n_13));
  XNOR2XL g2267(.A (timeout_counter[0]), .B (timeout_counter[1]), .Y
       (n_10));
  NAND4BXL g2268(.AN (pin_input[3]), .B (pin_input[0]), .C
       (pin_input[1]), .D (pin_input[2]), .Y (n_12));
  AOI2BB1X1 g2269(.A0N (unlock_cmd), .A1N (n_1), .B0 (state[1]), .Y
       (n_11));
  NAND2XL g2270(.A (lock_cmd), .B (n_2), .Y (n_8));
  NAND2XL g2271(.A (unlock_cmd), .B (n_2), .Y (n_9));
  NOR2XL g2272(.A (timeout_counter[3]), .B (timeout_counter[4]), .Y
       (n_7));
  NAND2XL g2273(.A (timeout_counter[0]), .B (timeout_counter[1]), .Y
       (n_6));
  CLKINVX1 g2277(.A (state[1]), .Y (n_2));
  INVX1 g2278(.A (attempt_counter[1]), .Y (n_5));
  CLKINVX1 g2279(.A (attempt_counter[2]), .Y (n_4));
  INVXL g2280(.A (attempt_counter[0]), .Y (n_3));
  INVX1 g2286(.A (state[0]), .Y (n_1));
  NAND2BX1 g2(.AN (timeout_counter[5]), .B (n_7), .Y (n_0));
endmodule

module entertainment_system(clk, rst_n, tv_on_cmd, music_on_cmd,
     volume_cmd, tv_on, music_on, volume_level, DFT_sdi, DFT_sen);
  input clk, rst_n, tv_on_cmd, music_on_cmd, DFT_sdi, DFT_sen;
  input [3:0] volume_cmd;
  output tv_on, music_on;
  output [3:0] volume_level;
  wire clk, rst_n, tv_on_cmd, music_on_cmd, DFT_sdi, DFT_sen;
  wire [3:0] volume_cmd;
  wire tv_on, music_on;
  wire [3:0] volume_level;
  wire n_0, n_1, n_2, n_3, n_4;
  SDFFRHQX1 tv_on_reg(.RN (rst_n), .CK (clk), .D (tv_on_cmd), .SI
       (music_on), .SE (DFT_sen), .Q (tv_on));
  SDFFRHQX1 music_on_reg(.RN (rst_n), .CK (clk), .D (music_on_cmd), .SI
       (DFT_sdi), .SE (DFT_sen), .Q (music_on));
  SDFFSHQX1 \volume_level_reg[0] (.SN (rst_n), .CK (clk), .D (n_3), .SI
       (tv_on), .SE (DFT_sen), .Q (volume_level[0]));
  SDFFSHQX1 \volume_level_reg[2] (.SN (rst_n), .CK (clk), .D (n_2), .SI
       (volume_level[1]), .SE (DFT_sen), .Q (volume_level[2]));
  SDFFRHQX1 \volume_level_reg[1] (.RN (rst_n), .CK (clk), .D (n_4), .SI
       (volume_level[0]), .SE (DFT_sen), .Q (volume_level[1]));
  SDFFRHQX1 \volume_level_reg[3] (.RN (rst_n), .CK (clk), .D (n_1), .SI
       (volume_level[2]), .SE (DFT_sen), .Q (volume_level[3]));
  MX2X1 g44(.A (volume_cmd[1]), .B (volume_level[1]), .S0 (n_0), .Y
       (n_4));
  MX2X1 g45(.A (volume_cmd[0]), .B (volume_level[0]), .S0 (n_0), .Y
       (n_3));
  MX2X1 g46(.A (volume_cmd[2]), .B (volume_level[2]), .S0 (n_0), .Y
       (n_2));
  MX2X1 g47(.A (volume_cmd[3]), .B (volume_level[3]), .S0 (n_0), .Y
       (n_1));
  NOR4X1 g48(.A (volume_cmd[3]), .B (volume_cmd[2]), .C
       (volume_cmd[1]), .D (volume_cmd[0]), .Y (n_0));
endmodule

module humidity_controller(clk, rst_n, humidity_sensor, humidifier_on,
     dehumidifier_on, DFT_sdi, DFT_sen);
  input clk, rst_n, DFT_sdi, DFT_sen;
  input [7:0] humidity_sensor;
  output humidifier_on, dehumidifier_on;
  wire clk, rst_n, DFT_sdi, DFT_sen;
  wire [7:0] humidity_sensor;
  wire humidifier_on, dehumidifier_on;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  SDFFRHQX1 dehumidifier_on_reg(.RN (rst_n), .CK (clk), .D (n_5), .SI
       (DFT_sdi), .SE (DFT_sen), .Q (dehumidifier_on));
  SDFFRHQX1 humidifier_on_reg(.RN (rst_n), .CK (clk), .D (n_4), .SI
       (dehumidifier_on), .SE (DFT_sen), .Q (humidifier_on));
  AOI21X1 g202(.A0 (n_0), .A1 (n_1), .B0 (n_3), .Y (n_5));
  AOI21X1 g203(.A0 (humidity_sensor[5]), .A1 (humidity_sensor[3]), .B0
       (n_2), .Y (n_4));
  INVXL g204(.A (n_2), .Y (n_3));
  OAI2BB1X1 g205(.A0N (humidity_sensor[4]), .A1N (humidity_sensor[5]),
       .B0 (n_0), .Y (n_2));
  OAI211X1 g206(.A0 (humidity_sensor[1]), .A1 (humidity_sensor[0]), .B0
       (humidity_sensor[2]), .C0 (humidity_sensor[3]), .Y (n_1));
  NOR2XL g207(.A (humidity_sensor[7]), .B (humidity_sensor[6]), .Y
       (n_0));
endmodule

module luminosity_controller(clk, rst_n, light_sensor, led_brightness,
     DFT_sdi, DFT_sen);
  input clk, rst_n, DFT_sdi, DFT_sen;
  input [7:0] light_sensor;
  output [7:0] led_brightness;
  wire clk, rst_n, DFT_sdi, DFT_sen;
  wire [7:0] light_sensor;
  wire [7:0] led_brightness;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  SDFFRHQX1 \led_brightness_reg[4] (.RN (rst_n), .CK (clk), .D (n_5),
       .SI (led_brightness[3]), .SE (DFT_sen), .Q (led_brightness[4]));
  SDFFRHQX1 \led_brightness_reg[6] (.RN (rst_n), .CK (clk), .D (n_6),
       .SI (led_brightness[5]), .SE (DFT_sen), .Q (led_brightness[6]));
  SDFFRHQX1 \led_brightness_reg[7] (.RN (rst_n), .CK (clk), .D (n_7),
       .SI (led_brightness[6]), .SE (DFT_sen), .Q (led_brightness[7]));
  SDFFRHQX1 \led_brightness_reg[0] (.RN (rst_n), .CK (clk), .D (n_4),
       .SI (DFT_sdi), .SE (DFT_sen), .Q (led_brightness[0]));
  SDFFRHQX1 \led_brightness_reg[2] (.RN (rst_n), .CK (clk), .D (n_0),
       .SI (led_brightness[1]), .SE (DFT_sen), .Q (led_brightness[2]));
  SDFFRHQX1 \led_brightness_reg[5] (.RN (rst_n), .CK (clk), .D (n_1),
       .SI (led_brightness[4]), .SE (DFT_sen), .Q (led_brightness[5]));
  SDFFRHQX1 \led_brightness_reg[3] (.RN (rst_n), .CK (clk), .D (n_2),
       .SI (led_brightness[2]), .SE (DFT_sen), .Q (led_brightness[3]));
  SDFFRHQX1 \led_brightness_reg[1] (.RN (rst_n), .CK (clk), .D (n_3),
       .SI (led_brightness[0]), .SE (DFT_sen), .Q (led_brightness[1]));
  INVX1 g95(.A (light_sensor[7]), .Y (n_7));
  INVX1 g96(.A (light_sensor[6]), .Y (n_6));
  INVX1 g97(.A (light_sensor[4]), .Y (n_5));
  INVX1 g98(.A (light_sensor[0]), .Y (n_4));
  INVX1 g99(.A (light_sensor[1]), .Y (n_3));
  INVX1 g100(.A (light_sensor[3]), .Y (n_2));
  INVX1 g101(.A (light_sensor[5]), .Y (n_1));
  INVX1 g102(.A (light_sensor[2]), .Y (n_0));
endmodule

module temperature_controller(clk, rst_n, temp_sensor, temp_setpoint,
     heater_on, cooler_on, DFT_sdi, DFT_sen);
  input clk, rst_n, DFT_sdi, DFT_sen;
  input [7:0] temp_sensor, temp_setpoint;
  output heater_on, cooler_on;
  wire clk, rst_n, DFT_sdi, DFT_sen;
  wire [7:0] temp_sensor, temp_setpoint;
  wire heater_on, cooler_on;
  wire n_2, n_4, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_91;
  SDFFRHQX1 cooler_on_reg(.RN (rst_n), .CK (clk), .D (n_72), .SI
       (DFT_sdi), .SE (DFT_sen), .Q (cooler_on));
  SDFFRHQX1 heater_on_reg(.RN (rst_n), .CK (clk), .D (n_71), .SI
       (cooler_on), .SE (DFT_sen), .Q (heater_on));
  MXI2XL g1650(.A (n_65), .B (n_40), .S0 (n_70), .Y (n_72));
  MXI2XL g1651(.A (n_64), .B (n_43), .S0 (n_70), .Y (n_71));
  NOR2XL g1652(.A (n_65), .B (n_69), .Y (n_70));
  AOI211X1 g1653(.A0 (n_59), .A1 (n_60), .B0 (n_67), .C0 (n_68), .Y
       (n_69));
  OAI33X1 g1654(.A0 (temp_sensor[4]), .A1 (n_39), .A2 (n_66), .B0
       (temp_sensor[5]), .B1 (n_48), .B2 (n_62), .Y (n_68));
  AOI211X1 g1655(.A0 (temp_sensor[4]), .A1 (n_39), .B0 (n_45), .C0
       (n_66), .Y (n_67));
  OAI2BB1X1 g1656(.A0N (temp_sensor[5]), .A1N (n_48), .B0 (n_61), .Y
       (n_66));
  CLKINVX1 g1657(.A (n_64), .Y (n_65));
  AOI21X1 g1658(.A0 (n_6), .A1 (n_55), .B0 (n_63), .Y (n_64));
  AOI211X1 g1659(.A0 (temp_sensor[6]), .A1 (n_54), .B0 (n_58), .C0
       (n_56), .Y (n_63));
  INVXL g1660(.A (n_61), .Y (n_62));
  AOI22X1 g1661(.A0 (temp_sensor[6]), .A1 (n_91), .B0 (temp_sensor[7]),
       .B1 (n_57), .Y (n_61));
  OAI31X1 g1662(.A0 (temp_sensor[7]), .A1 (temp_sensor[6]), .A2 (n_91),
       .B0 (n_57), .Y (n_60));
  OAI21X1 g1663(.A0 (temp_sensor[6]), .A1 (n_91), .B0 (temp_sensor[7]),
       .Y (n_59));
  NOR2XL g1664(.A (n_6), .B (n_55), .Y (n_58));
  AOI21X1 g1665(.A0 (temp_setpoint[6]), .A1 (n_47), .B0
       (temp_setpoint[7]), .Y (n_57));
  AOI211X1 g1666(.A0 (temp_setpoint[6]), .A1 (n_38), .B0 (n_50), .C0
       (n_52), .Y (n_56));
  CLKXOR2X1 g1667(.A (temp_setpoint[7]), .B (n_50), .Y (n_55));
  NAND2XL g1668(.A (n_49), .B (n_51), .Y (n_54));
  AND3X1 g1669(.A (n_2), .B (n_49), .C (n_51), .Y (n_52));
  OAI222XL g1671(.A0 (n_36), .A1 (n_46), .B0 (temp_sensor[5]), .B1
       (n_44), .C0 (n_41), .C1 (temp_sensor[4]), .Y (n_51));
  NOR2XL g1672(.A (temp_setpoint[6]), .B (n_38), .Y (n_50));
  NAND2XL g1673(.A (temp_sensor[5]), .B (n_44), .Y (n_49));
  AO21X1 g1674(.A0 (n_4), .A1 (n_32), .B0 (n_47), .Y (n_48));
  NOR2XL g1675(.A (n_4), .B (n_32), .Y (n_47));
  OAI22X1 g1676(.A0 (n_34), .A1 (n_42), .B0 (n_7), .B1 (n_27), .Y
       (n_46));
  AOI21X1 g1677(.A0 (n_30), .A1 (n_31), .B0 (n_37), .Y (n_45));
  OA21X1 g1678(.A0 (n_4), .A1 (n_34), .B0 (n_38), .Y (n_44));
  NAND2XL g1679(.A (n_33), .B (heater_on), .Y (n_43));
  NAND2XL g1680(.A (temp_sensor[4]), .B (n_35), .Y (n_42));
  NOR2BX1 g1681(.AN (n_35), .B (n_34), .Y (n_41));
  NAND2XL g1682(.A (n_33), .B (cooler_on), .Y (n_40));
  AOI221X1 g1683(.A0 (temp_sensor[2]), .A1 (n_19), .B0
       (temp_sensor[3]), .B1 (n_25), .C0 (n_26), .Y (n_37));
  AOI221X1 g1684(.A0 (n_19), .A1 (n_24), .B0 (n_7), .B1 (n_27), .C0
       (n_29), .Y (n_36));
  OAI21X1 g1685(.A0 (temp_setpoint[4]), .A1 (n_20), .B0 (n_32), .Y
       (n_39));
  NAND2XL g1686(.A (n_4), .B (n_34), .Y (n_38));
  NAND2XL g1687(.A (temp_setpoint[4]), .B (n_21), .Y (n_35));
  NOR2XL g1688(.A (temp_setpoint[4]), .B (n_21), .Y (n_34));
  OAI31X1 g1689(.A0 (temp_sensor[2]), .A1 (temp_sensor[3]), .A2 (n_19),
       .B0 (n_25), .Y (n_31));
  NAND2XL g1691(.A (temp_setpoint[4]), .B (n_20), .Y (n_32));
  OAI21X1 g1692(.A0 (temp_sensor[2]), .A1 (n_19), .B0 (temp_sensor[3]),
       .Y (n_30));
  AOI21X1 g1693(.A0 (n_9), .A1 (n_22), .B0 (temp_sensor[2]), .Y (n_29));
  OAI2BB1X1 g1695(.A0N (n_11), .A1N (n_9), .B0 (n_12), .Y (n_26));
  OAI21X1 g1696(.A0 (n_8), .A1 (n_10), .B0 (n_21), .Y (n_27));
  NAND3X1 g1697(.A (temp_sensor[2]), .B (n_9), .C (n_22), .Y (n_24));
  AOI211X1 g1698(.A0 (n_12), .A1 (n_9), .B0 (n_11), .C0 (n_14), .Y
       (n_23));
  AO21X1 g1699(.A0 (n_8), .A1 (n_13), .B0 (n_20), .Y (n_25));
  NAND2XL g1701(.A (n_12), .B (n_14), .Y (n_22));
  NAND2XL g1702(.A (n_8), .B (n_10), .Y (n_21));
  NOR2XL g1703(.A (n_8), .B (n_13), .Y (n_20));
  NAND2BX1 g1704(.AN (n_10), .B (n_13), .Y (n_19));
  NOR2BX1 g1710(.AN (temp_setpoint[0]), .B (temp_sensor[0]), .Y (n_14));
  NAND2XL g1711(.A (temp_setpoint[2]), .B (temp_setpoint[1]), .Y
       (n_13));
  NAND2XL g1712(.A (temp_sensor[1]), .B (temp_setpoint[1]), .Y (n_12));
  NOR2BX1 g1713(.AN (temp_sensor[0]), .B (temp_setpoint[0]), .Y (n_11));
  NOR2XL g1714(.A (temp_setpoint[2]), .B (temp_setpoint[1]), .Y (n_10));
  OR2X1 g1715(.A (temp_sensor[1]), .B (temp_setpoint[1]), .Y (n_9));
  CLKINVX1 g1716(.A (temp_setpoint[3]), .Y (n_8));
  CLKINVX1 g1718(.A (temp_sensor[3]), .Y (n_7));
  INVX1 g1719(.A (temp_sensor[7]), .Y (n_6));
  CLKINVX1 g1721(.A (temp_setpoint[5]), .Y (n_4));
  INVX1 g1724(.A (temp_sensor[6]), .Y (n_2));
  INVXL g1726(.A (n_23), .Y (n_33));
  XNOR2X1 g2(.A (temp_setpoint[6]), .B (n_47), .Y (n_91));
endmodule

module visitor_counter(clk, rst_n, entry_sensor, exit_sensor, count,
     DFT_sdi, DFT_sen, DFT_sdo);
  input clk, rst_n, entry_sensor, exit_sensor, DFT_sdi, DFT_sen;
  output [7:0] count;
  output DFT_sdo;
  wire clk, rst_n, entry_sensor, exit_sensor, DFT_sdi, DFT_sen;
  wire [7:0] count;
  wire DFT_sdo;
  wire entry_prev, exit_prev, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_41, n_42, n_43, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_57;
  SDFFRHQX1 \count_reg[2] (.RN (rst_n), .CK (clk), .D (n_49), .SI
       (count[1]), .SE (DFT_sen), .Q (count[2]));
  SDFFRHQX1 \count_reg[4] (.RN (rst_n), .CK (clk), .D (n_52), .SI
       (count[3]), .SE (DFT_sen), .Q (count[4]));
  SDFFRHQX1 \count_reg[6] (.RN (rst_n), .CK (clk), .D (n_50), .SI
       (count[5]), .SE (DFT_sen), .Q (count[6]));
  SDFFRHQX1 \count_reg[3] (.RN (rst_n), .CK (clk), .D (n_45), .SI
       (count[2]), .SE (DFT_sen), .Q (count[3]));
  SDFFRHQX1 \count_reg[5] (.RN (rst_n), .CK (clk), .D (n_48), .SI
       (count[4]), .SE (DFT_sen), .Q (count[5]));
  INVX1 g797(.A (n_51), .Y (n_52));
  AOI222XL g798(.A0 (n_15), .A1 (n_31), .B0 (n_14), .B1 (n_24), .C0
       (n_35), .C1 (count[4]), .Y (n_51));
  SDFFRHQX1 \count_reg[7] (.RN (rst_n), .CK (clk), .D (n_57), .SI
       (count[6]), .SE (DFT_sen), .Q (count[7]));
  SDFFRHQX1 \count_reg[1] (.RN (rst_n), .CK (clk), .D (n_43), .SI
       (count[0]), .SE (DFT_sen), .Q (count[1]));
  INVX1 g801(.A (n_47), .Y (n_50));
  INVX1 g802(.A (n_46), .Y (n_49));
  OAI2BB1X1 g803(.A0N (count[5]), .A1N (n_36), .B0 (n_42), .Y (n_48));
  AOI222XL g804(.A0 (n_20), .A1 (n_31), .B0 (n_18), .B1 (n_24), .C0
       (n_37), .C1 (count[6]), .Y (n_47));
  AOI222XL g805(.A0 (n_10), .A1 (n_31), .B0 (n_9), .B1 (n_24), .C0
       (n_34), .C1 (count[2]), .Y (n_46));
  OAI2BB1X1 g806(.A0N (count[3]), .A1N (n_38), .B0 (n_39), .Y (n_45));
  SDFFRHQX1 \count_reg[0] (.RN (rst_n), .CK (clk), .D (n_33), .SI
       (DFT_sdi), .SE (DFT_sen), .Q (count[0]));
  OAI21X1 g809(.A0 (n_11), .A1 (n_30), .B0 (n_41), .Y (n_43));
  AOI32X1 g810(.A0 (n_5), .A1 (n_2), .A2 (n_24), .B0 (n_16), .B1
       (n_31), .Y (n_42));
  AOI22X1 g811(.A0 (count[1]), .A1 (n_27), .B0 (n_11), .B1 (n_24), .Y
       (n_41));
  AOI32X1 g813(.A0 (n_6), .A1 (n_1), .A2 (n_24), .B0 (n_13), .B1
       (n_31), .Y (n_39));
  OAI221XL g814(.A0 (n_10), .A1 (n_30), .B0 (n_1), .B1 (n_23), .C0
       (n_28), .Y (n_38));
  OAI211XL g815(.A0 (n_30), .A1 (n_16), .B0 (n_26), .C0 (n_28), .Y
       (n_37));
  OAI221XL g816(.A0 (n_15), .A1 (n_30), .B0 (n_2), .B1 (n_23), .C0
       (n_28), .Y (n_36));
  OAI211XL g817(.A0 (n_30), .A1 (n_13), .B0 (n_29), .C0 (n_28), .Y
       (n_35));
  OAI211XL g818(.A0 (n_30), .A1 (n_8), .B0 (n_25), .C0 (n_28), .Y
       (n_34));
  MXI2XL g819(.A (n_27), .B (n_28), .S0 (count[0]), .Y (n_33));
  NAND3XL g820(.A (n_20), .B (n_23), .C (n_28), .Y (n_32));
  CLKINVX1 g821(.A (n_31), .Y (n_30));
  NAND2XL g822(.A (n_12), .B (n_24), .Y (n_29));
  NOR2XL g823(.A (n_22), .B (n_24), .Y (n_31));
  INVX1 g824(.A (n_28), .Y (n_27));
  NAND2XL g825(.A (n_17), .B (n_24), .Y (n_26));
  NAND2XL g826(.A (n_7), .B (n_24), .Y (n_25));
  NAND2XL g827(.A (n_22), .B (n_23), .Y (n_28));
  CLKINVX1 g828(.A (n_24), .Y (n_23));
  AOI211X1 g829(.A0 (count[7]), .A1 (n_21), .B0 (entry_prev), .C0
       (n_4), .Y (n_24));
  OAI211X1 g830(.A0 (count[7]), .A1 (n_19), .B0 (exit_sensor), .C0
       (exit_prev), .Y (n_22));
  NOR2XL g831(.A (n_3), .B (n_17), .Y (n_21));
  CLKINVX1 g832(.A (n_19), .Y (n_20));
  NOR2XL g833(.A (count[6]), .B (n_17), .Y (n_18));
  NAND2XL g834(.A (n_3), .B (n_16), .Y (n_19));
  NAND2XL g835(.A (count[5]), .B (n_2), .Y (n_17));
  AND2X1 g836(.A (n_5), .B (n_15), .Y (n_16));
  NOR2BX1 g837(.AN (n_13), .B (count[4]), .Y (n_15));
  NOR2XL g838(.A (count[4]), .B (n_12), .Y (n_14));
  AND2X1 g840(.A (n_6), .B (n_10), .Y (n_13));
  NAND2XL g841(.A (count[3]), .B (n_1), .Y (n_12));
  NOR2BX1 g842(.AN (n_7), .B (n_8), .Y (n_11));
  NOR2BX1 g843(.AN (n_8), .B (count[2]), .Y (n_10));
  NOR2XL g844(.A (count[2]), .B (n_7), .Y (n_9));
  SDFFRXL exit_prev_reg(.RN (rst_n), .CK (clk), .D (exit_sensor), .SI
       (entry_prev), .SE (DFT_sen), .Q (DFT_sdo), .QN (exit_prev));
  SDFFRHQX1 entry_prev_reg(.RN (rst_n), .CK (clk), .D (entry_sensor),
       .SI (count[7]), .SE (DFT_sen), .Q (entry_prev));
  NOR2XL g848(.A (count[0]), .B (count[1]), .Y (n_8));
  NAND2XL g849(.A (count[0]), .B (count[1]), .Y (n_7));
  CLKINVX1 g855(.A (count[3]), .Y (n_6));
  CLKINVX1 g856(.A (count[5]), .Y (n_5));
  CLKINVX1 g859(.A (count[6]), .Y (n_3));
  INVX1 g860(.A (entry_sensor), .Y (n_4));
  NOR2BX1 g2(.AN (count[4]), .B (n_12), .Y (n_2));
  NOR2BX1 g866(.AN (count[2]), .B (n_7), .Y (n_1));
  AO22XL g867(.A0 (n_21), .A1 (n_24), .B0 (count[7]), .B1 (n_32), .Y
       (n_57));
endmodule

module water_level_controller(clk, rst_n, water_level, pump_on,
     valve_close, DFT_sdi, DFT_sen);
  input clk, rst_n, DFT_sdi, DFT_sen;
  input [3:0] water_level;
  output pump_on, valve_close;
  wire clk, rst_n, DFT_sdi, DFT_sen;
  wire [3:0] water_level;
  wire pump_on, valve_close;
  wire n_2, n_3, n_4, n_13;
  SDFFRHQX1 valve_close_reg(.RN (rst_n), .CK (clk), .D (n_4), .SI
       (pump_on), .SE (DFT_sen), .Q (valve_close));
  NOR2XL g77(.A (n_2), .B (n_3), .Y (n_4));
  AOI21X1 g79(.A0 (water_level[3]), .A1 (water_level[2]), .B0 (n_2), .Y
       (n_3));
  AOI211X1 g81(.A0 (water_level[1]), .A1 (water_level[0]), .B0
       (water_level[3]), .C0 (water_level[2]), .Y (n_2));
  SDFFRHQX1 pump_on_reg(.RN (rst_n), .CK (clk), .D (n_13), .SI
       (DFT_sdi), .SE (DFT_sen), .Q (pump_on));
  MX2X1 g2(.A (n_2), .B (pump_on), .S0 (n_3), .Y (n_13));
endmodule

module window_treatment(clk, rst_n, auto_mode, light_level,
     manual_open, manual_close, window_state, DFT_sdi, DFT_sen);
  input clk, rst_n, auto_mode, manual_open, manual_close, DFT_sdi,
       DFT_sen;
  input [7:0] light_level;
  output [1:0] window_state;
  wire clk, rst_n, auto_mode, manual_open, manual_close, DFT_sdi,
       DFT_sen;
  wire [7:0] light_level;
  wire [1:0] window_state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12;
  SDFFRHQX1 \window_state_reg[0] (.RN (rst_n), .CK (clk), .D (n_12),
       .SI (DFT_sdi), .SE (DFT_sen), .Q (window_state[0]));
  AO22X1 g361(.A0 (auto_mode), .A1 (n_11), .B0 (n_2), .B1
       (window_state[0]), .Y (n_12));
  SDFFRHQX1 \window_state_reg[1] (.RN (rst_n), .CK (clk), .D (n_10),
       .SI (window_state[0]), .SE (DFT_sen), .Q (window_state[1]));
  MXI2XL g363(.A (n_7), .B (n_9), .S0 (light_level[6]), .Y (n_11));
  OAI21X1 g364(.A0 (auto_mode), .A1 (n_3), .B0 (n_8), .Y (n_10));
  NOR2BXL g365(.AN (light_level[7]), .B (n_6), .Y (n_9));
  NAND3BX1 g366(.AN (light_level[6]), .B (auto_mode), .C (n_7), .Y
       (n_8));
  AOI31X1 g367(.A0 (light_level[5]), .A1 (light_level[4]), .A2 (n_4),
       .B0 (light_level[7]), .Y (n_7));
  AOI211X1 g368(.A0 (light_level[3]), .A1 (n_5), .B0 (light_level[5]),
       .C0 (light_level[4]), .Y (n_6));
  NAND2BX1 g369(.AN (light_level[0]), .B (n_1), .Y (n_5));
  NAND2BXL g370(.AN (light_level[3]), .B (n_1), .Y (n_4));
  AOI21X1 g371(.A0 (n_0), .A1 (window_state[1]), .B0 (manual_open), .Y
       (n_3));
  NOR3X1 g372(.A (manual_open), .B (manual_close), .C (auto_mode), .Y
       (n_2));
  NOR2XL g373(.A (light_level[2]), .B (light_level[1]), .Y (n_1));
  INVXL g374(.A (manual_close), .Y (n_0));
endmodule

module HA(clk, rst_n, temp_sensor, temp_setpoint, water_level,
     light_sensor, motion_sensor, door_sensor, window_sensor,
     alarm_arm, entry_sensor, exit_sensor, window_auto_mode,
     window_manual_open, window_manual_close, tv_on_cmd, music_on_cmd,
     volume_cmd, ac_cmd, fan_cmd, light_cmd, door_lock_cmd,
     door_unlock_cmd, pin_input, humidity_sensor, heater_on, cooler_on,
     water_pump_on, water_valve_close, led_brightness,
     burglar_alarm_out, visitor_count, window_state, tv_on, music_on,
     volume_level, ac_on, fan_on, lights_on, door_locked, lock_status,
     humidifier_on, dehumidifier_on, system_status, scan_en, test_mode,
     DFT_sdi_1, DFT_sdo_1, DFT_sdi_2, DFT_sdo_2);
  input clk, rst_n, motion_sensor, door_sensor, window_sensor,
       alarm_arm, entry_sensor, exit_sensor, window_auto_mode,
       window_manual_open, window_manual_close, tv_on_cmd,
       music_on_cmd, ac_cmd, fan_cmd, light_cmd, door_lock_cmd,
       door_unlock_cmd, scan_en, test_mode, DFT_sdi_1, DFT_sdi_2;
  input [7:0] temp_sensor, temp_setpoint, light_sensor, humidity_sensor;
  input [3:0] water_level, volume_cmd, pin_input;
  output heater_on, cooler_on, water_pump_on, water_valve_close,
       burglar_alarm_out, tv_on, music_on, ac_on, fan_on, lights_on,
       door_locked, humidifier_on, dehumidifier_on, DFT_sdo_1,
       DFT_sdo_2;
  output [7:0] led_brightness, visitor_count, system_status;
  output [1:0] window_state, lock_status;
  output [3:0] volume_level;
  wire clk, rst_n, motion_sensor, door_sensor, window_sensor,
       alarm_arm, entry_sensor, exit_sensor, window_auto_mode,
       window_manual_open, window_manual_close, tv_on_cmd,
       music_on_cmd, ac_cmd, fan_cmd, light_cmd, door_lock_cmd,
       door_unlock_cmd, scan_en, test_mode, DFT_sdi_1, DFT_sdi_2;
  wire [7:0] temp_sensor, temp_setpoint, light_sensor, humidity_sensor;
  wire [3:0] water_level, volume_cmd, pin_input;
  wire heater_on, cooler_on, water_pump_on, water_valve_close,
       burglar_alarm_out, tv_on, music_on, ac_on, fan_on, lights_on,
       door_locked, humidifier_on, dehumidifier_on, DFT_sdo_1,
       DFT_sdo_2;
  wire [7:0] led_brightness, visitor_count, system_status;
  wire [1:0] window_state, lock_status;
  wire [3:0] volume_level;
  wire [3:0] pin_input_r;
  wire [1:0] lock_status_int;
  wire [3:0] volume_cmd_r;
  wire [3:0] volume_level_int;
  wire [7:0] humidity_sensor_r;
  wire [7:0] light_sensor_r;
  wire [7:0] led_brightness_int;
  wire [7:0] temp_sensor_r;
  wire [7:0] temp_setpoint_r;
  wire [7:0] visitor_count_int;
  wire [3:0] water_level_r;
  wire [1:0] window_state_int;
  wire ac_cmd_r, ac_on_int, alarm_arm_r, burglar_alarm_out_int,
       cooler_on_int, dehumidifier_on_int, door_lock_cmd_r,
       door_locked_int;
  wire door_sensor_r, door_unlock_cmd_r, entry_sensor_r, exit_sensor_r,
       fan_cmd_r, fan_on_int, heater_on_int, humidifier_on_int;
  wire light_cmd_r, lights_on_int, motion_sensor_r, music_on_cmd_r,
       music_on_int, n_64, n_65, n_66;
  wire tv_on_cmd_r, tv_on_int, water_pump_on_int,
       water_valve_close_int, window_auto_mode_r,
       window_manual_close_r, window_manual_open_r, window_sensor_r;
  assign DFT_sdo_2 = window_state[1];
  assign system_status[0] = cooler_on;
  assign system_status[1] = heater_on;
  assign system_status[2] = lights_on;
  assign system_status[3] = fan_on;
  assign system_status[4] = ac_on;
  assign system_status[5] = door_locked;
  assign system_status[6] = water_pump_on;
  assign system_status[7] = burglar_alarm_out;
  appliances_controller u_appliances(.clk (clk), .rst_n (rst_n),
       .ac_cmd (ac_cmd_r), .fan_cmd (fan_cmd_r), .light_cmd
       (light_cmd_r), .ac_on (ac_on_int), .fan_on (fan_on_int),
       .lights_on (lights_on_int), .DFT_sdi (DFT_sdi_1), .DFT_sen
       (scan_en));
  burglar_alarm u_burglar(.clk (clk), .rst_n (rst_n), .motion_sensor
       (motion_sensor_r), .door_sensor (door_sensor_r), .window_sensor
       (window_sensor_r), .alarm_arm (alarm_arm_r), .alarm_out
       (burglar_alarm_out_int), .DFT_sdi (lights_on_int), .DFT_sen
       (scan_en), .DFT_sdo (n_64));
  door_lock_controller u_door_lock(.clk (clk), .rst_n (rst_n),
       .lock_cmd (door_lock_cmd_r), .unlock_cmd (door_unlock_cmd_r),
       .pin_input (pin_input_r), .door_locked (door_locked_int),
       .lock_status (lock_status_int), .DFT_sdi (n_64), .DFT_sen
       (scan_en), .DFT_sdo (n_65));
  entertainment_system u_entertainment(.clk (clk), .rst_n (rst_n),
       .tv_on_cmd (tv_on_cmd_r), .music_on_cmd (music_on_cmd_r),
       .volume_cmd (volume_cmd_r), .tv_on (tv_on_int), .music_on
       (music_on_int), .volume_level (volume_level_int), .DFT_sdi
       (n_65), .DFT_sen (scan_en));
  humidity_controller u_humidity(.clk (clk), .rst_n (rst_n),
       .humidity_sensor ({humidity_sensor_r[7:2], DFT_sdo_1,
       humidity_sensor_r[0]}), .humidifier_on (humidifier_on_int),
       .dehumidifier_on (dehumidifier_on_int), .DFT_sdi
       (volume_level_int[3]), .DFT_sen (scan_en));
  luminosity_controller u_lum_ctrl(.clk (clk), .rst_n (rst_n),
       .light_sensor (light_sensor_r), .led_brightness
       (led_brightness_int), .DFT_sdi (humidifier_on_int), .DFT_sen
       (scan_en));
  temperature_controller u_temp_ctrl(.clk (clk), .rst_n (rst_n),
       .temp_sensor (temp_sensor_r), .temp_setpoint (temp_setpoint_r),
       .heater_on (heater_on_int), .cooler_on (cooler_on_int), .DFT_sdi
       (led_brightness_int[7]), .DFT_sen (scan_en));
  visitor_counter u_visitor(.clk (clk), .rst_n (rst_n), .entry_sensor
       (entry_sensor_r), .exit_sensor (exit_sensor_r), .count
       (visitor_count_int), .DFT_sdi (heater_on_int), .DFT_sen
       (scan_en), .DFT_sdo (n_66));
  water_level_controller u_water_ctrl(.clk (clk), .rst_n (rst_n),
       .water_level (water_level_r), .pump_on (water_pump_on_int),
       .valve_close (water_valve_close_int), .DFT_sdi (n_66), .DFT_sen
       (scan_en));
  window_treatment u_window(.clk (clk), .rst_n (rst_n), .auto_mode
       (window_auto_mode_r), .light_level (light_sensor_r),
       .manual_open (window_manual_open_r), .manual_close
       (window_manual_close_r), .window_state (window_state_int),
       .DFT_sdi (water_valve_close_int), .DFT_sen (scan_en));
  SDFFRHQX1 water_valve_close_r_reg(.RN (rst_n), .CK (clk), .D
       (water_valve_close_int), .SI (water_pump_on), .SE (scan_en), .Q
       (water_valve_close));
  SDFFRHQX1 tv_on_r_reg(.RN (rst_n), .CK (clk), .D (tv_on_int), .SI
       (tv_on_cmd_r), .SE (scan_en), .Q (tv_on));
  SDFFRHQX1 music_on_r_reg(.RN (rst_n), .CK (clk), .D (music_on_int),
       .SI (music_on_cmd_r), .SE (scan_en), .Q (music_on));
  SDFFRHQX1 \led_brightness_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[4]), .SI (led_brightness[3]), .SE (scan_en),
       .Q (led_brightness[4]));
  SDFFRHQX1 \led_brightness_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[3]), .SI (led_brightness[2]), .SE (scan_en),
       .Q (led_brightness[3]));
  SDFFRHQX1 humidifier_on_r_reg(.RN (rst_n), .CK (clk), .D
       (humidifier_on_int), .SI (heater_on), .SE (scan_en), .Q
       (humidifier_on));
  SDFFRHQX1 dehumidifier_on_r_reg(.RN (rst_n), .CK (clk), .D
       (dehumidifier_on_int), .SI (cooler_on), .SE (scan_en), .Q
       (dehumidifier_on));
  SDFFRHQX1 \led_brightness_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[6]), .SI (led_brightness[5]), .SE (scan_en),
       .Q (led_brightness[6]));
  SDFFRHQX1 lights_on_r_reg(.RN (rst_n), .CK (clk), .D (lights_on_int),
       .SI (light_sensor_r[7]), .SE (scan_en), .Q (lights_on));
  SDFFRHQX1 \led_brightness_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[1]), .SI (led_brightness[0]), .SE (scan_en),
       .Q (led_brightness[1]));
  SDFFRHQX1 \led_brightness_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[0]), .SI (humidity_sensor_r[7]), .SE
       (scan_en), .Q (led_brightness[0]));
  SDFFRHQX1 \led_brightness_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[7]), .SI (led_brightness[6]), .SE (scan_en),
       .Q (led_brightness[7]));
  SDFFRHQX1 \led_brightness_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[5]), .SI (led_brightness[4]), .SE (scan_en),
       .Q (led_brightness[5]));
  SDFFRHQX1 \led_brightness_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[2]), .SI (led_brightness[1]), .SE (scan_en),
       .Q (led_brightness[2]));
  SDFFRHQX1 ac_on_r_reg(.RN (rst_n), .CK (clk), .D (ac_on_int), .SI
       (ac_cmd_r), .SE (scan_en), .Q (ac_on));
  SDFFRHQX1 fan_on_r_reg(.RN (rst_n), .CK (clk), .D (fan_on_int), .SI
       (fan_cmd_r), .SE (scan_en), .Q (fan_on));
  SDFFRHQX1 \lock_status_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (lock_status_int[0]), .SI (lights_on), .SE (scan_en), .Q
       (lock_status[0]));
  SDFFRHQX1 \lock_status_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (lock_status_int[1]), .SI (lock_status[0]), .SE (scan_en), .Q
       (lock_status[1]));
  SDFFRHQX1 door_locked_r_reg(.RN (rst_n), .CK (clk), .D
       (door_locked_int), .SI (door_lock_cmd_r), .SE (scan_en), .Q
       (door_locked));
  SDFFRHQX1 \volume_level_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (volume_level_int[1]), .SI (volume_level[0]), .SE (scan_en), .Q
       (volume_level[1]));
  SDFFRHQX1 \volume_level_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (volume_level_int[2]), .SI (volume_level[1]), .SE (scan_en), .Q
       (volume_level[2]));
  SDFFRHQX1 \volume_level_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (volume_level_int[3]), .SI (volume_level[2]), .SE (scan_en), .Q
       (volume_level[3]));
  SDFFRHQX1 \volume_level_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (volume_level_int[0]), .SI (volume_cmd_r[3]), .SE (scan_en), .Q
       (volume_level[0]));
  SDFFRHQX1 water_pump_on_r_reg(.RN (rst_n), .CK (clk), .D
       (water_pump_on_int), .SI (water_level_r[3]), .SE (scan_en), .Q
       (water_pump_on));
  SDFFRHQX1 \visitor_count_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[1]), .SI (visitor_count[0]), .SE (scan_en),
       .Q (visitor_count[1]));
  SDFFRHQX1 \temp_sensor_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[3]), .SI (temp_sensor_r[2]), .SE (scan_en), .Q
       (temp_sensor_r[3]));
  SDFFRHQX1 \visitor_count_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[5]), .SI (visitor_count[4]), .SE (scan_en),
       .Q (visitor_count[5]));
  SDFFRHQX1 \visitor_count_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[4]), .SI (visitor_count[3]), .SE (scan_en),
       .Q (visitor_count[4]));
  SDFFRHQX1 \visitor_count_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[2]), .SI (visitor_count[1]), .SE (scan_en),
       .Q (visitor_count[2]));
  SDFFRHQX1 \temp_sensor_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[7]), .SI (temp_sensor_r[6]), .SE (scan_en), .Q
       (temp_sensor_r[7]));
  SDFFRHQX1 \visitor_count_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[3]), .SI (visitor_count[2]), .SE (scan_en),
       .Q (visitor_count[3]));
  SDFFRHQX1 \temp_setpoint_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[0]), .SI (temp_sensor_r[7]), .SE (scan_en), .Q
       (temp_setpoint_r[0]));
  SDFFRHQX1 \temp_sensor_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[6]), .SI (temp_sensor_r[5]), .SE (scan_en), .Q
       (temp_sensor_r[6]));
  SDFFRHQX1 \temp_setpoint_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[4]), .SI (temp_setpoint_r[3]), .SE (scan_en), .Q
       (temp_setpoint_r[4]));
  SDFFRHQX1 \window_state_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (window_state_int[1]), .SI (window_state[0]), .SE (scan_en), .Q
       (window_state[1]));
  SDFFRHQX1 \visitor_count_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[0]), .SI (tv_on), .SE (scan_en), .Q
       (visitor_count[0]));
  SDFFRHQX1 \window_state_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (window_state_int[0]), .SI (window_sensor_r), .SE (scan_en), .Q
       (window_state[0]));
  SDFFRHQX1 \water_level_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (water_level[0]), .SI (volume_level[3]), .SE (scan_en), .Q
       (water_level_r[0]));
  SDFFRHQX1 \visitor_count_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[7]), .SI (visitor_count[6]), .SE (scan_en),
       .Q (visitor_count[7]));
  SDFFRHQX1 \humidity_sensor_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[4]), .SI (humidity_sensor_r[3]), .SE (scan_en),
       .Q (humidity_sensor_r[4]));
  SDFFRHQX1 \visitor_count_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[6]), .SI (visitor_count[5]), .SE (scan_en),
       .Q (visitor_count[6]));
  SDFFRHQX1 \temp_sensor_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[5]), .SI (temp_sensor_r[4]), .SE (scan_en), .Q
       (temp_sensor_r[5]));
  SDFFRHQX1 \volume_cmd_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (volume_cmd[3]), .SI (volume_cmd_r[2]), .SE (scan_en), .Q
       (volume_cmd_r[3]));
  SDFFRHQX1 light_cmd_r_reg(.RN (rst_n), .CK (clk), .D (light_cmd), .SI
       (led_brightness[7]), .SE (scan_en), .Q (light_cmd_r));
  SDFFRHQX1 ac_cmd_r_reg(.RN (rst_n), .CK (clk), .D (ac_cmd), .SI
       (window_state_int[1]), .SE (scan_en), .Q (ac_cmd_r));
  SDFFRHQX1 window_manual_open_r_reg(.RN (rst_n), .CK (clk), .D
       (window_manual_open), .SI (window_manual_close_r), .SE
       (scan_en), .Q (window_manual_open_r));
  SDFFRHQX1 window_auto_mode_r_reg(.RN (rst_n), .CK (clk), .D
       (window_auto_mode), .SI (water_valve_close), .SE (scan_en), .Q
       (window_auto_mode_r));
  SDFFRHQX1 \temp_setpoint_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[7]), .SI (temp_setpoint_r[6]), .SE (scan_en), .Q
       (temp_setpoint_r[7]));
  SDFFRHQX1 window_sensor_r_reg(.RN (rst_n), .CK (clk), .D
       (window_sensor), .SI (window_manual_open_r), .SE (scan_en), .Q
       (window_sensor_r));
  SDFFRHQX1 \temp_setpoint_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[6]), .SI (temp_setpoint_r[5]), .SE (scan_en), .Q
       (temp_setpoint_r[6]));
  SDFFRHQX1 \temp_setpoint_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[5]), .SI (temp_setpoint_r[4]), .SE (scan_en), .Q
       (temp_setpoint_r[5]));
  SDFFRHQX1 \temp_setpoint_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[3]), .SI (temp_setpoint_r[2]), .SE (scan_en), .Q
       (temp_setpoint_r[3]));
  SDFFRHQX1 window_manual_close_r_reg(.RN (rst_n), .CK (clk), .D
       (window_manual_close), .SI (window_auto_mode_r), .SE (scan_en),
       .Q (window_manual_close_r));
  SDFFRHQX1 motion_sensor_r_reg(.RN (rst_n), .CK (clk), .D
       (motion_sensor), .SI (lock_status[1]), .SE (scan_en), .Q
       (motion_sensor_r));
  SDFFRHQX1 \temp_sensor_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[0]), .SI (pin_input_r[3]), .SE (scan_en), .Q
       (temp_sensor_r[0]));
  SDFFRHQX1 \temp_sensor_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[1]), .SI (temp_sensor_r[0]), .SE (scan_en), .Q
       (temp_sensor_r[1]));
  SDFFRHQX1 \temp_sensor_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[2]), .SI (temp_sensor_r[1]), .SE (scan_en), .Q
       (temp_sensor_r[2]));
  SDFFRHQX1 door_sensor_r_reg(.RN (rst_n), .CK (clk), .D (door_sensor),
       .SI (door_locked), .SE (scan_en), .Q (door_sensor_r));
  SDFFRHQX1 \temp_sensor_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[4]), .SI (temp_sensor_r[3]), .SE (scan_en), .Q
       (temp_sensor_r[4]));
  SDFFRHQX1 burglar_alarm_out_r_reg(.RN (rst_n), .CK (clk), .D
       (burglar_alarm_out_int), .SI (alarm_arm_r), .SE (scan_en), .Q
       (burglar_alarm_out));
  SDFFRHQX1 cooler_on_r_reg(.RN (rst_n), .CK (clk), .D (cooler_on_int),
       .SI (burglar_alarm_out), .SE (scan_en), .Q (cooler_on));
  SDFFRHQX1 heater_on_r_reg(.RN (rst_n), .CK (clk), .D (heater_on_int),
       .SI (fan_on), .SE (scan_en), .Q (heater_on));
  SDFFRHQX1 \temp_setpoint_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[1]), .SI (temp_setpoint_r[0]), .SE (scan_en), .Q
       (temp_setpoint_r[1]));
  SDFFRHQX1 \temp_setpoint_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[2]), .SI (temp_setpoint_r[1]), .SE (scan_en), .Q
       (temp_setpoint_r[2]));
  SDFFRHQX1 \pin_input_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (pin_input[2]), .SI (pin_input_r[1]), .SE (scan_en), .Q
       (pin_input_r[2]));
  SDFFRHQX1 \water_level_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (water_level[2]), .SI (water_level_r[1]), .SE (scan_en), .Q
       (water_level_r[2]));
  SDFFRHQX1 \water_level_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (water_level[1]), .SI (water_level_r[0]), .SE (scan_en), .Q
       (water_level_r[1]));
  SDFFRHQX1 alarm_arm_r_reg(.RN (rst_n), .CK (clk), .D (alarm_arm), .SI
       (ac_on), .SE (scan_en), .Q (alarm_arm_r));
  SDFFRHQX1 entry_sensor_r_reg(.RN (rst_n), .CK (clk), .D
       (entry_sensor), .SI (door_unlock_cmd_r), .SE (scan_en), .Q
       (entry_sensor_r));
  SDFFRHQX1 exit_sensor_r_reg(.RN (rst_n), .CK (clk), .D (exit_sensor),
       .SI (entry_sensor_r), .SE (scan_en), .Q (exit_sensor_r));
  SDFFRHQX1 fan_cmd_r_reg(.RN (rst_n), .CK (clk), .D (fan_cmd), .SI
       (exit_sensor_r), .SE (scan_en), .Q (fan_cmd_r));
  SDFFRHQX1 \humidity_sensor_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[0]), .SI (humidifier_on), .SE (scan_en), .Q
       (humidity_sensor_r[0]));
  SDFFRHQX1 \humidity_sensor_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[1]), .SI (humidity_sensor_r[0]), .SE (scan_en),
       .Q (DFT_sdo_1));
  SDFFRHQX1 \humidity_sensor_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[2]), .SI (DFT_sdi_2), .SE (scan_en), .Q
       (humidity_sensor_r[2]));
  SDFFRHQX1 \humidity_sensor_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[3]), .SI (humidity_sensor_r[2]), .SE (scan_en),
       .Q (humidity_sensor_r[3]));
  SDFFRHQX1 \humidity_sensor_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[5]), .SI (humidity_sensor_r[4]), .SE (scan_en),
       .Q (humidity_sensor_r[5]));
  SDFFRHQX1 \humidity_sensor_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[6]), .SI (humidity_sensor_r[5]), .SE (scan_en),
       .Q (humidity_sensor_r[6]));
  SDFFRHQX1 \humidity_sensor_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[7]), .SI (humidity_sensor_r[6]), .SE (scan_en),
       .Q (humidity_sensor_r[7]));
  SDFFRHQX1 music_on_cmd_r_reg(.RN (rst_n), .CK (clk), .D
       (music_on_cmd), .SI (motion_sensor_r), .SE (scan_en), .Q
       (music_on_cmd_r));
  SDFFRHQX1 \pin_input_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (pin_input[0]), .SI (music_on), .SE (scan_en), .Q
       (pin_input_r[0]));
  SDFFRHQX1 \pin_input_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (pin_input[1]), .SI (pin_input_r[0]), .SE (scan_en), .Q
       (pin_input_r[1]));
  SDFFRHQX1 \pin_input_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (pin_input[3]), .SI (pin_input_r[2]), .SE (scan_en), .Q
       (pin_input_r[3]));
  SDFFRHQX1 tv_on_cmd_r_reg(.RN (rst_n), .CK (clk), .D (tv_on_cmd), .SI
       (temp_setpoint_r[7]), .SE (scan_en), .Q (tv_on_cmd_r));
  SDFFRHQX1 door_unlock_cmd_r_reg(.RN (rst_n), .CK (clk), .D
       (door_unlock_cmd), .SI (door_sensor_r), .SE (scan_en), .Q
       (door_unlock_cmd_r));
  SDFFRHQX1 \volume_cmd_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (volume_cmd[1]), .SI (volume_cmd_r[0]), .SE (scan_en), .Q
       (volume_cmd_r[1]));
  SDFFRHQX1 \volume_cmd_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (volume_cmd[2]), .SI (volume_cmd_r[1]), .SE (scan_en), .Q
       (volume_cmd_r[2]));
  SDFFRHQX1 door_lock_cmd_r_reg(.RN (rst_n), .CK (clk), .D
       (door_lock_cmd), .SI (dehumidifier_on), .SE (scan_en), .Q
       (door_lock_cmd_r));
  SDFFRHQX1 \volume_cmd_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (volume_cmd[0]), .SI (visitor_count[7]), .SE (scan_en), .Q
       (volume_cmd_r[0]));
  SDFFRHQX1 \water_level_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (water_level[3]), .SI (water_level_r[2]), .SE (scan_en), .Q
       (water_level_r[3]));
  SDFFRHQX1 \light_sensor_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (light_sensor[6]), .SI (light_sensor_r[5]), .SE (scan_en), .Q
       (light_sensor_r[6]));
  SDFFRHQX1 \light_sensor_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (light_sensor[1]), .SI (light_sensor_r[0]), .SE (scan_en), .Q
       (light_sensor_r[1]));
  SDFFRHQX1 \light_sensor_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (light_sensor[7]), .SI (light_sensor_r[6]), .SE (scan_en), .Q
       (light_sensor_r[7]));
  SDFFRHQX1 \light_sensor_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (light_sensor[2]), .SI (light_sensor_r[1]), .SE (scan_en), .Q
       (light_sensor_r[2]));
  SDFFRHQX1 \light_sensor_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (light_sensor[0]), .SI (light_cmd_r), .SE (scan_en), .Q
       (light_sensor_r[0]));
  SDFFRHQX1 \light_sensor_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (light_sensor[4]), .SI (light_sensor_r[3]), .SE (scan_en), .Q
       (light_sensor_r[4]));
  SDFFRHQX1 \light_sensor_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (light_sensor[5]), .SI (light_sensor_r[4]), .SE (scan_en), .Q
       (light_sensor_r[5]));
  SDFFRHQX1 \light_sensor_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (light_sensor[3]), .SI (light_sensor_r[2]), .SE (scan_en), .Q
       (light_sensor_r[3]));
endmodule

