/*
###############################################################
#  Generated by:      Cadence Innovus 20.10-p004_1
#  OS:                Linux x86_64(Host ID edatools-server2.iiitd.edu.in)
#  Generated on:      Wed Nov 19 00:33:11 2025
#  Design:            HA
#  Command:           saveNetlist rtl_module_post_route_netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Nov  7 2025 23:22:38 IST (Nov  7 2025 17:52:38 UTC)
// Verification Directory fv/HA 
module appliances_controller (
	rst_n, 
	ac_cmd, 
	fan_cmd, 
	light_cmd, 
	ac_on, 
	fan_on, 
	lights_on, 
	DFT_sdi, 
	DFT_sen, 
	led_brightness_int_0, 
	clk, 
	FE_OFN0_rst_n);
   input rst_n;
   input ac_cmd;
   input fan_cmd;
   input light_cmd;
   output ac_on;
   output fan_on;
   output lights_on;
   input DFT_sdi;
   input DFT_sen;
   input led_brightness_int_0;
   input clk;
   input FE_OFN0_rst_n;

   SDFFRHQX1 ac_on_reg (.CK(clk),
	.D(ac_cmd),
	.Q(ac_on),
	.RN(FE_OFN0_rst_n),
	.SE(DFT_sen),
	.SI(fan_on));
   SDFFRHQX1 fan_on_reg (.CK(clk),
	.D(fan_cmd),
	.Q(fan_on),
	.RN(FE_OFN0_rst_n),
	.SE(DFT_sen),
	.SI(fan_cmd));
   SDFFRHQX1 lights_on_reg (.CK(clk),
	.D(light_cmd),
	.Q(lights_on),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(led_brightness_int_0));
endmodule

module burglar_alarm (
	rst_n, 
	motion_sensor, 
	door_sensor, 
	window_sensor, 
	alarm_arm, 
	alarm_out, 
	DFT_sdi, 
	DFT_sen, 
	DFT_sdo, 
	delay_counter_3, 
	SPCASCAN_N2, 
	clk_clone1, 
	clk, 
	FE_OFN5_scan_en);
   input rst_n;
   input motion_sensor;
   input door_sensor;
   input window_sensor;
   input alarm_arm;
   output alarm_out;
   input DFT_sdi;
   input DFT_sen;
   output DFT_sdo;
   output delay_counter_3;
   input SPCASCAN_N2;
   input clk_clone1;
   input clk;
   input FE_OFN5_scan_en;

   // Internal wires
   wire [8:0] delay_counter;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_29;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_39;
   wire n_46;
   wire n_47;

   assign delay_counter_3 = delay_counter[3] ;

   INVX1 FE_OFC0_n_6 (.A(n_6),
	.Y(n_7));
   SDFFRHQX1 \delay_counter_reg[6]  (.CK(clk_clone1),
	.D(n_39),
	.Q(delay_counter[6]),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(SPCASCAN_N2));
   OAI21X1 g671 (.A0(n_12),
	.A1(n_36),
	.B0(n_14),
	.Y(n_39));
   SDFFRHQX1 \delay_counter_reg[5]  (.CK(clk),
	.D(n_47),
	.Q(delay_counter[5]),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(delay_counter[6]));
   SDFFRHQX1 \delay_counter_reg[7]  (.CK(clk_clone1),
	.D(n_37),
	.Q(delay_counter[7]),
	.RN(rst_n),
	.SE(FE_OFN5_scan_en),
	.SI(delay_counter[5]));
   OAI21X1 g675 (.A0(n_12),
	.A1(n_34),
	.B0(n_14),
	.Y(n_37));
   AOI21X1 g676 (.A0(delay_counter[6]),
	.A1(n_29),
	.B0(n_35),
	.Y(n_36));
   SDFFRHQX1 \delay_counter_reg[3]  (.CK(clk),
	.D(n_33),
	.Q(delay_counter[3]),
	.RN(rst_n),
	.SE(FE_OFN5_scan_en),
	.SI(delay_counter[4]));
   NOR2XL g678 (.A(delay_counter[6]),
	.B(n_29),
	.Y(n_35));
   SDFFRHQX1 \delay_counter_reg[4]  (.CK(clk),
	.D(n_31),
	.Q(delay_counter[4]),
	.RN(rst_n),
	.SE(FE_OFN5_scan_en),
	.SI(delay_counter[7]));
   AOI21X1 g680 (.A0(delay_counter[7]),
	.A1(n_26),
	.B0(n_32),
	.Y(n_34));
   OAI22X1 g681 (.A0(n_25),
	.A1(n_12),
	.B0(n_1),
	.B1(n_14),
	.Y(n_33));
   SDFFRHQX1 \delay_counter_reg[8]  (.CK(clk),
	.D(n_27),
	.Q(DFT_sdo),
	.RN(rst_n),
	.SE(FE_OFN5_scan_en),
	.SI(delay_counter[2]));
   SDFFRHQX1 \delay_counter_reg[2]  (.CK(clk),
	.D(n_24),
	.Q(delay_counter[2]),
	.RN(rst_n),
	.SE(FE_OFN5_scan_en),
	.SI(door_sensor));
   NOR2XL g684 (.A(delay_counter[7]),
	.B(n_26),
	.Y(n_32));
   OAI21X1 g685 (.A0(n_21),
	.A1(n_12),
	.B0(n_14),
	.Y(n_31));
   NAND2XL g688 (.A(n_14),
	.B(n_23),
	.Y(n_27));
   NAND2BX1 g689 (.AN(n_18),
	.B(delay_counter[5]),
	.Y(n_29));
   MXI2XL g690 (.A(delay_counter[3]),
	.B(n_1),
	.S0(n_10),
	.Y(n_25));
   OAI22X1 g691 (.A0(n_15),
	.A1(n_12),
	.B0(n_2),
	.B1(n_14),
	.Y(n_24));
   NAND3BX1 g692 (.AN(n_18),
	.B(delay_counter[5]),
	.C(delay_counter[6]),
	.Y(n_26));
   SDFFRHQX1 alarm_out_reg (.CK(clk_clone1),
	.D(n_22),
	.Q(alarm_out),
	.RN(rst_n),
	.SE(FE_OFN5_scan_en),
	.SI(delay_counter[1]));
   SDFFRHQX1 \delay_counter_reg[1]  (.CK(clk_clone1),
	.D(n_20),
	.Q(delay_counter[1]),
	.RN(rst_n),
	.SE(FE_OFN5_scan_en),
	.SI(delay_counter[0]));
   OAI21XL g695 (.A0(n_16),
	.A1(DFT_sdo),
	.B0(n_0),
	.Y(n_23));
   SDFFRHQX1 \delay_counter_reg[0]  (.CK(clk_clone1),
	.D(n_19),
	.Q(delay_counter[0]),
	.RN(rst_n),
	.SE(FE_OFN5_scan_en),
	.SI(DFT_sdo));
   OAI2BB1XL g697 (.A0N(alarm_out),
	.A1N(n_0),
	.B0(n_14),
	.Y(n_22));
   AOI21X1 g698 (.A0(delay_counter[4]),
	.A1(n_11),
	.B0(n_17),
	.Y(n_21));
   AO22X1 g699 (.A0(n_5),
	.A1(n_0),
	.B0(delay_counter[1]),
	.B1(n_13),
	.Y(n_20));
   MXI2XL g700 (.A(n_12),
	.B(n_14),
	.S0(delay_counter[0]),
	.Y(n_19));
   NOR2XL g701 (.A(delay_counter[4]),
	.B(n_11),
	.Y(n_17));
   NAND2BX1 g702 (.AN(n_11),
	.B(delay_counter[4]),
	.Y(n_18));
   NOR2XL g703 (.A(n_11),
	.B(n_6),
	.Y(n_16));
   MXI2XL g704 (.A(n_2),
	.B(delay_counter[2]),
	.S0(n_3),
	.Y(n_15));
   CLKINVX1 g705 (.A(n_13),
	.Y(n_14));
   CLKINVX1 g706 (.A(n_0),
	.Y(n_12));
   NOR2XL g707 (.A(n_9),
	.B(n_8),
	.Y(n_13));
   NOR2XL g709 (.A(n_2),
	.B(n_3),
	.Y(n_10));
   OR2X1 g710 (.A(n_4),
	.B(n_3),
	.Y(n_11));
   OAI31X1 g711 (.A0(window_sensor),
	.A1(motion_sensor),
	.A2(door_sensor),
	.B0(alarm_arm),
	.Y(n_9));
   OAI211X1 g713 (.A0(delay_counter[2]),
	.A1(delay_counter[3]),
	.B0(DFT_sdo),
	.C0(n_7),
	.Y(n_8));
   NAND4X1 g715 (.A(delay_counter[6]),
	.B(delay_counter[4]),
	.C(delay_counter[5]),
	.D(delay_counter[7]),
	.Y(n_6));
   XOR2XL g716 (.A(delay_counter[0]),
	.B(delay_counter[1]),
	.Y(n_5));
   NAND2XL g717 (.A(delay_counter[2]),
	.B(delay_counter[3]),
	.Y(n_4));
   NAND2X1 g718 (.A(delay_counter[0]),
	.B(delay_counter[1]),
	.Y(n_3));
   INVX1 g719 (.A(delay_counter[2]),
	.Y(n_2));
   CLKINVX1 g720 (.A(delay_counter[3]),
	.Y(n_1));
   NOR2BX1 g2 (.AN(n_8),
	.B(n_9),
	.Y(n_0));
   OAI21X1 g721 (.A0(n_46),
	.A1(n_12),
	.B0(n_14),
	.Y(n_47));
   CLKXOR2X1 g3 (.A(delay_counter[5]),
	.B(n_18),
	.Y(n_46));
endmodule

module door_lock_controller (
	rst_n, 
	lock_cmd, 
	unlock_cmd, 
	pin_input, 
	door_locked, 
	lock_status, 
	DFT_sdi, 
	DFT_sen, 
	DFT_sdo, 
	attempt_counter_0, 
	timeout_counter_0, 
	p_1, 
	humidifier_on_int, 
	timeout_counter_1, 
	tv_on_int, 
	water_pump_on_int, 
	timeout_counter_5, 
	n_91, 
	clk_clone1, 
	clk, 
	FE_OFN1_rst_n, 
	FE_OFN6_scan_en);
   input rst_n;
   input lock_cmd;
   input unlock_cmd;
   input [3:0] pin_input;
   output door_locked;
   output [1:0] lock_status;
   input DFT_sdi;
   input DFT_sen;
   output DFT_sdo;
   output attempt_counter_0;
   output timeout_counter_0;
   input p_1;
   input humidifier_on_int;
   output timeout_counter_1;
   input tv_on_int;
   input water_pump_on_int;
   output timeout_counter_5;
   input n_91;
   input clk_clone1;
   input clk;
   input FE_OFN1_rst_n;
   input FE_OFN6_scan_en;

   // Internal wires
   wire FE_RN_10_0;
   wire [2:0] attempt_counter;
   wire [1:0] state;
   wire [7:0] timeout_counter;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;

   assign attempt_counter_0 = attempt_counter[0] ;
   assign timeout_counter_0 = timeout_counter[0] ;
   assign timeout_counter_1 = timeout_counter[1] ;
   assign timeout_counter_5 = timeout_counter[5] ;

   NAND2X1 FE_RC_18_0 (.A(timeout_counter[2]),
	.B(timeout_counter[0]),
	.Y(FE_RN_10_0));
   NAND2BX2 FE_RC_17_0 (.AN(FE_RN_10_0),
	.B(timeout_counter[1]),
	.Y(n_1));
   SDFFRHQX1 door_locked_reg (.CK(clk),
	.D(n_55),
	.Q(door_locked),
	.RN(FE_OFN1_rst_n),
	.SE(DFT_sen),
	.SI(humidifier_on_int));
   SDFFRHQX1 \lock_status_reg[1]  (.CK(clk),
	.D(state[1]),
	.Q(lock_status[1]),
	.RN(FE_OFN1_rst_n),
	.SE(DFT_sen),
	.SI(lock_status[0]));
   SDFFRHQX1 \lock_status_reg[0]  (.CK(clk),
	.D(state[0]),
	.Q(lock_status[0]),
	.RN(FE_OFN1_rst_n),
	.SE(DFT_sen),
	.SI(water_pump_on_int));
   OR2X1 g754 (.A(state[0]),
	.B(state[1]),
	.Y(n_55));
   SDFFRHQX1 \timeout_counter_reg[7]  (.CK(clk_clone1),
	.D(n_54),
	.Q(DFT_sdo),
	.RN(FE_OFN1_rst_n),
	.SE(DFT_sen),
	.SI(attempt_counter[2]));
   SDFFRHQX1 \timeout_counter_reg[6]  (.CK(clk_clone1),
	.D(n_52),
	.Q(timeout_counter[6]),
	.RN(FE_OFN1_rst_n),
	.SE(DFT_sen),
	.SI(DFT_sdo));
   NOR2XL g2229 (.A(n_30),
	.B(n_53),
	.Y(n_54));
   AOI21XL g2230 (.A0(timeout_counter[6]),
	.A1(n_49),
	.B0(DFT_sdo),
	.Y(n_53));
   NOR2XL g2231 (.A(n_30),
	.B(n_51),
	.Y(n_52));
   SDFFRHQX1 \timeout_counter_reg[5]  (.CK(clk_clone1),
	.D(n_50),
	.Q(timeout_counter[5]),
	.RN(FE_OFN1_rst_n),
	.SE(DFT_sen),
	.SI(timeout_counter[6]));
   MXI2XL g2233 (.A(n_49),
	.B(n_46),
	.S0(timeout_counter[6]),
	.Y(n_51));
   NOR2XL g2234 (.A(n_30),
	.B(n_48),
	.Y(n_50));
   CLKINVX1 g2235 (.A(n_46),
	.Y(n_49));
   SDFFRHQX1 \timeout_counter_reg[4]  (.CK(clk),
	.D(n_45),
	.Q(timeout_counter[4]),
	.RN(FE_OFN1_rst_n),
	.SE(DFT_sen),
	.SI(p_1));
   AOI21XL g2237 (.A0(timeout_counter[5]),
	.A1(n_42),
	.B0(n_47),
	.Y(n_48));
   NOR2XL g2238 (.A(timeout_counter[5]),
	.B(n_42),
	.Y(n_47));
   NOR2XL g2239 (.A(n_44),
	.B(n_30),
	.Y(n_45));
   NAND2BX1 g2240 (.AN(n_42),
	.B(timeout_counter[5]),
	.Y(n_46));
   SDFFRHQX1 \timeout_counter_reg[3]  (.CK(clk),
	.D(n_41),
	.Q(timeout_counter[3]),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(timeout_counter[2]));
   AOI21XL g2242 (.A0(timeout_counter[4]),
	.A1(n_37),
	.B0(n_43),
	.Y(n_44));
   NOR2XL g2243 (.A(timeout_counter[4]),
	.B(n_37),
	.Y(n_43));
   NOR2XL g2244 (.A(n_40),
	.B(n_30),
	.Y(n_41));
   NAND2BX1 g2245 (.AN(n_37),
	.B(timeout_counter[4]),
	.Y(n_42));
   SDFFRHQX1 \attempt_counter_reg[0]  (.CK(clk_clone1),
	.D(n_39),
	.Q(attempt_counter[0]),
	.RN(rst_n),
	.SE(FE_OFN6_scan_en),
	.SI(DFT_sdi));
   SDFFRHQX1 \attempt_counter_reg[1]  (.CK(clk_clone1),
	.D(n_38),
	.Q(attempt_counter[1]),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(state[0]));
   SDFFRHQX1 \timeout_counter_reg[1]  (.CK(clk),
	.D(n_33),
	.Q(timeout_counter[1]),
	.RN(FE_OFN1_rst_n),
	.SE(DFT_sen),
	.SI(tv_on_int));
   SDFFRHQX1 \timeout_counter_reg[2]  (.CK(clk),
	.D(n_31),
	.Q(timeout_counter[2]),
	.RN(FE_OFN1_rst_n),
	.SE(DFT_sen),
	.SI(timeout_counter[4]));
   SDFFRHQX1 \state_reg[1]  (.CK(clk_clone1),
	.D(n_32),
	.Q(state[1]),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(n_91));
   SDFFRHQX1 \state_reg[0]  (.CK(clk_clone1),
	.D(n_34),
	.Q(state[0]),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(state[1]));
   AOI21XL g2252 (.A0(timeout_counter[3]),
	.A1(n_1),
	.B0(n_35),
	.Y(n_40));
   AO21X1 g2253 (.A0(attempt_counter[0]),
	.A1(n_28),
	.B0(n_26),
	.Y(n_39));
   OAI22X1 g2254 (.A0(n_19),
	.A1(n_15),
	.B0(n_6),
	.B1(n_29),
	.Y(n_38));
   SDFFRHQX1 \timeout_counter_reg[0]  (.CK(clk),
	.D(n_36),
	.Q(timeout_counter[0]),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(timeout_counter[3]));
   NOR2XL g2256 (.A(timeout_counter[0]),
	.B(n_30),
	.Y(n_36));
   NOR2XL g2257 (.A(timeout_counter[3]),
	.B(n_1),
	.Y(n_35));
   NAND2BX1 g2258 (.AN(n_1),
	.B(timeout_counter[3]),
	.Y(n_37));
   NAND2XL g2259 (.A(n_25),
	.B(n_27),
	.Y(n_34));
   NOR2XL g2260 (.A(n_11),
	.B(n_30),
	.Y(n_33));
   NAND2XL g2261 (.A(n_19),
	.B(n_30),
	.Y(n_32));
   NOR2XL g2262 (.A(n_24),
	.B(n_30),
	.Y(n_31));
   SDFFRHQX1 \attempt_counter_reg[2]  (.CK(clk_clone1),
	.D(n_23),
	.Q(attempt_counter[2]),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(attempt_counter[1]));
   OAI21X1 g2264 (.A0(n_18),
	.A1(n_20),
	.B0(state[1]),
	.Y(n_30));
   INVXL g2265 (.A(n_28),
	.Y(n_29));
   AOI32X1 g2266 (.A0(lock_cmd),
	.A1(n_2),
	.A2(n_3),
	.B0(state[1]),
	.B1(n_21),
	.Y(n_27));
   OAI21X1 g2267 (.A0(n_5),
	.A1(n_19),
	.B0(n_12),
	.Y(n_28));
   AOI211X1 g2268 (.A0(attempt_counter[1]),
	.A1(attempt_counter[2]),
	.B0(attempt_counter[0]),
	.C0(n_19),
	.Y(n_26));
   OAI21X1 g2269 (.A0(n_10),
	.A1(n_17),
	.B0(state[0]),
	.Y(n_25));
   AOI21XL g2270 (.A0(timeout_counter[2]),
	.A1(n_7),
	.B0(n_22),
	.Y(n_24));
   OAI32X1 g2271 (.A0(n_3),
	.A1(n_10),
	.A2(n_16),
	.B0(n_5),
	.B1(n_12),
	.Y(n_23));
   NOR2XL g2272 (.A(timeout_counter[2]),
	.B(n_7),
	.Y(n_22));
   INVXL g2274 (.A(n_20),
	.Y(n_21));
   AOI31X1 g2275 (.A0(DFT_sdo),
	.A1(timeout_counter[6]),
	.A2(n_0),
	.B0(n_3),
	.Y(n_18));
   AOI31X1 g2276 (.A0(timeout_counter[5]),
	.A1(timeout_counter[6]),
	.A2(n_14),
	.B0(DFT_sdo),
	.Y(n_20));
   NAND3BX1 g2277 (.AN(n_10),
	.B(state[0]),
	.C(n_13),
	.Y(n_19));
   INVX1 g2279 (.A(n_16),
	.Y(n_17));
   OAI2BB1X1 g2280 (.A0N(n_5),
	.A1N(n_9),
	.B0(n_13),
	.Y(n_16));
   AOI32X1 g2281 (.A0(attempt_counter[0]),
	.A1(n_6),
	.A2(n_5),
	.B0(attempt_counter[1]),
	.B1(n_4),
	.Y(n_15));
   NAND2BX1 g2283 (.AN(timeout_counter[2]),
	.B(n_8),
	.Y(n_14));
   XNOR2XL g2284 (.A(timeout_counter[0]),
	.B(timeout_counter[1]),
	.Y(n_11));
   NAND4BXL g2285 (.AN(pin_input[3]),
	.B(pin_input[0]),
	.C(pin_input[1]),
	.D(pin_input[2]),
	.Y(n_13));
   AOI2BB1X1 g2286 (.A0N(unlock_cmd),
	.A1N(n_3),
	.B0(state[1]),
	.Y(n_12));
   NAND2XL g2287 (.A(attempt_counter[0]),
	.B(attempt_counter[1]),
	.Y(n_9));
   NAND2XL g2288 (.A(unlock_cmd),
	.B(n_2),
	.Y(n_10));
   NOR2XL g2289 (.A(timeout_counter[3]),
	.B(timeout_counter[4]),
	.Y(n_8));
   NAND2XL g2290 (.A(timeout_counter[0]),
	.B(timeout_counter[1]),
	.Y(n_7));
   CLKINVX1 g2295 (.A(state[1]),
	.Y(n_2));
   INVX1 g2296 (.A(attempt_counter[1]),
	.Y(n_6));
   CLKINVX1 g2297 (.A(attempt_counter[2]),
	.Y(n_5));
   INVXL g2298 (.A(attempt_counter[0]),
	.Y(n_4));
   CLKINVX1 g2299 (.A(state[0]),
	.Y(n_3));
   NAND2BX1 g2300 (.AN(timeout_counter[5]),
	.B(n_8),
	.Y(n_0));
endmodule

module entertainment_system (
	rst_n, 
	tv_on_cmd, 
	music_on_cmd, 
	volume_cmd, 
	tv_on, 
	music_on, 
	volume_level, 
	DFT_sdi, 
	DFT_sen, 
	lock_status_int_1, 
	dehumidifier_on, 
	clk);
   input rst_n;
   input tv_on_cmd;
   input music_on_cmd;
   input [3:0] volume_cmd;
   output tv_on;
   output music_on;
   output [3:0] volume_level;
   input DFT_sdi;
   input DFT_sen;
   input lock_status_int_1;
   input dehumidifier_on;
   input clk;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;

   SDFFRHQX1 tv_on_reg (.CK(clk),
	.D(tv_on_cmd),
	.Q(tv_on),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(music_on));
   SDFFRHQX1 music_on_reg (.CK(clk),
	.D(music_on_cmd),
	.Q(music_on),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(DFT_sdi));
   SDFFSHQX1 \volume_level_reg[0]  (.CK(clk),
	.D(n_3),
	.Q(volume_level[0]),
	.SE(DFT_sen),
	.SI(lock_status_int_1),
	.SN(rst_n));
   SDFFSHQX1 \volume_level_reg[2]  (.CK(clk),
	.D(n_2),
	.Q(volume_level[2]),
	.SE(DFT_sen),
	.SI(volume_level[3]),
	.SN(rst_n));
   SDFFRHQX1 \volume_level_reg[1]  (.CK(clk),
	.D(n_4),
	.Q(volume_level[1]),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(dehumidifier_on));
   SDFFRHQX1 \volume_level_reg[3]  (.CK(clk),
	.D(n_1),
	.Q(volume_level[3]),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(volume_level[1]));
   MX2X1 g44 (.A(volume_cmd[1]),
	.B(volume_level[1]),
	.S0(n_0),
	.Y(n_4));
   MX2X1 g45 (.A(volume_cmd[0]),
	.B(volume_level[0]),
	.S0(n_0),
	.Y(n_3));
   MX2X1 g46 (.A(volume_cmd[2]),
	.B(volume_level[2]),
	.S0(n_0),
	.Y(n_2));
   MX2X1 g47 (.A(volume_cmd[3]),
	.B(volume_level[3]),
	.S0(n_0),
	.Y(n_1));
   NOR4X1 g48 (.A(volume_cmd[3]),
	.B(volume_cmd[2]),
	.C(volume_cmd[1]),
	.D(volume_cmd[0]),
	.Y(n_0));
endmodule

module humidity_controller (
	rst_n, 
	humidity_sensor, 
	humidifier_on, 
	dehumidifier_on, 
	DFT_sdi, 
	DFT_sen, 
	SPCASCAN_N4, 
	clk);
   input rst_n;
   input [7:0] humidity_sensor;
   output humidifier_on;
   output dehumidifier_on;
   input DFT_sdi;
   input DFT_sen;
   input SPCASCAN_N4;
   input clk;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;

   SDFFRHQX1 dehumidifier_on_reg (.CK(clk),
	.D(n_5),
	.Q(dehumidifier_on),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(DFT_sdi));
   SDFFRHQX1 humidifier_on_reg (.CK(clk),
	.D(n_4),
	.Q(humidifier_on),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(SPCASCAN_N4));
   AOI21XL g202 (.A0(n_0),
	.A1(n_1),
	.B0(n_3),
	.Y(n_5));
   AOI21X1 g203 (.A0(humidity_sensor[5]),
	.A1(humidity_sensor[3]),
	.B0(n_2),
	.Y(n_4));
   INVXL g204 (.A(n_2),
	.Y(n_3));
   OAI2BB1X1 g205 (.A0N(humidity_sensor[4]),
	.A1N(humidity_sensor[5]),
	.B0(n_0),
	.Y(n_2));
   OAI211X1 g206 (.A0(humidity_sensor[1]),
	.A1(humidity_sensor[0]),
	.B0(humidity_sensor[2]),
	.C0(humidity_sensor[3]),
	.Y(n_1));
   NOR2XL g207 (.A(humidity_sensor[7]),
	.B(humidity_sensor[6]),
	.Y(n_0));
endmodule

module luminosity_controller (
	rst_n, 
	light_sensor, 
	led_brightness, 
	DFT_sdi, 
	DFT_sen, 
	p_1, 
	visitor_count_int_3, 
	clk, 
	FE_OFN3_scan_en);
   input rst_n;
   input [7:0] light_sensor;
   output [7:0] led_brightness;
   input DFT_sdi;
   input DFT_sen;
   input p_1;
   input visitor_count_int_3;
   input clk;
   input FE_OFN3_scan_en;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;

   SDFFRHQX1 \led_brightness_reg[4]  (.CK(clk),
	.D(n_5),
	.Q(led_brightness[4]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(led_brightness[3]));
   SDFFRHQX1 \led_brightness_reg[6]  (.CK(clk),
	.D(n_6),
	.Q(led_brightness[6]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(p_1));
   SDFFRHQX1 \led_brightness_reg[7]  (.CK(clk),
	.D(n_7),
	.Q(led_brightness[7]),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(led_brightness[6]));
   SDFFRHQX1 \led_brightness_reg[0]  (.CK(clk),
	.D(n_4),
	.Q(led_brightness[0]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(DFT_sdi));
   SDFFRHQX1 \led_brightness_reg[2]  (.CK(clk),
	.D(n_0),
	.Q(led_brightness[2]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(led_brightness[5]));
   SDFFRHQX1 \led_brightness_reg[5]  (.CK(clk),
	.D(n_1),
	.Q(led_brightness[5]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(led_brightness[4]));
   SDFFRHQX1 \led_brightness_reg[3]  (.CK(clk),
	.D(n_2),
	.Q(led_brightness[3]),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(visitor_count_int_3));
   SDFFRHQX1 \led_brightness_reg[1]  (.CK(clk),
	.D(n_3),
	.Q(led_brightness[1]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(led_brightness[2]));
   INVX1 g95 (.A(light_sensor[7]),
	.Y(n_7));
   INVX1 g96 (.A(light_sensor[6]),
	.Y(n_6));
   INVX1 g97 (.A(light_sensor[4]),
	.Y(n_5));
   INVX1 g98 (.A(light_sensor[0]),
	.Y(n_4));
   INVX1 g99 (.A(light_sensor[1]),
	.Y(n_3));
   INVX1 g100 (.A(light_sensor[3]),
	.Y(n_2));
   INVX1 g101 (.A(light_sensor[5]),
	.Y(n_1));
   INVX1 g102 (.A(light_sensor[2]),
	.Y(n_0));
endmodule

module temperature_controller (
	rst_n, 
	temp_sensor, 
	temp_setpoint, 
	heater_on, 
	cooler_on, 
	DFT_sdi, 
	DFT_sen, 
	DFT_sdo, 
	n_1, 
	SPCASCAN_N3, 
	clk);
   input rst_n;
   input [7:0] temp_sensor;
   input [7:0] temp_setpoint;
   output heater_on;
   output cooler_on;
   input DFT_sdi;
   input DFT_sen;
   output DFT_sdo;
   output n_1;
   input SPCASCAN_N3;
   input clk;

   // Internal wires
   wire FE_RN_11_0;
   wire FE_RN_9_0;
   wire FE_RN_8_0;
   wire FE_RN_7_0;
   wire FE_RN_6_0;
   wire FE_RN_5_0;
   wire FE_RN_1_0;
   wire FE_RN_0_0;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_112;
   wire n_113;
   wire n_114;

   NOR3X1 FE_RC_21_0 (.A(temp_setpoint[6]),
	.B(temp_setpoint[5]),
	.C(temp_setpoint[4]),
	.Y(n_33));
   NAND2X2 FE_RC_20_0 (.A(temp_sensor[2]),
	.B(n_4),
	.Y(FE_RN_11_0));
   NAND2BX1 FE_RC_19_0 (.AN(temp_sensor[3]),
	.B(FE_RN_11_0),
	.Y(n_3));
   NOR2BX1 FE_RC_16_0 (.AN(FE_RN_1_0),
	.B(temp_setpoint[4]),
	.Y(FE_RN_9_0));
   NOR2BX2 FE_RC_15_0 (.AN(FE_RN_9_0),
	.B(n_31),
	.Y(n_59));
   CLKINVX1 FE_RC_14_0 (.A(temp_setpoint[7]),
	.Y(FE_RN_7_0));
   NAND2XL FE_RC_13_0 (.A(FE_RN_7_0),
	.B(n_33),
	.Y(FE_RN_8_0));
   NOR2X1 FE_RC_12_0 (.A(FE_RN_8_0),
	.B(n_31),
	.Y(n_5));
   NAND3X2 FE_RC_11_0 (.A(n_85),
	.B(n_86),
	.C(n_83),
	.Y(n_89));
   CLKINVX1 FE_RC_10_0 (.A(n_74),
	.Y(FE_RN_5_0));
   CLKINVX1 FE_RC_9_0 (.A(n_71),
	.Y(FE_RN_6_0));
   AOI2BB2X1 FE_RC_8_0 (.A0N(FE_RN_6_0),
	.A1N(FE_RN_5_0),
	.B0(n_79),
	.B1(n_70),
	.Y(n_84));
   CLKINVX1 FE_RC_3_0 (.A(temp_setpoint[5]),
	.Y(FE_RN_1_0));
   CLKINVX1 FE_RC_1_0 (.A(temp_setpoint[4]),
	.Y(FE_RN_0_0));
   AOI22X2 FE_RC_0_0 (.A0(temp_setpoint[4]),
	.A1(n_32),
	.B0(FE_RN_0_0),
	.B1(n_31),
	.Y(n_44));
   SDFFRXL cooler_on_reg (.CK(clk),
	.D(n_92),
	.Q(cooler_on),
	.QN(n_1),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(DFT_sdo));
   SDFFRXL heater_on_reg (.CK(clk),
	.D(n_93),
	.Q(heater_on),
	.QN(DFT_sdo),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(SPCASCAN_N3));
   OAI21X1 g1630 (.A0(n_18),
	.A1(n_90),
	.B0(n_89),
	.Y(n_93));
   OAI21X1 g1631 (.A0(n_13),
	.A1(n_90),
	.B0(n_91),
	.Y(n_92));
   NAND2X1 g1632 (.A(n_88),
	.B(n_89),
	.Y(n_91));
   NAND3X2 g1633 (.A(n_42),
	.B(n_87),
	.C(n_89),
	.Y(n_90));
   INVX1 g1635 (.A(n_87),
	.Y(n_88));
   NAND2X2 g1636 (.A(n_84),
	.B(n_82),
	.Y(n_87));
   NAND2X1 g1637 (.A(n_80),
	.B(n_81),
	.Y(n_86));
   NAND2X1 g1638 (.A(n_73),
	.B(n_81),
	.Y(n_85));
   AOI31X1 g1640 (.A0(temp_sensor[6]),
	.A1(n_56),
	.A2(n_76),
	.B0(n_7),
	.Y(n_83));
   AOI21X1 g1641 (.A0(n_69),
	.A1(n_79),
	.B0(n_114),
	.Y(n_82));
   AOI21X1 g1642 (.A0(n_12),
	.A1(n_75),
	.B0(n_55),
	.Y(n_81));
   AOI211X1 g1643 (.A0(n_61),
	.A1(n_52),
	.B0(n_8),
	.C0(n_72),
	.Y(n_80));
   AOI21X1 g1644 (.A0(temp_sensor[6]),
	.A1(n_62),
	.B0(n_78),
	.Y(n_79));
   NOR2XL g1645 (.A(n_11),
	.B(n_71),
	.Y(n_78));
   INVXL g1647 (.A(n_75),
	.Y(n_76));
   OAI21X1 g1648 (.A0(temp_sensor[6]),
	.A1(n_62),
	.B0(temp_sensor[7]),
	.Y(n_74));
   OAI21XL g1649 (.A0(n_68),
	.A1(n_64),
	.B0(n_65),
	.Y(n_73));
   OAI21X1 g1650 (.A0(n_15),
	.A1(n_59),
	.B0(n_37),
	.Y(n_75));
   NOR2X1 g1651 (.A(temp_sensor[5]),
	.B(n_63),
	.Y(n_72));
   NOR2X1 g1653 (.A(n_66),
	.B(n_112),
	.Y(n_70));
   OAI32X1 g1654 (.A0(temp_sensor[4]),
	.A1(n_6),
	.A2(n_51),
	.B0(temp_sensor[5]),
	.B1(n_43),
	.Y(n_69));
   NAND2BX1 g1655 (.AN(temp_setpoint[7]),
	.B(n_58),
	.Y(n_71));
   INVX1 g1657 (.A(n_63),
	.Y(n_68));
   OAI2BB1X1 g1659 (.A0N(temp_sensor[4]),
	.A1N(n_6),
	.B0(n_50),
	.Y(n_66));
   NAND2XL g1660 (.A(temp_sensor[5]),
	.B(n_60),
	.Y(n_65));
   NOR2XL g1661 (.A(temp_sensor[5]),
	.B(n_60),
	.Y(n_64));
   OAI221X1 g1662 (.A0(temp_sensor[3]),
	.A1(n_39),
	.B0(temp_sensor[2]),
	.B1(n_4),
	.C0(n_48),
	.Y(n_61));
   AOI21X1 g1663 (.A0(temp_setpoint[5]),
	.A1(n_40),
	.B0(n_59),
	.Y(n_63));
   AOI21X1 g1664 (.A0(temp_setpoint[6]),
	.A1(n_45),
	.B0(n_57),
	.Y(n_62));
   NAND4XL g1665 (.A(temp_setpoint[6]),
	.B(temp_setpoint[3]),
	.C(n_25),
	.D(n_19),
	.Y(n_58));
   NOR4X1 g1667 (.A(temp_setpoint[6]),
	.B(n_16),
	.C(n_24),
	.D(n_20),
	.Y(n_57));
   NOR2BX1 g1668 (.AN(temp_sensor[4]),
	.B(n_44),
	.Y(n_60));
   INVX1 g1670 (.A(n_55),
	.Y(n_56));
   OAI21X1 g1671 (.A0(temp_sensor[3]),
	.A1(n_113),
	.B0(n_2),
	.Y(n_54));
   AOI21XL g1672 (.A0(temp_sensor[2]),
	.A1(n_35),
	.B0(n_49),
	.Y(n_53));
   AOI32X1 g1674 (.A0(temp_sensor[3]),
	.A1(temp_sensor[2]),
	.A2(n_4),
	.B0(n_39),
	.B1(n_3),
	.Y(n_52));
   NOR2X1 g1675 (.A(temp_sensor[7]),
	.B(n_46),
	.Y(n_55));
   INVX1 g1678 (.A(n_50),
	.Y(n_51));
   OAI31X1 g1679 (.A0(temp_setpoint[0]),
	.A1(n_17),
	.A2(n_21),
	.B0(n_22),
	.Y(n_49));
   AOI31X1 g1680 (.A0(temp_setpoint[0]),
	.A1(n_17),
	.A2(n_22),
	.B0(n_21),
	.Y(n_48));
   NAND2X1 g1681 (.A(temp_sensor[5]),
	.B(n_43),
	.Y(n_50));
   NAND2XL g1683 (.A(temp_sensor[3]),
	.B(n_113),
	.Y(n_47));
   AOI21X1 g1684 (.A0(temp_setpoint[7]),
	.A1(n_37),
	.B0(n_5),
	.Y(n_46));
   NAND3XL g1685 (.A(temp_setpoint[3]),
	.B(n_25),
	.C(n_19),
	.Y(n_45));
   OAI21X1 g1689 (.A0(n_21),
	.A1(n_23),
	.B0(n_30),
	.Y(n_42));
   AOI21X1 g1691 (.A0(temp_setpoint[5]),
	.A1(n_29),
	.B0(n_41),
	.Y(n_43));
   NOR3X1 g1692 (.A(temp_setpoint[5]),
	.B(n_28),
	.C(n_20),
	.Y(n_41));
   NAND2XL g1694 (.A(n_10),
	.B(n_32),
	.Y(n_40));
   AOI2BB1X2 g1695 (.A0N(n_16),
	.A1N(n_27),
	.B0(n_32),
	.Y(n_39));
   NAND2X1 g1697 (.A(n_33),
	.B(n_32),
	.Y(n_37));
   INVXL g1698 (.A(n_4),
	.Y(n_35));
   NAND2XL g1700 (.A(temp_setpoint[3]),
	.B(n_19),
	.Y(n_36));
   CLKINVX2 g1703 (.A(n_32),
	.Y(n_31));
   MXI2XL g1705 (.A(temp_sensor[0]),
	.B(n_17),
	.S0(temp_setpoint[0]),
	.Y(n_30));
   NAND2BX1 g1706 (.AN(n_28),
	.B(n_19),
	.Y(n_29));
   CLKAND2X6 g1707 (.A(n_14),
	.B(n_26),
	.Y(n_32));
   NAND2X1 g1709 (.A(temp_setpoint[4]),
	.B(temp_setpoint[3]),
	.Y(n_28));
   NOR2X2 g1710 (.A(temp_setpoint[3]),
	.B(temp_setpoint[2]),
	.Y(n_26));
   NOR2X1 g1711 (.A(temp_setpoint[2]),
	.B(temp_setpoint[1]),
	.Y(n_27));
   CLKINVX1 g1712 (.A(n_24),
	.Y(n_25));
   INVXL g1713 (.A(n_22),
	.Y(n_23));
   CLKINVX2 g1714 (.A(n_20),
	.Y(n_19));
   NAND2X2 g1715 (.A(temp_setpoint[5]),
	.B(temp_setpoint[4]),
	.Y(n_24));
   NAND2XL g1716 (.A(temp_setpoint[1]),
	.B(temp_sensor[1]),
	.Y(n_22));
   NOR2XL g1717 (.A(temp_sensor[1]),
	.B(temp_setpoint[1]),
	.Y(n_21));
   NAND2X4 g1718 (.A(temp_setpoint[2]),
	.B(temp_setpoint[1]),
	.Y(n_20));
   INVXL g1719 (.A(heater_on),
	.Y(n_18));
   CLKINVX1 g1720 (.A(temp_sensor[0]),
	.Y(n_17));
   CLKINVX1 g1721 (.A(temp_setpoint[3]),
	.Y(n_16));
   INVXL g1723 (.A(temp_setpoint[6]),
	.Y(n_15));
   CLKINVX2 g1724 (.A(temp_setpoint[1]),
	.Y(n_14));
   INVXL g1725 (.A(cooler_on),
	.Y(n_13));
   CLKINVX1 g1726 (.A(temp_sensor[6]),
	.Y(n_12));
   CLKINVX1 g1728 (.A(temp_sensor[7]),
	.Y(n_11));
   INVXL g1729 (.A(temp_setpoint[4]),
	.Y(n_10));
   NOR2BXL g1736 (.AN(n_44),
	.B(temp_sensor[4]),
	.Y(n_8));
   NOR2BXL g1737 (.AN(n_46),
	.B(n_11),
	.Y(n_7));
   CLKXOR2X1 g1738 (.A(n_36),
	.B(temp_setpoint[4]),
	.Y(n_6));
   NOR2BX2 g1740 (.AN(n_20),
	.B(n_27),
	.Y(n_4));
   NAND2BX1 g1742 (.AN(temp_sensor[2]),
	.B(n_4),
	.Y(n_2));
   OAI21X1 g1743 (.A0(n_54),
	.A1(n_53),
	.B0(n_47),
	.Y(n_112));
   XNOR2XL g1744 (.A(n_20),
	.B(n_16),
	.Y(n_113));
   NOR3BXL g1745 (.AN(n_12),
	.B(temp_sensor[7]),
	.C(n_62),
	.Y(n_114));
endmodule

module visitor_counter (
	rst_n, 
	entry_sensor, 
	exit_sensor, 
	count, 
	DFT_sdi, 
	DFT_sen, 
	DFT_sdo, 
	SPCASCAN_N5, 
	led_brightness_int_7, 
	clk_clone1, 
	clk, 
	FE_OFN2_rst_n, 
	FE_OFN7_scan_en, 
	FE_OFN4_scan_en);
   input rst_n;
   input entry_sensor;
   input exit_sensor;
   output [7:0] count;
   input DFT_sdi;
   input DFT_sen;
   output DFT_sdo;
   input SPCASCAN_N5;
   input led_brightness_int_7;
   input clk_clone1;
   input clk;
   input FE_OFN2_rst_n;
   input FE_OFN7_scan_en;
   input FE_OFN4_scan_en;

   // Internal wires
   wire FE_RN_4_0;
   wire FE_RN_3_0;
   wire FE_RN_2_0;
   wire FE_OFN0_visitor_count_int_6;
   wire entry_prev;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;

   CLKINVX1 FE_RC_7_0 (.A(n_26),
	.Y(FE_RN_2_0));
   NAND2BX1 FE_RC_6_0 (.AN(n_47),
	.B(FE_RN_2_0),
	.Y(FE_RN_3_0));
   OR2X1 FE_RC_5_0 (.A(n_4),
	.B(n_30),
	.Y(FE_RN_4_0));
   OAI211X1 FE_RC_4_0 (.A0(n_32),
	.A1(n_41),
	.B0(FE_RN_4_0),
	.C0(FE_RN_3_0),
	.Y(n_50));
   CLKINVX1 FE_OFC2_visitor_count_int_6 (.A(n_4),
	.Y(count[6]));
   INVX2 FE_OFC1_visitor_count_int_6 (.A(FE_OFN0_visitor_count_int_6),
	.Y(n_4));
   SDFFRHQX1 \count_reg[6]  (.CK(clk_clone1),
	.D(n_50),
	.Q(FE_OFN0_visitor_count_int_6),
	.RN(FE_OFN2_rst_n),
	.SE(DFT_sen),
	.SI(count[5]));
   SDFFRHQX4 \count_reg[5]  (.CK(clk),
	.D(n_49),
	.Q(count[5]),
	.RN(FE_OFN2_rst_n),
	.SE(DFT_sen),
	.SI(count[4]));
   SDFFRHQX2 \count_reg[7]  (.CK(clk),
	.D(n_48),
	.Q(count[7]),
	.RN(FE_OFN2_rst_n),
	.SE(DFT_sen),
	.SI(count[6]));
   OAI211X1 g1048 (.A0(n_29),
	.A1(n_32),
	.B0(n_33),
	.C0(n_45),
	.Y(n_49));
   OAI31XL g1049 (.A0(n_26),
	.A1(n_4),
	.A2(n_43),
	.B0(n_46),
	.Y(n_48));
   MXI2XL g1050 (.A(n_4),
	.B(count[6]),
	.S0(n_43),
	.Y(n_47));
   SDFFRHQX2 \count_reg[4]  (.CK(clk),
	.D(n_44),
	.Q(count[4]),
	.RN(FE_OFN2_rst_n),
	.SE(DFT_sen),
	.SI(SPCASCAN_N5));
   OAI31X1 g1052 (.A0(n_25),
	.A1(n_31),
	.A2(n_38),
	.B0(count[7]),
	.Y(n_46));
   OAI211X1 g1053 (.A0(count[5]),
	.A1(n_35),
	.B0(n_25),
	.C0(n_43),
	.Y(n_45));
   OAI222XL g1054 (.A0(n_21),
	.A1(n_32),
	.B0(n_2),
	.B1(n_30),
	.C0(n_36),
	.C1(n_26),
	.Y(n_44));
   SDFFRHQX4 \count_reg[1]  (.CK(clk_clone1),
	.D(n_42),
	.Q(count[1]),
	.RN(rst_n),
	.SE(FE_OFN7_scan_en),
	.SI(count[0]));
   SDFFRHQX2 \count_reg[2]  (.CK(clk_clone1),
	.D(n_39),
	.Q(count[2]),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(count[1]));
   NAND2X1 g1057 (.A(count[5]),
	.B(n_35),
	.Y(n_43));
   SDFFRHQX2 \count_reg[3]  (.CK(clk_clone1),
	.D(n_40),
	.Q(count[3]),
	.RN(FE_OFN2_rst_n),
	.SE(FE_OFN4_scan_en),
	.SI(count[2]));
   OAI211X1 g1059 (.A0(n_0),
	.A1(n_26),
	.B0(n_34),
	.C0(n_1),
	.Y(n_42));
   SDFFRHQX4 \count_reg[0]  (.CK(clk_clone1),
	.D(n_37),
	.Q(count[0]),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(DFT_sdi));
   MXI2XL g1061 (.A(count[6]),
	.B(n_4),
	.S0(n_28),
	.Y(n_41));
   OAI222XL g1062 (.A0(n_27),
	.A1(n_32),
	.B0(n_6),
	.B1(n_30),
	.C0(n_26),
	.C1(n_24),
	.Y(n_40));
   OAI222XL g1063 (.A0(n_17),
	.A1(n_32),
	.B0(n_5),
	.B1(n_30),
	.C0(n_26),
	.C1(n_16),
	.Y(n_39));
   NAND2XL g1064 (.A(n_4),
	.B(n_28),
	.Y(n_38));
   MXI2XL g1065 (.A(n_31),
	.B(n_30),
	.S0(count[0]),
	.Y(n_37));
   MXI2XL g1066 (.A(n_2),
	.B(count[4]),
	.S0(n_23),
	.Y(n_36));
   NAND2XL g1067 (.A(count[1]),
	.B(n_31),
	.Y(n_34));
   NOR2X1 g1068 (.A(n_2),
	.B(n_23),
	.Y(n_35));
   NAND2XL g1069 (.A(count[5]),
	.B(n_31),
	.Y(n_33));
   NAND2X1 g1072 (.A(n_20),
	.B(n_26),
	.Y(n_32));
   CLKINVX2 g1073 (.A(n_31),
	.Y(n_30));
   AOI21X1 g1074 (.A0(count[5]),
	.A1(n_19),
	.B0(n_28),
	.Y(n_29));
   NOR2X2 g1075 (.A(n_20),
	.B(n_25),
	.Y(n_31));
   AOI21X1 g1076 (.A0(count[3]),
	.A1(n_13),
	.B0(n_14),
	.Y(n_27));
   NOR2X1 g1077 (.A(count[5]),
	.B(n_19),
	.Y(n_28));
   CLKINVX2 g1078 (.A(n_26),
	.Y(n_25));
   MXI2XL g1079 (.A(count[3]),
	.B(n_6),
	.S0(n_15),
	.Y(n_24));
   NAND3BX2 g1080 (.AN(entry_prev),
	.B(entry_sensor),
	.C(n_22),
	.Y(n_26));
   NAND2X1 g1081 (.A(count[3]),
	.B(n_15),
	.Y(n_23));
   NAND2X1 g1082 (.A(n_15),
	.B(n_18),
	.Y(n_22));
   OA21XL g1083 (.A0(n_2),
	.A1(n_14),
	.B0(n_19),
	.Y(n_21));
   AOI211X1 g1084 (.A0(n_12),
	.A1(n_14),
	.B0(DFT_sdo),
	.C0(n_3),
	.Y(n_20));
   NOR3X1 g1085 (.A(n_8),
	.B(n_4),
	.C(n_11),
	.Y(n_18));
   NAND2XL g1086 (.A(n_2),
	.B(n_14),
	.Y(n_19));
   MXI2XL g1087 (.A(count[2]),
	.B(n_5),
	.S0(n_9),
	.Y(n_17));
   MXI2XL g1088 (.A(n_5),
	.B(count[2]),
	.S0(n_10),
	.Y(n_16));
   NOR2X2 g1090 (.A(n_5),
	.B(n_10),
	.Y(n_15));
   NAND2XL g1091 (.A(n_5),
	.B(n_9),
	.Y(n_13));
   NOR4X1 g1092 (.A(count[7]),
	.B(count[6]),
	.C(count[5]),
	.D(count[4]),
	.Y(n_12));
   AND2X1 g1093 (.A(n_9),
	.B(n_7),
	.Y(n_14));
   SDFFRHQX1 exit_prev_reg (.CK(clk_clone1),
	.D(exit_sensor),
	.Q(DFT_sdo),
	.RN(FE_OFN2_rst_n),
	.SE(DFT_sen),
	.SI(entry_prev));
   SDFFRHQX1 entry_prev_reg (.CK(clk_clone1),
	.D(entry_sensor),
	.Q(entry_prev),
	.RN(FE_OFN2_rst_n),
	.SE(DFT_sen),
	.SI(led_brightness_int_7));
   NAND2XL g1096 (.A(count[4]),
	.B(count[5]),
	.Y(n_11));
   NAND2X1 g1098 (.A(count[3]),
	.B(count[7]),
	.Y(n_8));
   NOR2XL g1099 (.A(count[3]),
	.B(count[2]),
	.Y(n_7));
   NAND2X2 g1100 (.A(count[0]),
	.B(count[1]),
	.Y(n_10));
   NOR2X2 g1101 (.A(count[0]),
	.B(count[1]),
	.Y(n_9));
   CLKINVX1 g1102 (.A(count[3]),
	.Y(n_6));
   CLKINVX2 g1103 (.A(count[2]),
	.Y(n_5));
   INVX1 g1105 (.A(exit_sensor),
	.Y(n_3));
   CLKINVX1 g1109 (.A(count[4]),
	.Y(n_2));
   NAND2BX1 g2 (.AN(n_32),
	.B(n_0),
	.Y(n_1));
   NAND2BX1 g1110 (.AN(n_9),
	.B(n_10),
	.Y(n_0));
endmodule

module water_level_controller (
	rst_n, 
	water_level, 
	pump_on, 
	valve_close, 
	DFT_sdi, 
	DFT_sen, 
	visitor_count_int_7, 
	clk);
   input rst_n;
   input [3:0] water_level;
   output pump_on;
   output valve_close;
   input DFT_sdi;
   input DFT_sen;
   input visitor_count_int_7;
   input clk;

   // Internal wires
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_13;

   SDFFRHQX1 valve_close_reg (.CK(clk),
	.D(n_4),
	.Q(valve_close),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(visitor_count_int_7));
   NOR2XL g77 (.A(n_2),
	.B(n_3),
	.Y(n_4));
   AOI21X1 g79 (.A0(water_level[3]),
	.A1(water_level[2]),
	.B0(n_2),
	.Y(n_3));
   AOI211X1 g81 (.A0(water_level[1]),
	.A1(water_level[0]),
	.B0(water_level[3]),
	.C0(water_level[2]),
	.Y(n_2));
   SDFFRHQX1 pump_on_reg (.CK(clk),
	.D(n_13),
	.Q(pump_on),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(valve_close));
   MX2X1 g2 (.A(n_2),
	.B(pump_on),
	.S0(n_3),
	.Y(n_13));
endmodule

module window_treatment (
	clk, 
	rst_n, 
	auto_mode, 
	light_level, 
	manual_open, 
	manual_close, 
	window_state, 
	DFT_sdi, 
	DFT_sen, 
	SPCASCAN_N1, 
	clk_clone1);
   input clk;
   input rst_n;
   input auto_mode;
   input [7:0] light_level;
   input manual_open;
   input manual_close;
   output [1:0] window_state;
   input DFT_sdi;
   input DFT_sen;
   input SPCASCAN_N1;
   input clk_clone1;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;

   SDFFRHQX1 \window_state_reg[0]  (.CK(clk_clone1),
	.D(n_12),
	.Q(window_state[0]),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(DFT_sdi));
   AO22X1 g360 (.A0(auto_mode),
	.A1(n_11),
	.B0(n_2),
	.B1(window_state[0]),
	.Y(n_12));
   SDFFRHQX1 \window_state_reg[1]  (.CK(clk),
	.D(n_10),
	.Q(window_state[1]),
	.RN(rst_n),
	.SE(DFT_sen),
	.SI(SPCASCAN_N1));
   MXI2XL g362 (.A(n_7),
	.B(n_9),
	.S0(light_level[6]),
	.Y(n_11));
   OAI21X1 g363 (.A0(auto_mode),
	.A1(n_3),
	.B0(n_8),
	.Y(n_10));
   NOR2BXL g364 (.AN(light_level[7]),
	.B(n_6),
	.Y(n_9));
   NAND3BX1 g365 (.AN(light_level[6]),
	.B(auto_mode),
	.C(n_7),
	.Y(n_8));
   AOI31X1 g366 (.A0(light_level[5]),
	.A1(light_level[4]),
	.A2(n_4),
	.B0(light_level[7]),
	.Y(n_7));
   AOI211X1 g367 (.A0(light_level[3]),
	.A1(n_5),
	.B0(light_level[5]),
	.C0(light_level[4]),
	.Y(n_6));
   NAND2BX1 g368 (.AN(light_level[0]),
	.B(n_1),
	.Y(n_5));
   NAND2BXL g369 (.AN(light_level[3]),
	.B(n_1),
	.Y(n_4));
   AOI21X1 g370 (.A0(n_0),
	.A1(window_state[1]),
	.B0(manual_open),
	.Y(n_3));
   NOR3X1 g371 (.A(manual_open),
	.B(manual_close),
	.C(auto_mode),
	.Y(n_2));
   NOR2XL g372 (.A(light_level[2]),
	.B(light_level[1]),
	.Y(n_1));
   INVXL g373 (.A(manual_close),
	.Y(n_0));
endmodule

module HA (
	clk, 
	rst_n, 
	temp_sensor, 
	temp_setpoint, 
	water_level, 
	light_sensor, 
	motion_sensor, 
	door_sensor, 
	window_sensor, 
	alarm_arm, 
	entry_sensor, 
	exit_sensor, 
	window_auto_mode, 
	window_manual_open, 
	window_manual_close, 
	tv_on_cmd, 
	music_on_cmd, 
	volume_cmd, 
	ac_cmd, 
	fan_cmd, 
	light_cmd, 
	door_lock_cmd, 
	door_unlock_cmd, 
	pin_input, 
	humidity_sensor, 
	heater_on, 
	cooler_on, 
	water_pump_on, 
	water_valve_close, 
	led_brightness, 
	burglar_alarm_out, 
	visitor_count, 
	window_state, 
	tv_on, 
	music_on, 
	volume_level, 
	ac_on, 
	fan_on, 
	lights_on, 
	door_locked, 
	lock_status, 
	humidifier_on, 
	dehumidifier_on, 
	system_status, 
	scan_en, 
	test_mode, 
	DFT_sdi_1, 
	DFT_sdo_1, 
	DFT_sdi_2, 
	DFT_sdo_2);
   input clk;
   input rst_n;
   input [7:0] temp_sensor;
   input [7:0] temp_setpoint;
   input [3:0] water_level;
   input [7:0] light_sensor;
   input motion_sensor;
   input door_sensor;
   input window_sensor;
   input alarm_arm;
   input entry_sensor;
   input exit_sensor;
   input window_auto_mode;
   input window_manual_open;
   input window_manual_close;
   input tv_on_cmd;
   input music_on_cmd;
   input [3:0] volume_cmd;
   input ac_cmd;
   input fan_cmd;
   input light_cmd;
   input door_lock_cmd;
   input door_unlock_cmd;
   input [3:0] pin_input;
   input [7:0] humidity_sensor;
   output heater_on;
   output cooler_on;
   output water_pump_on;
   output water_valve_close;
   output [7:0] led_brightness;
   output burglar_alarm_out;
   output [7:0] visitor_count;
   output [1:0] window_state;
   output tv_on;
   output music_on;
   output [3:0] volume_level;
   output ac_on;
   output fan_on;
   output lights_on;
   output door_locked;
   output [1:0] lock_status;
   output humidifier_on;
   output dehumidifier_on;
   output [7:0] system_status;
   input scan_en;
   input test_mode;
   input DFT_sdi_1;
   output DFT_sdo_1;
   input DFT_sdi_2;
   output DFT_sdo_2;

   // Internal wires
   wire FE_OFN4_scan_en;
   wire FE_OFN3_scan_en;
   wire FE_OFN2_rst_n;
   wire FE_OFN1_rst_n;
   wire CTS_3;
   wire CTS_2;
   wire SPCASCAN_N5;
   wire SPCASCAN_N4;
   wire SPCASCAN_N3;
   wire SPCASCAN_N2;
   wire SPCASCAN_N1;
   wire SPCASCAN_N0;
   wire [3:0] pin_input_r;
   wire [1:0] lock_status_int;
   wire [3:0] volume_cmd_r;
   wire [3:0] volume_level_int;
   wire [7:0] humidity_sensor_r;
   wire [7:0] light_sensor_r;
   wire [7:0] led_brightness_int;
   wire [7:0] temp_sensor_r;
   wire [7:0] temp_setpoint_r;
   wire [7:0] visitor_count_int;
   wire [3:0] water_level_r;
   wire [1:0] window_state_int;
   wire ac_cmd_r;
   wire ac_on_int;
   wire ac_on_r_375;
   wire alarm_arm_r;
   wire burglar_alarm_out_int;
   wire burglar_alarm_out_r_372;
   wire cooler_on_int;
   wire cooler_on_r_369;
   wire dehumidifier_on_int;
   wire door_lock_cmd_r;
   wire door_locked_int;
   wire door_locked_r_378;
   wire door_sensor_r;
   wire door_unlock_cmd_r;
   wire entry_sensor_r;
   wire exit_sensor_r;
   wire fan_cmd_r;
   wire fan_on_int;
   wire fan_on_r_376;
   wire heater_on_int;
   wire heater_on_r_368;
   wire humidifier_on_int;
   wire light_cmd_r;
   wire lights_on_int;
   wire lights_on_r_377;
   wire motion_sensor_r;
   wire music_on_cmd_r;
   wire music_on_int;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire tv_on_cmd_r;
   wire tv_on_int;
   wire water_pump_on_int;
   wire water_pump_on_r_370;
   wire water_valve_close_int;
   wire window_auto_mode_r;
   wire window_manual_close_r;
   wire window_manual_open_r;
   wire window_sensor_r;

   assign DFT_sdo_2 = window_state[1] ;

   BUFX2 FE_OFC6_scan_en (.A(FE_OFN3_scan_en),
	.Y(FE_OFN4_scan_en));
   CLKBUFX4 FE_OFC5_scan_en (.A(scan_en),
	.Y(FE_OFN3_scan_en));
   BUFX3 FE_OFC4_rst_n (.A(rst_n),
	.Y(FE_OFN2_rst_n));
   BUFX2 FE_OFC3_rst_n (.A(rst_n),
	.Y(FE_OFN1_rst_n));
   CLKBUFX16 CTS_ccl_a_buf_00006 (.A(clk),
	.Y(CTS_3));
   CLKBUFX16 CTS_ccl_a_buf_00004 (.A(clk),
	.Y(CTS_2));
   appliances_controller u_appliances (.rst_n(rst_n),
	.ac_cmd(ac_cmd_r),
	.fan_cmd(fan_cmd_r),
	.light_cmd(light_cmd_r),
	.ac_on(ac_on_int),
	.fan_on(fan_on_int),
	.lights_on(lights_on_int),
	.DFT_sdi(DFT_sdi_1),
	.DFT_sen(FE_OFN3_scan_en),
	.led_brightness_int_0(led_brightness_int[0]),
	.clk(CTS_2),
	.FE_OFN0_rst_n(FE_OFN1_rst_n));
   burglar_alarm u_burglar (.rst_n(rst_n),
	.motion_sensor(motion_sensor_r),
	.door_sensor(door_sensor_r),
	.window_sensor(window_sensor_r),
	.alarm_arm(alarm_arm_r),
	.alarm_out(burglar_alarm_out_int),
	.DFT_sdi(lights_on_int),
	.DFT_sen(scan_en),
	.DFT_sdo(n_88),
	.delay_counter_3(SPCASCAN_N1),
	.SPCASCAN_N2(SPCASCAN_N2),
	.clk_clone1(CTS_2),
	.clk(CTS_3),
	.FE_OFN5_scan_en(FE_OFN3_scan_en));
   door_lock_controller u_door_lock (.rst_n(rst_n),
	.lock_cmd(door_lock_cmd_r),
	.unlock_cmd(door_unlock_cmd_r),
	.pin_input(pin_input_r),
	.door_locked(door_locked_int),
	.lock_status(lock_status_int),
	.DFT_sdi(burglar_alarm_out_int),
	.DFT_sen(scan_en),
	.DFT_sdo(n_89),
	.attempt_counter_0(SPCASCAN_N0),
	.timeout_counter_0(SPCASCAN_N3),
	.p_1(n_4),
	.humidifier_on_int(humidifier_on_int),
	.timeout_counter_1(SPCASCAN_N4),
	.tv_on_int(tv_on_int),
	.water_pump_on_int(water_pump_on_int),
	.timeout_counter_5(SPCASCAN_N5),
	.n_91(n_91),
	.clk_clone1(CTS_2),
	.clk(CTS_3),
	.FE_OFN1_rst_n(FE_OFN2_rst_n),
	.FE_OFN6_scan_en(FE_OFN3_scan_en));
   entertainment_system u_entertainment (.rst_n(FE_OFN2_rst_n),
	.tv_on_cmd(tv_on_cmd_r),
	.music_on_cmd(music_on_cmd_r),
	.volume_cmd(volume_cmd_r),
	.tv_on(tv_on_int),
	.music_on(music_on_int),
	.volume_level(volume_level_int),
	.DFT_sdi(dehumidifier_on_int),
	.DFT_sen(scan_en),
	.lock_status_int_1(lock_status_int[1]),
	.dehumidifier_on(dehumidifier_on),
	.clk(CTS_3));
   humidity_controller u_humidity (.rst_n(FE_OFN2_rst_n),
	.humidity_sensor({ humidity_sensor_r[7],
		humidity_sensor_r[6],
		humidity_sensor_r[5],
		humidity_sensor_r[4],
		humidity_sensor_r[3],
		humidity_sensor_r[2],
		DFT_sdo_1,
		humidity_sensor_r[0] }),
	.humidifier_on(humidifier_on_int),
	.dehumidifier_on(dehumidifier_on_int),
	.DFT_sdi(volume_level_int[0]),
	.DFT_sen(scan_en),
	.SPCASCAN_N4(SPCASCAN_N4),
	.clk(CTS_3));
   luminosity_controller u_lum_ctrl (.rst_n(FE_OFN1_rst_n),
	.light_sensor(light_sensor_r),
	.led_brightness(led_brightness_int),
	.DFT_sdi(n_5),
	.DFT_sen(scan_en),
	.p_1(n_1),
	.visitor_count_int_3(visitor_count_int[3]),
	.clk(CTS_2),
	.FE_OFN3_scan_en(FE_OFN3_scan_en));
   temperature_controller u_temp_ctrl (.rst_n(rst_n),
	.temp_sensor(temp_sensor_r),
	.temp_setpoint(temp_setpoint_r),
	.heater_on(heater_on_int),
	.cooler_on(cooler_on_int),
	.DFT_sdi(led_brightness_int[7]),
	.DFT_sen(scan_en),
	.DFT_sdo(n_90),
	.n_1(SPCASCAN_N2),
	.SPCASCAN_N3(SPCASCAN_N3),
	.clk(CTS_3));
   visitor_counter u_visitor (.rst_n(FE_OFN1_rst_n),
	.entry_sensor(entry_sensor_r),
	.exit_sensor(exit_sensor_r),
	.count(visitor_count_int),
	.DFT_sdi(volume_level_int[2]),
	.DFT_sen(scan_en),
	.DFT_sdo(n_91),
	.SPCASCAN_N5(SPCASCAN_N5),
	.led_brightness_int_7(led_brightness_int[7]),
	.clk_clone1(CTS_2),
	.clk(CTS_3),
	.FE_OFN2_rst_n(FE_OFN2_rst_n),
	.FE_OFN7_scan_en(FE_OFN4_scan_en),
	.FE_OFN4_scan_en(FE_OFN3_scan_en));
   water_level_controller u_water_ctrl (.rst_n(FE_OFN2_rst_n),
	.water_level(water_level_r),
	.pump_on(water_pump_on_int),
	.valve_close(water_valve_close_int),
	.DFT_sdi(n_91),
	.DFT_sen(scan_en),
	.visitor_count_int_7(visitor_count_int[7]),
	.clk(CTS_3));
   window_treatment u_window (.clk(CTS_3),
	.rst_n(rst_n),
	.auto_mode(window_auto_mode_r),
	.light_level(light_sensor_r),
	.manual_open(window_manual_open_r),
	.manual_close(window_manual_close_r),
	.window_state(window_state_int),
	.DFT_sdi(SPCASCAN_N0),
	.DFT_sen(FE_OFN3_scan_en),
	.SPCASCAN_N1(SPCASCAN_N1),
	.clk_clone1(CTS_2));
   SDFFRHQX1 water_valve_close_r_reg (.CK(CTS_3),
	.D(water_valve_close_int),
	.Q(water_valve_close),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(n_3));
   SDFFRHQX1 tv_on_r_reg (.CK(CTS_3),
	.D(tv_on_int),
	.Q(tv_on),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(music_on));
   SDFFRHQX1 music_on_r_reg (.CK(CTS_3),
	.D(music_on_int),
	.Q(music_on),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(window_state[0]));
   CLKINVX1 g44 (.A(lights_on_r_377),
	.Y(lights_on));
   CLKINVX1 g45 (.A(lights_on_r_377),
	.Y(system_status[2]));
   CLKINVX1 g74 (.A(ac_on_r_375),
	.Y(ac_on));
   CLKINVX1 g75 (.A(ac_on_r_375),
	.Y(system_status[4]));
   CLKINVX1 g76 (.A(fan_on_r_376),
	.Y(fan_on));
   CLKINVX1 g77 (.A(fan_on_r_376),
	.Y(system_status[3]));
   SDFFRHQX1 \led_brightness_r_reg[2]  (.CK(CTS_2),
	.D(led_brightness_int[2]),
	.Q(led_brightness[2]),
	.RN(FE_OFN1_rst_n),
	.SE(FE_OFN4_scan_en),
	.SI(led_brightness[1]));
   SDFFRHQX1 \led_brightness_r_reg[7]  (.CK(CTS_2),
	.D(led_brightness_int[7]),
	.Q(led_brightness[7]),
	.RN(FE_OFN1_rst_n),
	.SE(FE_OFN4_scan_en),
	.SI(led_brightness[6]));
   SDFFRHQX1 \led_brightness_r_reg[3]  (.CK(CTS_2),
	.D(led_brightness_int[3]),
	.Q(led_brightness[3]),
	.RN(FE_OFN1_rst_n),
	.SE(FE_OFN4_scan_en),
	.SI(led_brightness[2]));
   SDFFRHQX1 humidifier_on_r_reg (.CK(CTS_3),
	.D(humidifier_on_int),
	.Q(humidifier_on),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(DFT_sdi_1));
   SDFFRHQX1 dehumidifier_on_r_reg (.CK(CTS_3),
	.D(dehumidifier_on_int),
	.Q(dehumidifier_on),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(humidifier_on));
   SDFFRX1 lights_on_r_reg (.CK(CTS_2),
	.D(lights_on_int),
	.Q(n_7),
	.QN(lights_on_r_377),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(pin_input_r[3]));
   SDFFRHQX1 \led_brightness_r_reg[1]  (.CK(CTS_2),
	.D(led_brightness_int[1]),
	.Q(led_brightness[1]),
	.RN(FE_OFN1_rst_n),
	.SE(FE_OFN4_scan_en),
	.SI(led_brightness[0]));
   SDFFRHQX1 \led_brightness_r_reg[0]  (.CK(CTS_2),
	.D(led_brightness_int[0]),
	.Q(led_brightness[0]),
	.RN(FE_OFN1_rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(n_7));
   SDFFRHQX1 \led_brightness_r_reg[6]  (.CK(CTS_2),
	.D(led_brightness_int[6]),
	.Q(led_brightness[6]),
	.RN(FE_OFN1_rst_n),
	.SE(FE_OFN4_scan_en),
	.SI(led_brightness[5]));
   SDFFRHQX1 \led_brightness_r_reg[5]  (.CK(CTS_2),
	.D(led_brightness_int[5]),
	.Q(led_brightness[5]),
	.RN(FE_OFN1_rst_n),
	.SE(FE_OFN4_scan_en),
	.SI(led_brightness[4]));
   SDFFRHQX1 \led_brightness_r_reg[4]  (.CK(CTS_2),
	.D(led_brightness_int[4]),
	.Q(led_brightness[4]),
	.RN(FE_OFN1_rst_n),
	.SE(FE_OFN4_scan_en),
	.SI(led_brightness[3]));
   SDFFRX1 ac_on_r_reg (.CK(CTS_2),
	.D(ac_on_int),
	.Q(n_6),
	.QN(ac_on_r_375),
	.RN(FE_OFN1_rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(led_brightness_int[1]));
   SDFFRX1 fan_on_r_reg (.CK(CTS_2),
	.D(fan_on_int),
	.Q(n_5),
	.QN(fan_on_r_376),
	.RN(FE_OFN1_rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(n_6));
   CLKINVX1 g46 (.A(door_locked_r_378),
	.Y(door_locked));
   CLKINVX1 g47 (.A(door_locked_r_378),
	.Y(system_status[5]));
   SDFFRHQX1 \lock_status_r_reg[0]  (.CK(CTS_3),
	.D(lock_status_int[0]),
	.Q(lock_status[0]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(volume_level[3]));
   SDFFRHQX1 \lock_status_r_reg[1]  (.CK(CTS_3),
	.D(lock_status_int[1]),
	.Q(lock_status[1]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(lock_status[0]));
   SDFFRX1 door_locked_r_reg (.CK(CTS_3),
	.D(door_locked_int),
	.Q(n_4),
	.QN(door_locked_r_378),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(door_locked_int));
   CLKINVX1 g72 (.A(water_pump_on_r_370),
	.Y(water_pump_on));
   CLKINVX1 g73 (.A(water_pump_on_r_370),
	.Y(system_status[6]));
   CLKINVX1 g48 (.A(heater_on_r_368),
	.Y(heater_on));
   SDFFRHQX1 \volume_level_r_reg[2]  (.CK(CTS_3),
	.D(volume_level_int[2]),
	.Q(volume_level[2]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(volume_level[1]));
   SDFFRHQX1 \volume_level_r_reg[3]  (.CK(CTS_3),
	.D(volume_level_int[3]),
	.Q(volume_level[3]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(volume_level[2]));
   SDFFRHQX1 \volume_level_r_reg[1]  (.CK(CTS_3),
	.D(volume_level_int[1]),
	.Q(volume_level[1]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(volume_level[0]));
   SDFFRHQX1 \volume_level_r_reg[0]  (.CK(CTS_3),
	.D(volume_level_int[0]),
	.Q(volume_level[0]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(water_valve_close));
   CLKINVX1 g49 (.A(heater_on_r_368),
	.Y(system_status[1]));
   CLKINVX1 g50 (.A(cooler_on_r_369),
	.Y(cooler_on));
   CLKINVX1 g51 (.A(cooler_on_r_369),
	.Y(system_status[0]));
   CLKINVX1 g70 (.A(burglar_alarm_out_r_372),
	.Y(burglar_alarm_out));
   CLKINVX1 g71 (.A(burglar_alarm_out_r_372),
	.Y(system_status[7]));
   SDFFRX1 water_pump_on_r_reg (.CK(CTS_3),
	.D(water_pump_on_int),
	.Q(n_3),
	.QN(water_pump_on_r_370),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(visitor_count[7]));
   SDFFRHQX4 \pin_input_r_reg[3]  (.CK(CTS_2),
	.D(pin_input[3]),
	.Q(pin_input_r[3]),
	.RN(FE_OFN1_rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(DFT_sdi_2));
   SDFFRHQX4 ac_cmd_r_reg (.CK(CTS_2),
	.D(ac_cmd),
	.Q(ac_cmd_r),
	.RN(FE_OFN1_rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(door_lock_cmd_r));
   SDFFRHQX1 \visitor_count_r_reg[1]  (.CK(CTS_2),
	.D(visitor_count_int[1]),
	.Q(visitor_count[1]),
	.RN(FE_OFN1_rst_n),
	.SE(scan_en),
	.SI(visitor_count[0]));
   SDFFRHQX1 \visitor_count_r_reg[5]  (.CK(CTS_2),
	.D(visitor_count_int[5]),
	.Q(visitor_count[5]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(visitor_count[4]));
   SDFFRHQX1 \visitor_count_r_reg[4]  (.CK(CTS_2),
	.D(visitor_count_int[4]),
	.Q(visitor_count[4]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(visitor_count[3]));
   SDFFRHQX1 \visitor_count_r_reg[2]  (.CK(CTS_2),
	.D(visitor_count_int[2]),
	.Q(visitor_count[2]),
	.RN(FE_OFN1_rst_n),
	.SE(FE_OFN4_scan_en),
	.SI(visitor_count[1]));
   SDFFRHQX1 \visitor_count_r_reg[3]  (.CK(CTS_2),
	.D(visitor_count_int[3]),
	.Q(visitor_count[3]),
	.RN(FE_OFN2_rst_n),
	.SE(FE_OFN4_scan_en),
	.SI(visitor_count[2]));
   SDFFRHQX1 \window_state_r_reg[1]  (.CK(CTS_3),
	.D(window_state_int[1]),
	.Q(window_state[1]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(tv_on));
   SDFFRHQX1 \visitor_count_r_reg[0]  (.CK(CTS_2),
	.D(visitor_count_int[0]),
	.Q(visitor_count[0]),
	.RN(FE_OFN1_rst_n),
	.SE(FE_OFN4_scan_en),
	.SI(led_brightness[7]));
   SDFFRHQX1 \window_state_r_reg[0]  (.CK(CTS_2),
	.D(window_state_int[0]),
	.Q(window_state[0]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(humidity_sensor_r[7]));
   SDFFRHQX1 \visitor_count_r_reg[7]  (.CK(CTS_2),
	.D(visitor_count_int[7]),
	.Q(visitor_count[7]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(visitor_count[6]));
   SDFFRHQX1 \visitor_count_r_reg[6]  (.CK(CTS_2),
	.D(visitor_count_int[6]),
	.Q(visitor_count[6]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(visitor_count[5]));
   SDFFRHQX4 window_manual_open_r_reg (.CK(CTS_3),
	.D(window_manual_open),
	.Q(window_manual_open_r),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(window_auto_mode_r));
   SDFFRHQX4 motion_sensor_r_reg (.CK(CTS_3),
	.D(motion_sensor),
	.Q(motion_sensor_r),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(window_sensor_r));
   SDFFRHQX4 \temp_sensor_r_reg[0]  (.CK(CTS_3),
	.D(temp_sensor[0]),
	.Q(temp_sensor_r[0]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(temp_sensor_r[1]));
   SDFFRHQX4 \temp_sensor_r_reg[1]  (.CK(CTS_3),
	.D(temp_sensor[1]),
	.Q(temp_sensor_r[1]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(temp_sensor_r[2]));
   SDFFRHQX4 \temp_sensor_r_reg[2]  (.CK(CTS_3),
	.D(temp_sensor[2]),
	.Q(temp_sensor_r[2]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(temp_sensor_r[3]));
   SDFFRHQX4 \temp_sensor_r_reg[3]  (.CK(CTS_3),
	.D(temp_sensor[3]),
	.Q(temp_sensor_r[3]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(temp_setpoint_r[0]));
   SDFFRHQX4 \temp_sensor_r_reg[4]  (.CK(CTS_3),
	.D(temp_sensor[4]),
	.Q(temp_sensor_r[4]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(music_on_cmd_r));
   SDFFRHQX4 \temp_sensor_r_reg[5]  (.CK(CTS_3),
	.D(temp_sensor[5]),
	.Q(temp_sensor_r[5]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(temp_sensor_r[4]));
   SDFFRHQX4 \pin_input_r_reg[0]  (.CK(CTS_2),
	.D(pin_input[0]),
	.Q(pin_input_r[0]),
	.RN(FE_OFN1_rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(light_cmd_r));
   SDFFRHQX4 \temp_sensor_r_reg[7]  (.CK(CTS_3),
	.D(temp_sensor[7]),
	.Q(temp_sensor_r[7]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(temp_setpoint_r[1]));
   SDFFRHQX4 \temp_setpoint_r_reg[7]  (.CK(CTS_3),
	.D(temp_setpoint[7]),
	.Q(temp_setpoint_r[7]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(water_level_r[0]));
   SDFFRHQX4 \temp_setpoint_r_reg[0]  (.CK(CTS_3),
	.D(temp_setpoint[0]),
	.Q(temp_setpoint_r[0]),
	.RN(FE_OFN2_rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(temp_sensor_r[6]));
   SDFFRHQX4 \temp_setpoint_r_reg[2]  (.CK(CTS_3),
	.D(temp_setpoint[2]),
	.Q(temp_setpoint_r[2]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(temp_setpoint_r[3]));
   SDFFRHQX4 \temp_setpoint_r_reg[3]  (.CK(CTS_3),
	.D(temp_setpoint[3]),
	.Q(temp_setpoint_r[3]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(temp_setpoint_r[4]));
   SDFFRHQX4 \temp_setpoint_r_reg[4]  (.CK(CTS_3),
	.D(temp_setpoint[4]),
	.Q(temp_setpoint_r[4]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(temp_setpoint_r[5]));
   SDFFRHQX4 \temp_setpoint_r_reg[6]  (.CK(CTS_3),
	.D(temp_setpoint[6]),
	.Q(temp_setpoint_r[6]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(temp_setpoint_r[7]));
   SDFFRHQX4 window_sensor_r_reg (.CK(CTS_3),
	.D(window_sensor),
	.Q(window_sensor_r),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(volume_cmd_r[0]));
   SDFFRHQX4 window_auto_mode_r_reg (.CK(CTS_3),
	.D(window_auto_mode),
	.Q(window_auto_mode_r),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(motion_sensor_r));
   SDFFRHQX4 alarm_arm_r_reg (.CK(CTS_3),
	.D(alarm_arm),
	.Q(alarm_arm_r),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(window_state_int[1]));
   SDFFRHQX4 door_sensor_r_reg (.CK(CTS_3),
	.D(door_sensor),
	.Q(door_sensor_r),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(alarm_arm_r));
   SDFFRHQX4 entry_sensor_r_reg (.CK(CTS_2),
	.D(entry_sensor),
	.Q(entry_sensor_r),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(lights_on_int));
   SDFFRHQX4 exit_sensor_r_reg (.CK(CTS_2),
	.D(exit_sensor),
	.Q(exit_sensor_r),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(door_unlock_cmd_r));
   SDFFRHQX4 \humidity_sensor_r_reg[3]  (.CK(CTS_2),
	.D(humidity_sensor[3]),
	.Q(humidity_sensor_r[3]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(humidity_sensor_r[2]));
   SDFFRHQX4 \pin_input_r_reg[2]  (.CK(CTS_2),
	.D(pin_input[2]),
	.Q(pin_input_r[2]),
	.RN(FE_OFN1_rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(pin_input_r[1]));
   SDFFRHQX4 \pin_input_r_reg[1]  (.CK(CTS_2),
	.D(pin_input[1]),
	.Q(pin_input_r[1]),
	.RN(FE_OFN1_rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(pin_input_r[0]));
   SDFFRX1 heater_on_r_reg (.CK(CTS_2),
	.D(heater_on_int),
	.Q(n_2),
	.QN(heater_on_r_368),
	.RN(FE_OFN1_rst_n),
	.SE(scan_en),
	.SI(n_0));
   SDFFRHQX4 \volume_cmd_r_reg[0]  (.CK(CTS_3),
	.D(volume_cmd[0]),
	.Q(volume_cmd_r[0]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(volume_cmd_r[3]));
   SDFFRHQX4 \volume_cmd_r_reg[1]  (.CK(CTS_3),
	.D(volume_cmd[1]),
	.Q(volume_cmd_r[1]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(temp_sensor_r[0]));
   SDFFRHQX4 door_unlock_cmd_r_reg (.CK(CTS_2),
	.D(door_unlock_cmd),
	.Q(door_unlock_cmd_r),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(entry_sensor_r));
   SDFFRHQX4 window_manual_close_r_reg (.CK(CTS_3),
	.D(window_manual_close),
	.Q(window_manual_close_r),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(window_manual_open_r));
   SDFFRHQX4 \volume_cmd_r_reg[2]  (.CK(CTS_3),
	.D(volume_cmd[2]),
	.Q(volume_cmd_r[2]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(volume_cmd_r[1]));
   SDFFRHQX4 door_lock_cmd_r_reg (.CK(CTS_2),
	.D(door_lock_cmd),
	.Q(door_lock_cmd_r),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(exit_sensor_r));
   SDFFRHQX4 \humidity_sensor_r_reg[6]  (.CK(CTS_3),
	.D(humidity_sensor[6]),
	.Q(humidity_sensor_r[6]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(humidity_sensor_r[4]));
   SDFFRHQX4 light_cmd_r_reg (.CK(CTS_2),
	.D(light_cmd),
	.Q(light_cmd_r),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(temp_sensor_r[5]));
   SDFFRHQX4 \humidity_sensor_r_reg[0]  (.CK(CTS_2),
	.D(humidity_sensor[0]),
	.Q(humidity_sensor_r[0]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(window_state_int[0]));
   SDFFRHQX4 \volume_cmd_r_reg[3]  (.CK(CTS_3),
	.D(volume_cmd[3]),
	.Q(volume_cmd_r[3]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(volume_cmd_r[2]));
   SDFFRHQX4 \temp_setpoint_r_reg[1]  (.CK(CTS_3),
	.D(temp_setpoint[1]),
	.Q(temp_setpoint_r[1]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(temp_setpoint_r[2]));
   SDFFRHQX4 \temp_setpoint_r_reg[5]  (.CK(CTS_3),
	.D(temp_setpoint[5]),
	.Q(temp_setpoint_r[5]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(temp_setpoint_r[6]));
   SDFFRHQX4 \water_level_r_reg[0]  (.CK(CTS_3),
	.D(water_level[0]),
	.Q(water_level_r[0]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(water_level_r[1]));
   SDFFRHQX4 \temp_sensor_r_reg[6]  (.CK(CTS_3),
	.D(temp_sensor[6]),
	.Q(temp_sensor_r[6]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(temp_sensor_r[7]));
   SDFFRHQX4 fan_cmd_r_reg (.CK(CTS_2),
	.D(fan_cmd),
	.Q(fan_cmd_r),
	.RN(FE_OFN1_rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(ac_cmd_r));
   SDFFRHQX4 \humidity_sensor_r_reg[1]  (.CK(CTS_2),
	.D(humidity_sensor[1]),
	.Q(DFT_sdo_1),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(humidity_sensor_r[0]));
   SDFFRHQX4 \humidity_sensor_r_reg[2]  (.CK(CTS_2),
	.D(humidity_sensor[2]),
	.Q(humidity_sensor_r[2]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(light_sensor_r[7]));
   SDFFRHQX4 \humidity_sensor_r_reg[4]  (.CK(CTS_3),
	.D(humidity_sensor[4]),
	.Q(humidity_sensor_r[4]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(humidity_sensor_r[5]));
   SDFFRHQX4 \humidity_sensor_r_reg[5]  (.CK(CTS_3),
	.D(humidity_sensor[5]),
	.Q(humidity_sensor_r[5]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(humidity_sensor_r[3]));
   SDFFRHQX4 \humidity_sensor_r_reg[7]  (.CK(CTS_2),
	.D(humidity_sensor[7]),
	.Q(humidity_sensor_r[7]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(humidity_sensor_r[6]));
   SDFFRHQX4 music_on_cmd_r_reg (.CK(CTS_3),
	.D(music_on_cmd),
	.Q(music_on_cmd_r),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(tv_on_cmd_r));
   SDFFRHQX4 tv_on_cmd_r_reg (.CK(CTS_3),
	.D(tv_on_cmd),
	.Q(tv_on_cmd_r),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(window_manual_close_r));
   SDFFRHQX4 \water_level_r_reg[3]  (.CK(CTS_3),
	.D(water_level[3]),
	.Q(water_level_r[3]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(lock_status[1]));
   SDFFRHQX4 \water_level_r_reg[1]  (.CK(CTS_3),
	.D(water_level[1]),
	.Q(water_level_r[1]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(water_level_r[2]));
   SDFFRHQX4 \water_level_r_reg[2]  (.CK(CTS_3),
	.D(water_level[2]),
	.Q(water_level_r[2]),
	.RN(FE_OFN2_rst_n),
	.SE(scan_en),
	.SI(water_level_r[3]));
   SDFFRX1 burglar_alarm_out_r_reg (.CK(CTS_2),
	.D(burglar_alarm_out_int),
	.Q(n_1),
	.QN(burglar_alarm_out_r_372),
	.RN(FE_OFN1_rst_n),
	.SE(scan_en),
	.SI(n_2));
   SDFFRHQX4 \light_sensor_r_reg[5]  (.CK(CTS_2),
	.D(light_sensor[5]),
	.Q(light_sensor_r[5]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(light_sensor_r[4]));
   SDFFRHQX4 \light_sensor_r_reg[6]  (.CK(CTS_2),
	.D(light_sensor[6]),
	.Q(light_sensor_r[6]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(light_sensor_r[5]));
   SDFFRHQX4 \light_sensor_r_reg[4]  (.CK(CTS_2),
	.D(light_sensor[4]),
	.Q(light_sensor_r[4]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(light_sensor_r[3]));
   SDFFRHQX4 \light_sensor_r_reg[3]  (.CK(CTS_2),
	.D(light_sensor[3]),
	.Q(light_sensor_r[3]),
	.RN(FE_OFN1_rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(light_sensor_r[2]));
   SDFFRX1 cooler_on_r_reg (.CK(CTS_2),
	.D(cooler_on_int),
	.Q(n_0),
	.QN(cooler_on_r_369),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(ac_on_int));
   SDFFRHQX4 \light_sensor_r_reg[1]  (.CK(CTS_2),
	.D(light_sensor[1]),
	.Q(light_sensor_r[1]),
	.RN(FE_OFN1_rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(pin_input_r[2]));
   SDFFRHQX4 \light_sensor_r_reg[2]  (.CK(CTS_2),
	.D(light_sensor[2]),
	.Q(light_sensor_r[2]),
	.RN(FE_OFN1_rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(light_sensor_r[0]));
   SDFFRHQX4 \light_sensor_r_reg[7]  (.CK(CTS_2),
	.D(light_sensor[7]),
	.Q(light_sensor_r[7]),
	.RN(rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(light_sensor_r[6]));
   SDFFRHQX4 \light_sensor_r_reg[0]  (.CK(CTS_2),
	.D(light_sensor[0]),
	.Q(light_sensor_r[0]),
	.RN(FE_OFN1_rst_n),
	.SE(FE_OFN3_scan_en),
	.SI(light_sensor_r[1]));
endmodule

