// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Nov  7 2025 23:22:38 IST (Nov  7 2025 17:52:38 UTC)

// Verification Directory fv/HA 

module appliances_controller(clk, rst_n, ac_cmd, fan_cmd, light_cmd,
     ac_on, fan_on, lights_on, DFT_sdi, DFT_sen);
  input clk, rst_n, ac_cmd, fan_cmd, light_cmd, DFT_sdi, DFT_sen;
  output ac_on, fan_on, lights_on;
  wire clk, rst_n, ac_cmd, fan_cmd, light_cmd, DFT_sdi, DFT_sen;
  wire ac_on, fan_on, lights_on;
  SDFFRHQX1 ac_on_reg(.RN (rst_n), .CK (clk), .D (ac_cmd), .SI
       (DFT_sdi), .SE (DFT_sen), .Q (ac_on));
  SDFFRHQX1 fan_on_reg(.RN (rst_n), .CK (clk), .D (fan_cmd), .SI
       (ac_on), .SE (DFT_sen), .Q (fan_on));
  SDFFRHQX1 lights_on_reg(.RN (rst_n), .CK (clk), .D (light_cmd), .SI
       (fan_on), .SE (DFT_sen), .Q (lights_on));
endmodule

module burglar_alarm(clk, rst_n, motion_sensor, door_sensor,
     window_sensor, alarm_arm, alarm_out, DFT_sdi, DFT_sen, DFT_sdo);
  input clk, rst_n, motion_sensor, door_sensor, window_sensor,
       alarm_arm, DFT_sdi, DFT_sen;
  output alarm_out, DFT_sdo;
  wire clk, rst_n, motion_sensor, door_sensor, window_sensor,
       alarm_arm, DFT_sdi, DFT_sen;
  wire alarm_out, DFT_sdo;
  wire [8:0] delay_counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_29, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_39, n_46, n_47;
  SDFFRHQX1 \delay_counter_reg[6] (.RN (rst_n), .CK (clk), .D (n_39),
       .SI (delay_counter[5]), .SE (DFT_sen), .Q (delay_counter[6]));
  OAI21X1 g671(.A0 (n_12), .A1 (n_36), .B0 (n_14), .Y (n_39));
  SDFFRHQX1 \delay_counter_reg[5] (.RN (rst_n), .CK (clk), .D (n_47),
       .SI (delay_counter[4]), .SE (DFT_sen), .Q (delay_counter[5]));
  SDFFRHQX1 \delay_counter_reg[7] (.RN (rst_n), .CK (clk), .D (n_37),
       .SI (delay_counter[6]), .SE (DFT_sen), .Q (delay_counter[7]));
  OAI21X1 g675(.A0 (n_12), .A1 (n_34), .B0 (n_14), .Y (n_37));
  AOI21X1 g676(.A0 (delay_counter[6]), .A1 (n_29), .B0 (n_35), .Y
       (n_36));
  SDFFRHQX1 \delay_counter_reg[3] (.RN (rst_n), .CK (clk), .D (n_33),
       .SI (delay_counter[2]), .SE (DFT_sen), .Q (delay_counter[3]));
  NOR2XL g678(.A (delay_counter[6]), .B (n_29), .Y (n_35));
  SDFFRHQX1 \delay_counter_reg[4] (.RN (rst_n), .CK (clk), .D (n_31),
       .SI (delay_counter[3]), .SE (DFT_sen), .Q (delay_counter[4]));
  AOI21X1 g680(.A0 (delay_counter[7]), .A1 (n_26), .B0 (n_32), .Y
       (n_34));
  OAI22X1 g681(.A0 (n_25), .A1 (n_12), .B0 (n_1), .B1 (n_14), .Y
       (n_33));
  SDFFRHQX1 \delay_counter_reg[8] (.RN (rst_n), .CK (clk), .D (n_27),
       .SI (delay_counter[7]), .SE (DFT_sen), .Q (DFT_sdo));
  SDFFRHQX1 \delay_counter_reg[2] (.RN (rst_n), .CK (clk), .D (n_24),
       .SI (delay_counter[1]), .SE (DFT_sen), .Q (delay_counter[2]));
  NOR2XL g684(.A (delay_counter[7]), .B (n_26), .Y (n_32));
  OAI21X1 g685(.A0 (n_21), .A1 (n_12), .B0 (n_14), .Y (n_31));
  NAND2XL g688(.A (n_14), .B (n_23), .Y (n_27));
  NAND2BX1 g689(.AN (n_18), .B (delay_counter[5]), .Y (n_29));
  MXI2XL g690(.A (delay_counter[3]), .B (n_1), .S0 (n_10), .Y (n_25));
  OAI22X1 g691(.A0 (n_15), .A1 (n_12), .B0 (n_2), .B1 (n_14), .Y
       (n_24));
  NAND3BX1 g692(.AN (n_18), .B (delay_counter[5]), .C
       (delay_counter[6]), .Y (n_26));
  SDFFRHQX1 alarm_out_reg(.RN (rst_n), .CK (clk), .D (n_22), .SI
       (DFT_sdi), .SE (DFT_sen), .Q (alarm_out));
  SDFFRHQX1 \delay_counter_reg[1] (.RN (rst_n), .CK (clk), .D (n_20),
       .SI (delay_counter[0]), .SE (DFT_sen), .Q (delay_counter[1]));
  OAI21XL g695(.A0 (n_16), .A1 (DFT_sdo), .B0 (n_0), .Y (n_23));
  SDFFRHQX1 \delay_counter_reg[0] (.RN (rst_n), .CK (clk), .D (n_19),
       .SI (alarm_out), .SE (DFT_sen), .Q (delay_counter[0]));
  OAI2BB1XL g697(.A0N (alarm_out), .A1N (n_0), .B0 (n_14), .Y (n_22));
  AOI21X1 g698(.A0 (delay_counter[4]), .A1 (n_11), .B0 (n_17), .Y
       (n_21));
  AO22X1 g699(.A0 (n_5), .A1 (n_0), .B0 (delay_counter[1]), .B1 (n_13),
       .Y (n_20));
  MXI2XL g700(.A (n_12), .B (n_14), .S0 (delay_counter[0]), .Y (n_19));
  NOR2XL g701(.A (delay_counter[4]), .B (n_11), .Y (n_17));
  NAND2BX1 g702(.AN (n_11), .B (delay_counter[4]), .Y (n_18));
  NOR2XL g703(.A (n_11), .B (n_6), .Y (n_16));
  MXI2XL g704(.A (n_2), .B (delay_counter[2]), .S0 (n_3), .Y (n_15));
  CLKINVX1 g705(.A (n_13), .Y (n_14));
  CLKINVX1 g706(.A (n_0), .Y (n_12));
  NOR2XL g707(.A (n_9), .B (n_8), .Y (n_13));
  NOR2XL g709(.A (n_2), .B (n_3), .Y (n_10));
  OR2X1 g710(.A (n_4), .B (n_3), .Y (n_11));
  OAI31X1 g711(.A0 (window_sensor), .A1 (motion_sensor), .A2
       (door_sensor), .B0 (alarm_arm), .Y (n_9));
  OAI211X1 g713(.A0 (delay_counter[2]), .A1 (delay_counter[3]), .B0
       (DFT_sdo), .C0 (n_7), .Y (n_8));
  INVX1 g714(.A (n_6), .Y (n_7));
  NAND4XL g715(.A (delay_counter[6]), .B (delay_counter[4]), .C
       (delay_counter[5]), .D (delay_counter[7]), .Y (n_6));
  XOR2XL g716(.A (delay_counter[0]), .B (delay_counter[1]), .Y (n_5));
  NAND2XL g717(.A (delay_counter[2]), .B (delay_counter[3]), .Y (n_4));
  NAND2XL g718(.A (delay_counter[0]), .B (delay_counter[1]), .Y (n_3));
  INVX1 g719(.A (delay_counter[2]), .Y (n_2));
  CLKINVX1 g720(.A (delay_counter[3]), .Y (n_1));
  NOR2BX1 g2(.AN (n_8), .B (n_9), .Y (n_0));
  OAI21X1 g721(.A0 (n_46), .A1 (n_12), .B0 (n_14), .Y (n_47));
  CLKXOR2X1 g3(.A (delay_counter[5]), .B (n_18), .Y (n_46));
endmodule

module door_lock_controller(clk, rst_n, lock_cmd, unlock_cmd,
     pin_input, door_locked, lock_status, DFT_sdi, DFT_sen, DFT_sdo);
  input clk, rst_n, lock_cmd, unlock_cmd, DFT_sdi, DFT_sen;
  input [3:0] pin_input;
  output door_locked, DFT_sdo;
  output [1:0] lock_status;
  wire clk, rst_n, lock_cmd, unlock_cmd, DFT_sdi, DFT_sen;
  wire [3:0] pin_input;
  wire door_locked, DFT_sdo;
  wire [1:0] lock_status;
  wire [2:0] attempt_counter;
  wire [1:0] state;
  wire [7:0] timeout_counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  SDFFRHQX1 door_locked_reg(.RN (rst_n), .CK (clk), .D (n_55), .SI
       (attempt_counter[2]), .SE (DFT_sen), .Q (door_locked));
  SDFFRHQX1 \lock_status_reg[1] (.RN (rst_n), .CK (clk), .D (state[1]),
       .SI (lock_status[0]), .SE (DFT_sen), .Q (lock_status[1]));
  SDFFRHQX1 \lock_status_reg[0] (.RN (rst_n), .CK (clk), .D (state[0]),
       .SI (door_locked), .SE (DFT_sen), .Q (lock_status[0]));
  OR2X1 g754(.A (state[0]), .B (state[1]), .Y (n_55));
  SDFFRHQX1 \timeout_counter_reg[7] (.RN (rst_n), .CK (clk), .D (n_54),
       .SI (timeout_counter[6]), .SE (DFT_sen), .Q (DFT_sdo));
  SDFFRHQX1 \timeout_counter_reg[6] (.RN (rst_n), .CK (clk), .D (n_52),
       .SI (timeout_counter[5]), .SE (DFT_sen), .Q
       (timeout_counter[6]));
  NOR2XL g2229(.A (n_30), .B (n_53), .Y (n_54));
  AOI21XL g2230(.A0 (timeout_counter[6]), .A1 (n_49), .B0 (DFT_sdo), .Y
       (n_53));
  NOR2XL g2231(.A (n_30), .B (n_51), .Y (n_52));
  SDFFRHQX1 \timeout_counter_reg[5] (.RN (rst_n), .CK (clk), .D (n_50),
       .SI (timeout_counter[4]), .SE (DFT_sen), .Q
       (timeout_counter[5]));
  MXI2XL g2233(.A (n_49), .B (n_46), .S0 (timeout_counter[6]), .Y
       (n_51));
  NOR2XL g2234(.A (n_30), .B (n_48), .Y (n_50));
  CLKINVX1 g2235(.A (n_46), .Y (n_49));
  SDFFRHQX1 \timeout_counter_reg[4] (.RN (rst_n), .CK (clk), .D (n_45),
       .SI (timeout_counter[3]), .SE (DFT_sen), .Q
       (timeout_counter[4]));
  AOI21XL g2237(.A0 (timeout_counter[5]), .A1 (n_42), .B0 (n_47), .Y
       (n_48));
  NOR2XL g2238(.A (timeout_counter[5]), .B (n_42), .Y (n_47));
  NOR2XL g2239(.A (n_44), .B (n_30), .Y (n_45));
  NAND2BX1 g2240(.AN (n_42), .B (timeout_counter[5]), .Y (n_46));
  SDFFRHQX1 \timeout_counter_reg[3] (.RN (rst_n), .CK (clk), .D (n_41),
       .SI (timeout_counter[2]), .SE (DFT_sen), .Q
       (timeout_counter[3]));
  AOI21XL g2242(.A0 (timeout_counter[4]), .A1 (n_37), .B0 (n_43), .Y
       (n_44));
  NOR2XL g2243(.A (timeout_counter[4]), .B (n_37), .Y (n_43));
  NOR2XL g2244(.A (n_40), .B (n_30), .Y (n_41));
  NAND2BX1 g2245(.AN (n_37), .B (timeout_counter[4]), .Y (n_42));
  SDFFRHQX1 \attempt_counter_reg[0] (.RN (rst_n), .CK (clk), .D (n_39),
       .SI (DFT_sdi), .SE (DFT_sen), .Q (attempt_counter[0]));
  SDFFRHQX1 \attempt_counter_reg[1] (.RN (rst_n), .CK (clk), .D (n_38),
       .SI (attempt_counter[0]), .SE (DFT_sen), .Q
       (attempt_counter[1]));
  SDFFRHQX1 \timeout_counter_reg[1] (.RN (rst_n), .CK (clk), .D (n_33),
       .SI (timeout_counter[0]), .SE (DFT_sen), .Q
       (timeout_counter[1]));
  SDFFRHQX1 \timeout_counter_reg[2] (.RN (rst_n), .CK (clk), .D (n_31),
       .SI (timeout_counter[1]), .SE (DFT_sen), .Q
       (timeout_counter[2]));
  SDFFRHQX1 \state_reg[1] (.RN (rst_n), .CK (clk), .D (n_32), .SI
       (state[0]), .SE (DFT_sen), .Q (state[1]));
  SDFFRHQX1 \state_reg[0] (.RN (rst_n), .CK (clk), .D (n_34), .SI
       (lock_status[1]), .SE (DFT_sen), .Q (state[0]));
  AOI21XL g2252(.A0 (timeout_counter[3]), .A1 (n_1), .B0 (n_35), .Y
       (n_40));
  AO21X1 g2253(.A0 (attempt_counter[0]), .A1 (n_28), .B0 (n_26), .Y
       (n_39));
  OAI22X1 g2254(.A0 (n_19), .A1 (n_15), .B0 (n_6), .B1 (n_29), .Y
       (n_38));
  SDFFRHQX1 \timeout_counter_reg[0] (.RN (rst_n), .CK (clk), .D (n_36),
       .SI (state[1]), .SE (DFT_sen), .Q (timeout_counter[0]));
  NOR2XL g2256(.A (timeout_counter[0]), .B (n_30), .Y (n_36));
  NOR2XL g2257(.A (timeout_counter[3]), .B (n_1), .Y (n_35));
  NAND2BX1 g2258(.AN (n_1), .B (timeout_counter[3]), .Y (n_37));
  NAND2XL g2259(.A (n_25), .B (n_27), .Y (n_34));
  NOR2XL g2260(.A (n_11), .B (n_30), .Y (n_33));
  NAND2XL g2261(.A (n_19), .B (n_30), .Y (n_32));
  NOR2XL g2262(.A (n_24), .B (n_30), .Y (n_31));
  SDFFRHQX1 \attempt_counter_reg[2] (.RN (rst_n), .CK (clk), .D (n_23),
       .SI (attempt_counter[1]), .SE (DFT_sen), .Q
       (attempt_counter[2]));
  OAI21X1 g2264(.A0 (n_18), .A1 (n_20), .B0 (state[1]), .Y (n_30));
  INVXL g2265(.A (n_28), .Y (n_29));
  AOI32X1 g2266(.A0 (lock_cmd), .A1 (n_2), .A2 (n_3), .B0 (state[1]),
       .B1 (n_21), .Y (n_27));
  OAI21X1 g2267(.A0 (n_5), .A1 (n_19), .B0 (n_12), .Y (n_28));
  AOI211X1 g2268(.A0 (attempt_counter[1]), .A1 (attempt_counter[2]),
       .B0 (attempt_counter[0]), .C0 (n_19), .Y (n_26));
  OAI21X1 g2269(.A0 (n_10), .A1 (n_17), .B0 (state[0]), .Y (n_25));
  AOI21XL g2270(.A0 (timeout_counter[2]), .A1 (n_7), .B0 (n_22), .Y
       (n_24));
  OAI32X1 g2271(.A0 (n_3), .A1 (n_10), .A2 (n_16), .B0 (n_5), .B1
       (n_12), .Y (n_23));
  NOR2XL g2272(.A (timeout_counter[2]), .B (n_7), .Y (n_22));
  INVXL g2274(.A (n_20), .Y (n_21));
  AOI31X1 g2275(.A0 (DFT_sdo), .A1 (timeout_counter[6]), .A2 (n_0), .B0
       (n_3), .Y (n_18));
  AOI31X1 g2276(.A0 (timeout_counter[5]), .A1 (timeout_counter[6]), .A2
       (n_14), .B0 (DFT_sdo), .Y (n_20));
  NAND3BX1 g2277(.AN (n_10), .B (state[0]), .C (n_13), .Y (n_19));
  INVX1 g2279(.A (n_16), .Y (n_17));
  OAI2BB1X1 g2280(.A0N (n_5), .A1N (n_9), .B0 (n_13), .Y (n_16));
  AOI32X1 g2281(.A0 (attempt_counter[0]), .A1 (n_6), .A2 (n_5), .B0
       (attempt_counter[1]), .B1 (n_4), .Y (n_15));
  NAND2BX1 g2283(.AN (timeout_counter[2]), .B (n_8), .Y (n_14));
  XNOR2XL g2284(.A (timeout_counter[0]), .B (timeout_counter[1]), .Y
       (n_11));
  NAND4BXL g2285(.AN (pin_input[3]), .B (pin_input[0]), .C
       (pin_input[1]), .D (pin_input[2]), .Y (n_13));
  AOI2BB1X1 g2286(.A0N (unlock_cmd), .A1N (n_3), .B0 (state[1]), .Y
       (n_12));
  NAND2XL g2287(.A (attempt_counter[0]), .B (attempt_counter[1]), .Y
       (n_9));
  NAND2XL g2288(.A (unlock_cmd), .B (n_2), .Y (n_10));
  NOR2XL g2289(.A (timeout_counter[3]), .B (timeout_counter[4]), .Y
       (n_8));
  NAND2XL g2290(.A (timeout_counter[0]), .B (timeout_counter[1]), .Y
       (n_7));
  CLKINVX1 g2295(.A (state[1]), .Y (n_2));
  INVX1 g2296(.A (attempt_counter[1]), .Y (n_6));
  CLKINVX1 g2297(.A (attempt_counter[2]), .Y (n_5));
  INVXL g2298(.A (attempt_counter[0]), .Y (n_4));
  CLKINVX1 g2299(.A (state[0]), .Y (n_3));
  NAND2BX1 g2(.AN (n_7), .B (timeout_counter[2]), .Y (n_1));
  NAND2BX1 g2300(.AN (timeout_counter[5]), .B (n_8), .Y (n_0));
endmodule

module entertainment_system(clk, rst_n, tv_on_cmd, music_on_cmd,
     volume_cmd, tv_on, music_on, volume_level, DFT_sdi, DFT_sen);
  input clk, rst_n, tv_on_cmd, music_on_cmd, DFT_sdi, DFT_sen;
  input [3:0] volume_cmd;
  output tv_on, music_on;
  output [3:0] volume_level;
  wire clk, rst_n, tv_on_cmd, music_on_cmd, DFT_sdi, DFT_sen;
  wire [3:0] volume_cmd;
  wire tv_on, music_on;
  wire [3:0] volume_level;
  wire n_0, n_1, n_2, n_3, n_4;
  SDFFRHQX1 tv_on_reg(.RN (rst_n), .CK (clk), .D (tv_on_cmd), .SI
       (music_on), .SE (DFT_sen), .Q (tv_on));
  SDFFRHQX1 music_on_reg(.RN (rst_n), .CK (clk), .D (music_on_cmd), .SI
       (DFT_sdi), .SE (DFT_sen), .Q (music_on));
  SDFFSHQX1 \volume_level_reg[0] (.SN (rst_n), .CK (clk), .D (n_3), .SI
       (tv_on), .SE (DFT_sen), .Q (volume_level[0]));
  SDFFSHQX1 \volume_level_reg[2] (.SN (rst_n), .CK (clk), .D (n_2), .SI
       (volume_level[1]), .SE (DFT_sen), .Q (volume_level[2]));
  SDFFRHQX1 \volume_level_reg[1] (.RN (rst_n), .CK (clk), .D (n_4), .SI
       (volume_level[0]), .SE (DFT_sen), .Q (volume_level[1]));
  SDFFRHQX1 \volume_level_reg[3] (.RN (rst_n), .CK (clk), .D (n_1), .SI
       (volume_level[2]), .SE (DFT_sen), .Q (volume_level[3]));
  MX2X1 g44(.A (volume_cmd[1]), .B (volume_level[1]), .S0 (n_0), .Y
       (n_4));
  MX2X1 g45(.A (volume_cmd[0]), .B (volume_level[0]), .S0 (n_0), .Y
       (n_3));
  MX2X1 g46(.A (volume_cmd[2]), .B (volume_level[2]), .S0 (n_0), .Y
       (n_2));
  MX2X1 g47(.A (volume_cmd[3]), .B (volume_level[3]), .S0 (n_0), .Y
       (n_1));
  NOR4X1 g48(.A (volume_cmd[3]), .B (volume_cmd[2]), .C
       (volume_cmd[1]), .D (volume_cmd[0]), .Y (n_0));
endmodule

module humidity_controller(clk, rst_n, humidity_sensor, humidifier_on,
     dehumidifier_on, DFT_sdi, DFT_sen);
  input clk, rst_n, DFT_sdi, DFT_sen;
  input [7:0] humidity_sensor;
  output humidifier_on, dehumidifier_on;
  wire clk, rst_n, DFT_sdi, DFT_sen;
  wire [7:0] humidity_sensor;
  wire humidifier_on, dehumidifier_on;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  SDFFRHQX1 dehumidifier_on_reg(.RN (rst_n), .CK (clk), .D (n_5), .SI
       (DFT_sdi), .SE (DFT_sen), .Q (dehumidifier_on));
  SDFFRHQX1 humidifier_on_reg(.RN (rst_n), .CK (clk), .D (n_4), .SI
       (dehumidifier_on), .SE (DFT_sen), .Q (humidifier_on));
  AOI21XL g202(.A0 (n_0), .A1 (n_1), .B0 (n_3), .Y (n_5));
  AOI21X1 g203(.A0 (humidity_sensor[5]), .A1 (humidity_sensor[3]), .B0
       (n_2), .Y (n_4));
  INVXL g204(.A (n_2), .Y (n_3));
  OAI2BB1X1 g205(.A0N (humidity_sensor[4]), .A1N (humidity_sensor[5]),
       .B0 (n_0), .Y (n_2));
  OAI211X1 g206(.A0 (humidity_sensor[1]), .A1 (humidity_sensor[0]), .B0
       (humidity_sensor[2]), .C0 (humidity_sensor[3]), .Y (n_1));
  NOR2XL g207(.A (humidity_sensor[7]), .B (humidity_sensor[6]), .Y
       (n_0));
endmodule

module luminosity_controller(clk, rst_n, light_sensor, led_brightness,
     DFT_sdi, DFT_sen);
  input clk, rst_n, DFT_sdi, DFT_sen;
  input [7:0] light_sensor;
  output [7:0] led_brightness;
  wire clk, rst_n, DFT_sdi, DFT_sen;
  wire [7:0] light_sensor;
  wire [7:0] led_brightness;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  SDFFRHQX1 \led_brightness_reg[4] (.RN (rst_n), .CK (clk), .D (n_5),
       .SI (led_brightness[3]), .SE (DFT_sen), .Q (led_brightness[4]));
  SDFFRHQX1 \led_brightness_reg[6] (.RN (rst_n), .CK (clk), .D (n_6),
       .SI (led_brightness[5]), .SE (DFT_sen), .Q (led_brightness[6]));
  SDFFRHQX1 \led_brightness_reg[7] (.RN (rst_n), .CK (clk), .D (n_7),
       .SI (led_brightness[6]), .SE (DFT_sen), .Q (led_brightness[7]));
  SDFFRHQX1 \led_brightness_reg[0] (.RN (rst_n), .CK (clk), .D (n_4),
       .SI (DFT_sdi), .SE (DFT_sen), .Q (led_brightness[0]));
  SDFFRHQX1 \led_brightness_reg[2] (.RN (rst_n), .CK (clk), .D (n_0),
       .SI (led_brightness[1]), .SE (DFT_sen), .Q (led_brightness[2]));
  SDFFRHQX1 \led_brightness_reg[5] (.RN (rst_n), .CK (clk), .D (n_1),
       .SI (led_brightness[4]), .SE (DFT_sen), .Q (led_brightness[5]));
  SDFFRHQX1 \led_brightness_reg[3] (.RN (rst_n), .CK (clk), .D (n_2),
       .SI (led_brightness[2]), .SE (DFT_sen), .Q (led_brightness[3]));
  SDFFRHQX1 \led_brightness_reg[1] (.RN (rst_n), .CK (clk), .D (n_3),
       .SI (led_brightness[0]), .SE (DFT_sen), .Q (led_brightness[1]));
  INVX1 g95(.A (light_sensor[7]), .Y (n_7));
  INVX1 g96(.A (light_sensor[6]), .Y (n_6));
  INVX1 g97(.A (light_sensor[4]), .Y (n_5));
  INVX1 g98(.A (light_sensor[0]), .Y (n_4));
  INVX1 g99(.A (light_sensor[1]), .Y (n_3));
  INVX1 g100(.A (light_sensor[3]), .Y (n_2));
  INVX1 g101(.A (light_sensor[5]), .Y (n_1));
  INVX1 g102(.A (light_sensor[2]), .Y (n_0));
endmodule

module temperature_controller(clk, rst_n, temp_sensor, temp_setpoint,
     heater_on, cooler_on, DFT_sdi, DFT_sen, DFT_sdo);
  input clk, rst_n, DFT_sdi, DFT_sen;
  input [7:0] temp_sensor, temp_setpoint;
  output heater_on, cooler_on, DFT_sdo;
  wire clk, rst_n, DFT_sdi, DFT_sen;
  wire [7:0] temp_sensor, temp_setpoint;
  wire heater_on, cooler_on, DFT_sdo;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_35, n_36, n_37, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_78, n_79, n_80, n_81, n_82, n_83, n_84, n_85;
  wire n_86, n_87, n_88, n_89, n_90, n_91, n_92, n_93;
  wire n_112, n_113, n_114;
  SDFFRXL cooler_on_reg(.RN (rst_n), .CK (clk), .D (n_92), .SI
       (DFT_sdi), .SE (DFT_sen), .Q (cooler_on), .QN (n_1));
  SDFFRXL heater_on_reg(.RN (rst_n), .CK (clk), .D (n_93), .SI (n_1),
       .SE (DFT_sen), .Q (heater_on), .QN (DFT_sdo));
  OAI21X1 g1630(.A0 (n_18), .A1 (n_90), .B0 (n_89), .Y (n_93));
  OAI21X1 g1631(.A0 (n_13), .A1 (n_90), .B0 (n_91), .Y (n_92));
  NAND2XL g1632(.A (n_88), .B (n_89), .Y (n_91));
  NAND3X2 g1633(.A (n_42), .B (n_87), .C (n_89), .Y (n_90));
  NAND3X1 g1634(.A (n_83), .B (n_85), .C (n_86), .Y (n_89));
  INVX1 g1635(.A (n_87), .Y (n_88));
  NAND2X2 g1636(.A (n_84), .B (n_82), .Y (n_87));
  NAND2XL g1637(.A (n_80), .B (n_81), .Y (n_86));
  NAND2XL g1638(.A (n_73), .B (n_81), .Y (n_85));
  AOI22X1 g1639(.A0 (n_70), .A1 (n_79), .B0 (n_71), .B1 (n_74), .Y
       (n_84));
  AOI31X1 g1640(.A0 (temp_sensor[6]), .A1 (n_56), .A2 (n_76), .B0
       (n_7), .Y (n_83));
  AOI21X1 g1641(.A0 (n_69), .A1 (n_79), .B0 (n_114), .Y (n_82));
  AOI21X1 g1642(.A0 (n_12), .A1 (n_75), .B0 (n_55), .Y (n_81));
  AOI211X1 g1643(.A0 (n_61), .A1 (n_52), .B0 (n_8), .C0 (n_72), .Y
       (n_80));
  AOI21X1 g1644(.A0 (temp_sensor[6]), .A1 (n_62), .B0 (n_78), .Y
       (n_79));
  NOR2XL g1645(.A (n_11), .B (n_71), .Y (n_78));
  INVXL g1647(.A (n_75), .Y (n_76));
  OAI21X1 g1648(.A0 (temp_sensor[6]), .A1 (n_62), .B0 (temp_sensor[7]),
       .Y (n_74));
  OAI21XL g1649(.A0 (n_68), .A1 (n_64), .B0 (n_65), .Y (n_73));
  OAI21X1 g1650(.A0 (n_15), .A1 (n_59), .B0 (n_37), .Y (n_75));
  NOR2XL g1651(.A (temp_sensor[5]), .B (n_63), .Y (n_72));
  NOR2XL g1653(.A (n_66), .B (n_112), .Y (n_70));
  OAI32X1 g1654(.A0 (temp_sensor[4]), .A1 (n_6), .A2 (n_51), .B0
       (temp_sensor[5]), .B1 (n_43), .Y (n_69));
  NAND2BX1 g1655(.AN (temp_setpoint[7]), .B (n_58), .Y (n_71));
  INVX1 g1657(.A (n_63), .Y (n_68));
  OAI2BB1X1 g1659(.A0N (temp_sensor[4]), .A1N (n_6), .B0 (n_50), .Y
       (n_66));
  NAND2XL g1660(.A (temp_sensor[5]), .B (n_60), .Y (n_65));
  NOR2X1 g1661(.A (temp_sensor[5]), .B (n_60), .Y (n_64));
  OAI221X1 g1662(.A0 (temp_sensor[3]), .A1 (n_39), .B0
       (temp_sensor[2]), .B1 (n_4), .C0 (n_48), .Y (n_61));
  AOI21X1 g1663(.A0 (temp_setpoint[5]), .A1 (n_40), .B0 (n_59), .Y
       (n_63));
  AOI21X1 g1664(.A0 (temp_setpoint[6]), .A1 (n_45), .B0 (n_57), .Y
       (n_62));
  NAND4XL g1665(.A (temp_setpoint[6]), .B (temp_setpoint[3]), .C
       (n_25), .D (n_19), .Y (n_58));
  NOR4X1 g1667(.A (temp_setpoint[6]), .B (n_16), .C (n_24), .D (n_20),
       .Y (n_57));
  NOR2BX1 g1668(.AN (temp_sensor[4]), .B (n_44), .Y (n_60));
  NOR3X1 g1669(.A (temp_setpoint[5]), .B (temp_setpoint[4]), .C (n_31),
       .Y (n_59));
  INVX1 g1670(.A (n_55), .Y (n_56));
  OAI21X1 g1671(.A0 (temp_sensor[3]), .A1 (n_113), .B0 (n_2), .Y
       (n_54));
  AOI21XL g1672(.A0 (temp_sensor[2]), .A1 (n_35), .B0 (n_49), .Y
       (n_53));
  AOI32X1 g1674(.A0 (temp_sensor[3]), .A1 (temp_sensor[2]), .A2 (n_4),
       .B0 (n_39), .B1 (n_3), .Y (n_52));
  NOR2X1 g1675(.A (temp_sensor[7]), .B (n_46), .Y (n_55));
  INVX1 g1678(.A (n_50), .Y (n_51));
  OAI31X1 g1679(.A0 (temp_setpoint[0]), .A1 (n_17), .A2 (n_21), .B0
       (n_22), .Y (n_49));
  AOI31X1 g1680(.A0 (temp_setpoint[0]), .A1 (n_17), .A2 (n_22), .B0
       (n_21), .Y (n_48));
  NAND2X1 g1681(.A (temp_sensor[5]), .B (n_43), .Y (n_50));
  NAND2XL g1683(.A (temp_sensor[3]), .B (n_113), .Y (n_47));
  AOI21X1 g1684(.A0 (temp_setpoint[7]), .A1 (n_37), .B0 (n_5), .Y
       (n_46));
  NAND3XL g1685(.A (temp_setpoint[3]), .B (n_25), .C (n_19), .Y (n_45));
  OAI21X1 g1689(.A0 (n_21), .A1 (n_23), .B0 (n_30), .Y (n_42));
  MXI2XL g1690(.A (n_31), .B (n_32), .S0 (temp_setpoint[4]), .Y (n_44));
  AOI21X1 g1691(.A0 (temp_setpoint[5]), .A1 (n_29), .B0 (n_41), .Y
       (n_43));
  NOR3X1 g1692(.A (temp_setpoint[5]), .B (n_28), .C (n_20), .Y (n_41));
  NAND2XL g1694(.A (n_10), .B (n_32), .Y (n_40));
  AOI2BB1X1 g1695(.A0N (n_16), .A1N (n_27), .B0 (n_32), .Y (n_39));
  NAND2XL g1697(.A (n_33), .B (n_32), .Y (n_37));
  INVXL g1698(.A (n_4), .Y (n_35));
  NAND2XL g1700(.A (temp_setpoint[3]), .B (n_19), .Y (n_36));
  CLKINVX2 g1703(.A (n_32), .Y (n_31));
  NOR3X1 g1704(.A (temp_setpoint[6]), .B (temp_setpoint[4]), .C
       (temp_setpoint[5]), .Y (n_33));
  MXI2XL g1705(.A (temp_sensor[0]), .B (n_17), .S0 (temp_setpoint[0]),
       .Y (n_30));
  NAND2BX1 g1706(.AN (n_28), .B (n_19), .Y (n_29));
  CLKAND2X3 g1707(.A (n_14), .B (n_26), .Y (n_32));
  NAND2X1 g1709(.A (temp_setpoint[4]), .B (temp_setpoint[3]), .Y
       (n_28));
  NOR2X2 g1710(.A (temp_setpoint[3]), .B (temp_setpoint[2]), .Y (n_26));
  NOR2X1 g1711(.A (temp_setpoint[2]), .B (temp_setpoint[1]), .Y (n_27));
  CLKINVX1 g1712(.A (n_24), .Y (n_25));
  INVXL g1713(.A (n_22), .Y (n_23));
  CLKINVX2 g1714(.A (n_20), .Y (n_19));
  NAND2X1 g1715(.A (temp_setpoint[5]), .B (temp_setpoint[4]), .Y
       (n_24));
  NAND2XL g1716(.A (temp_setpoint[1]), .B (temp_sensor[1]), .Y (n_22));
  NOR2XL g1717(.A (temp_sensor[1]), .B (temp_setpoint[1]), .Y (n_21));
  NAND2X4 g1718(.A (temp_setpoint[2]), .B (temp_setpoint[1]), .Y
       (n_20));
  INVXL g1719(.A (heater_on), .Y (n_18));
  CLKINVX1 g1720(.A (temp_sensor[0]), .Y (n_17));
  CLKINVX1 g1721(.A (temp_setpoint[3]), .Y (n_16));
  INVXL g1723(.A (temp_setpoint[6]), .Y (n_15));
  INVX1 g1724(.A (temp_setpoint[1]), .Y (n_14));
  INVXL g1725(.A (cooler_on), .Y (n_13));
  CLKINVX1 g1726(.A (temp_sensor[6]), .Y (n_12));
  CLKINVX1 g1728(.A (temp_sensor[7]), .Y (n_11));
  INVXL g1729(.A (temp_setpoint[4]), .Y (n_10));
  NOR2BXL g1736(.AN (n_44), .B (temp_sensor[4]), .Y (n_8));
  NOR2BXL g1737(.AN (n_46), .B (n_11), .Y (n_7));
  CLKXOR2X1 g1738(.A (n_36), .B (temp_setpoint[4]), .Y (n_6));
  NOR3BX1 g1739(.AN (n_33), .B (temp_setpoint[7]), .C (n_31), .Y (n_5));
  NOR2BX2 g1740(.AN (n_20), .B (n_27), .Y (n_4));
  AO21X1 g1741(.A0 (temp_sensor[2]), .A1 (n_4), .B0 (temp_sensor[3]),
       .Y (n_3));
  NAND2BX1 g1742(.AN (temp_sensor[2]), .B (n_4), .Y (n_2));
  OAI21X1 g1743(.A0 (n_54), .A1 (n_53), .B0 (n_47), .Y (n_112));
  XNOR2XL g1744(.A (n_20), .B (n_16), .Y (n_113));
  NOR3BXL g1745(.AN (n_12), .B (temp_sensor[7]), .C (n_62), .Y (n_114));
endmodule

module visitor_counter(clk, rst_n, entry_sensor, exit_sensor, count,
     DFT_sdi, DFT_sen, DFT_sdo);
  input clk, rst_n, entry_sensor, exit_sensor, DFT_sdi, DFT_sen;
  output [7:0] count;
  output DFT_sdo;
  wire clk, rst_n, entry_sensor, exit_sensor, DFT_sdi, DFT_sen;
  wire [7:0] count;
  wire DFT_sdo;
  wire entry_prev, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50;
  SDFFRHQX2 \count_reg[6] (.RN (rst_n), .CK (clk), .D (n_50), .SI
       (count[5]), .SE (DFT_sen), .Q (count[6]));
  OAI222XL g1045(.A0 (n_32), .A1 (n_41), .B0 (n_26), .B1 (n_47), .C0
       (n_30), .C1 (n_4), .Y (n_50));
  SDFFRHQX2 \count_reg[5] (.RN (rst_n), .CK (clk), .D (n_49), .SI
       (count[4]), .SE (DFT_sen), .Q (count[5]));
  SDFFRHQX1 \count_reg[7] (.RN (rst_n), .CK (clk), .D (n_48), .SI
       (count[6]), .SE (DFT_sen), .Q (count[7]));
  OAI211X1 g1048(.A0 (n_29), .A1 (n_32), .B0 (n_33), .C0 (n_45), .Y
       (n_49));
  OAI31XL g1049(.A0 (n_26), .A1 (n_4), .A2 (n_43), .B0 (n_46), .Y
       (n_48));
  MXI2XL g1050(.A (n_4), .B (count[6]), .S0 (n_43), .Y (n_47));
  SDFFRHQX2 \count_reg[4] (.RN (rst_n), .CK (clk), .D (n_44), .SI
       (count[3]), .SE (DFT_sen), .Q (count[4]));
  OAI31X1 g1052(.A0 (n_25), .A1 (n_31), .A2 (n_38), .B0 (count[7]), .Y
       (n_46));
  OAI211X1 g1053(.A0 (count[5]), .A1 (n_35), .B0 (n_25), .C0 (n_43), .Y
       (n_45));
  OAI222XL g1054(.A0 (n_21), .A1 (n_32), .B0 (n_2), .B1 (n_30), .C0
       (n_36), .C1 (n_26), .Y (n_44));
  SDFFRHQX2 \count_reg[1] (.RN (rst_n), .CK (clk), .D (n_42), .SI
       (count[0]), .SE (DFT_sen), .Q (count[1]));
  SDFFRHQX2 \count_reg[2] (.RN (rst_n), .CK (clk), .D (n_39), .SI
       (count[1]), .SE (DFT_sen), .Q (count[2]));
  NAND2XL g1057(.A (count[5]), .B (n_35), .Y (n_43));
  SDFFRHQX2 \count_reg[3] (.RN (rst_n), .CK (clk), .D (n_40), .SI
       (count[2]), .SE (DFT_sen), .Q (count[3]));
  OAI211X1 g1059(.A0 (n_0), .A1 (n_26), .B0 (n_34), .C0 (n_1), .Y
       (n_42));
  SDFFRHQX4 \count_reg[0] (.RN (rst_n), .CK (clk), .D (n_37), .SI
       (DFT_sdi), .SE (DFT_sen), .Q (count[0]));
  MXI2XL g1061(.A (count[6]), .B (n_4), .S0 (n_28), .Y (n_41));
  OAI222XL g1062(.A0 (n_27), .A1 (n_32), .B0 (n_6), .B1 (n_30), .C0
       (n_26), .C1 (n_24), .Y (n_40));
  OAI222XL g1063(.A0 (n_17), .A1 (n_32), .B0 (n_5), .B1 (n_30), .C0
       (n_26), .C1 (n_16), .Y (n_39));
  NAND2XL g1064(.A (n_4), .B (n_28), .Y (n_38));
  MXI2XL g1065(.A (n_31), .B (n_30), .S0 (count[0]), .Y (n_37));
  MXI2XL g1066(.A (n_2), .B (count[4]), .S0 (n_23), .Y (n_36));
  NAND2XL g1067(.A (count[1]), .B (n_31), .Y (n_34));
  NOR2XL g1068(.A (n_2), .B (n_23), .Y (n_35));
  NAND2XL g1069(.A (count[5]), .B (n_31), .Y (n_33));
  NAND2XL g1072(.A (n_20), .B (n_26), .Y (n_32));
  CLKINVX1 g1073(.A (n_31), .Y (n_30));
  AOI21X1 g1074(.A0 (count[5]), .A1 (n_19), .B0 (n_28), .Y (n_29));
  NOR2X1 g1075(.A (n_20), .B (n_25), .Y (n_31));
  AOI21X1 g1076(.A0 (count[3]), .A1 (n_13), .B0 (n_14), .Y (n_27));
  NOR2X1 g1077(.A (count[5]), .B (n_19), .Y (n_28));
  CLKINVX1 g1078(.A (n_26), .Y (n_25));
  MXI2XL g1079(.A (count[3]), .B (n_6), .S0 (n_15), .Y (n_24));
  NAND3BX1 g1080(.AN (entry_prev), .B (entry_sensor), .C (n_22), .Y
       (n_26));
  NAND2X1 g1081(.A (count[3]), .B (n_15), .Y (n_23));
  NAND2XL g1082(.A (n_15), .B (n_18), .Y (n_22));
  OA21XL g1083(.A0 (n_2), .A1 (n_14), .B0 (n_19), .Y (n_21));
  AOI211X1 g1084(.A0 (n_12), .A1 (n_14), .B0 (DFT_sdo), .C0 (n_3), .Y
       (n_20));
  NOR3X1 g1085(.A (n_8), .B (n_4), .C (n_11), .Y (n_18));
  NAND2XL g1086(.A (n_2), .B (n_14), .Y (n_19));
  MXI2XL g1087(.A (count[2]), .B (n_5), .S0 (n_9), .Y (n_17));
  MXI2XL g1088(.A (n_5), .B (count[2]), .S0 (n_10), .Y (n_16));
  NOR2X2 g1090(.A (n_5), .B (n_10), .Y (n_15));
  NAND2XL g1091(.A (n_5), .B (n_9), .Y (n_13));
  NOR4X1 g1092(.A (count[7]), .B (count[6]), .C (count[5]), .D
       (count[4]), .Y (n_12));
  AND2X1 g1093(.A (n_9), .B (n_7), .Y (n_14));
  SDFFRHQX1 exit_prev_reg(.RN (rst_n), .CK (clk), .D (exit_sensor), .SI
       (entry_prev), .SE (DFT_sen), .Q (DFT_sdo));
  SDFFRHQX1 entry_prev_reg(.RN (rst_n), .CK (clk), .D (entry_sensor),
       .SI (count[7]), .SE (DFT_sen), .Q (entry_prev));
  NAND2XL g1096(.A (count[4]), .B (count[5]), .Y (n_11));
  NAND2XL g1098(.A (count[3]), .B (count[7]), .Y (n_8));
  NOR2XL g1099(.A (count[3]), .B (count[2]), .Y (n_7));
  NAND2X2 g1100(.A (count[0]), .B (count[1]), .Y (n_10));
  NOR2X1 g1101(.A (count[0]), .B (count[1]), .Y (n_9));
  CLKINVX1 g1102(.A (count[3]), .Y (n_6));
  CLKINVX1 g1103(.A (count[2]), .Y (n_5));
  CLKINVX1 g1104(.A (count[6]), .Y (n_4));
  INVX1 g1105(.A (exit_sensor), .Y (n_3));
  CLKINVX1 g1109(.A (count[4]), .Y (n_2));
  NAND2BX1 g2(.AN (n_32), .B (n_0), .Y (n_1));
  NAND2BX1 g1110(.AN (n_9), .B (n_10), .Y (n_0));
endmodule

module water_level_controller(clk, rst_n, water_level, pump_on,
     valve_close, DFT_sdi, DFT_sen);
  input clk, rst_n, DFT_sdi, DFT_sen;
  input [3:0] water_level;
  output pump_on, valve_close;
  wire clk, rst_n, DFT_sdi, DFT_sen;
  wire [3:0] water_level;
  wire pump_on, valve_close;
  wire n_2, n_3, n_4, n_13;
  SDFFRHQX1 valve_close_reg(.RN (rst_n), .CK (clk), .D (n_4), .SI
       (pump_on), .SE (DFT_sen), .Q (valve_close));
  NOR2XL g77(.A (n_2), .B (n_3), .Y (n_4));
  AOI21X1 g79(.A0 (water_level[3]), .A1 (water_level[2]), .B0 (n_2), .Y
       (n_3));
  AOI211X1 g81(.A0 (water_level[1]), .A1 (water_level[0]), .B0
       (water_level[3]), .C0 (water_level[2]), .Y (n_2));
  SDFFRHQX1 pump_on_reg(.RN (rst_n), .CK (clk), .D (n_13), .SI
       (DFT_sdi), .SE (DFT_sen), .Q (pump_on));
  MX2X1 g2(.A (n_2), .B (pump_on), .S0 (n_3), .Y (n_13));
endmodule

module window_treatment(clk, rst_n, auto_mode, light_level,
     manual_open, manual_close, window_state, DFT_sdi, DFT_sen);
  input clk, rst_n, auto_mode, manual_open, manual_close, DFT_sdi,
       DFT_sen;
  input [7:0] light_level;
  output [1:0] window_state;
  wire clk, rst_n, auto_mode, manual_open, manual_close, DFT_sdi,
       DFT_sen;
  wire [7:0] light_level;
  wire [1:0] window_state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12;
  SDFFRHQX1 \window_state_reg[0] (.RN (rst_n), .CK (clk), .D (n_12),
       .SI (DFT_sdi), .SE (DFT_sen), .Q (window_state[0]));
  AO22X1 g360(.A0 (auto_mode), .A1 (n_11), .B0 (n_2), .B1
       (window_state[0]), .Y (n_12));
  SDFFRHQX1 \window_state_reg[1] (.RN (rst_n), .CK (clk), .D (n_10),
       .SI (window_state[0]), .SE (DFT_sen), .Q (window_state[1]));
  MXI2XL g362(.A (n_7), .B (n_9), .S0 (light_level[6]), .Y (n_11));
  OAI21X1 g363(.A0 (auto_mode), .A1 (n_3), .B0 (n_8), .Y (n_10));
  NOR2BXL g364(.AN (light_level[7]), .B (n_6), .Y (n_9));
  NAND3BX1 g365(.AN (light_level[6]), .B (auto_mode), .C (n_7), .Y
       (n_8));
  AOI31X1 g366(.A0 (light_level[5]), .A1 (light_level[4]), .A2 (n_4),
       .B0 (light_level[7]), .Y (n_7));
  AOI211X1 g367(.A0 (light_level[3]), .A1 (n_5), .B0 (light_level[5]),
       .C0 (light_level[4]), .Y (n_6));
  NAND2BX1 g368(.AN (light_level[0]), .B (n_1), .Y (n_5));
  NAND2BXL g369(.AN (light_level[3]), .B (n_1), .Y (n_4));
  AOI21X1 g370(.A0 (n_0), .A1 (window_state[1]), .B0 (manual_open), .Y
       (n_3));
  NOR3X1 g371(.A (manual_open), .B (manual_close), .C (auto_mode), .Y
       (n_2));
  NOR2XL g372(.A (light_level[2]), .B (light_level[1]), .Y (n_1));
  INVXL g373(.A (manual_close), .Y (n_0));
endmodule

module HA(clk, rst_n, temp_sensor, temp_setpoint, water_level,
     light_sensor, motion_sensor, door_sensor, window_sensor,
     alarm_arm, entry_sensor, exit_sensor, window_auto_mode,
     window_manual_open, window_manual_close, tv_on_cmd, music_on_cmd,
     volume_cmd, ac_cmd, fan_cmd, light_cmd, door_lock_cmd,
     door_unlock_cmd, pin_input, humidity_sensor, heater_on, cooler_on,
     water_pump_on, water_valve_close, led_brightness,
     burglar_alarm_out, visitor_count, window_state, tv_on, music_on,
     volume_level, ac_on, fan_on, lights_on, door_locked, lock_status,
     humidifier_on, dehumidifier_on, system_status, scan_en, test_mode,
     DFT_sdi_1, DFT_sdo_1, DFT_sdi_2, DFT_sdo_2);
  input clk, rst_n, motion_sensor, door_sensor, window_sensor,
       alarm_arm, entry_sensor, exit_sensor, window_auto_mode,
       window_manual_open, window_manual_close, tv_on_cmd,
       music_on_cmd, ac_cmd, fan_cmd, light_cmd, door_lock_cmd,
       door_unlock_cmd, scan_en, test_mode, DFT_sdi_1, DFT_sdi_2;
  input [7:0] temp_sensor, temp_setpoint, light_sensor, humidity_sensor;
  input [3:0] water_level, volume_cmd, pin_input;
  output heater_on, cooler_on, water_pump_on, water_valve_close,
       burglar_alarm_out, tv_on, music_on, ac_on, fan_on, lights_on,
       door_locked, humidifier_on, dehumidifier_on, DFT_sdo_1,
       DFT_sdo_2;
  output [7:0] led_brightness, visitor_count, system_status;
  output [1:0] window_state, lock_status;
  output [3:0] volume_level;
  wire clk, rst_n, motion_sensor, door_sensor, window_sensor,
       alarm_arm, entry_sensor, exit_sensor, window_auto_mode,
       window_manual_open, window_manual_close, tv_on_cmd,
       music_on_cmd, ac_cmd, fan_cmd, light_cmd, door_lock_cmd,
       door_unlock_cmd, scan_en, test_mode, DFT_sdi_1, DFT_sdi_2;
  wire [7:0] temp_sensor, temp_setpoint, light_sensor, humidity_sensor;
  wire [3:0] water_level, volume_cmd, pin_input;
  wire heater_on, cooler_on, water_pump_on, water_valve_close,
       burglar_alarm_out, tv_on, music_on, ac_on, fan_on, lights_on,
       door_locked, humidifier_on, dehumidifier_on, DFT_sdo_1,
       DFT_sdo_2;
  wire [7:0] led_brightness, visitor_count, system_status;
  wire [1:0] window_state, lock_status;
  wire [3:0] volume_level;
  wire [3:0] pin_input_r;
  wire [1:0] lock_status_int;
  wire [3:0] volume_cmd_r;
  wire [3:0] volume_level_int;
  wire [7:0] humidity_sensor_r;
  wire [7:0] light_sensor_r;
  wire [7:0] led_brightness_int;
  wire [7:0] temp_sensor_r;
  wire [7:0] temp_setpoint_r;
  wire [7:0] visitor_count_int;
  wire [3:0] water_level_r;
  wire [1:0] window_state_int;
  wire ac_cmd_r, ac_on_int, ac_on_r_375, alarm_arm_r,
       burglar_alarm_out_int, burglar_alarm_out_r_372, cooler_on_int,
       cooler_on_r_369;
  wire dehumidifier_on_int, door_lock_cmd_r, door_locked_int,
       door_locked_r_378, door_sensor_r, door_unlock_cmd_r,
       entry_sensor_r, exit_sensor_r;
  wire fan_cmd_r, fan_on_int, fan_on_r_376, heater_on_int,
       heater_on_r_368, humidifier_on_int, light_cmd_r, lights_on_int;
  wire lights_on_r_377, motion_sensor_r, music_on_cmd_r, music_on_int,
       n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_88, n_89, n_90, n_91;
  wire tv_on_cmd_r, tv_on_int, water_pump_on_int, water_pump_on_r_370,
       water_valve_close_int, window_auto_mode_r,
       window_manual_close_r, window_manual_open_r;
  wire window_sensor_r;
  assign DFT_sdo_2 = window_state[1];
  appliances_controller u_appliances(.clk (clk), .rst_n (rst_n),
       .ac_cmd (ac_cmd_r), .fan_cmd (fan_cmd_r), .light_cmd
       (light_cmd_r), .ac_on (ac_on_int), .fan_on (fan_on_int),
       .lights_on (lights_on_int), .DFT_sdi (DFT_sdi_1), .DFT_sen
       (scan_en));
  burglar_alarm u_burglar(.clk (clk), .rst_n (rst_n), .motion_sensor
       (motion_sensor_r), .door_sensor (door_sensor_r), .window_sensor
       (window_sensor_r), .alarm_arm (alarm_arm_r), .alarm_out
       (burglar_alarm_out_int), .DFT_sdi (lights_on_int), .DFT_sen
       (scan_en), .DFT_sdo (n_88));
  door_lock_controller u_door_lock(.clk (clk), .rst_n (rst_n),
       .lock_cmd (door_lock_cmd_r), .unlock_cmd (door_unlock_cmd_r),
       .pin_input (pin_input_r), .door_locked (door_locked_int),
       .lock_status (lock_status_int), .DFT_sdi (n_88), .DFT_sen
       (scan_en), .DFT_sdo (n_89));
  entertainment_system u_entertainment(.clk (clk), .rst_n (rst_n),
       .tv_on_cmd (tv_on_cmd_r), .music_on_cmd (music_on_cmd_r),
       .volume_cmd (volume_cmd_r), .tv_on (tv_on_int), .music_on
       (music_on_int), .volume_level (volume_level_int), .DFT_sdi
       (n_89), .DFT_sen (scan_en));
  humidity_controller u_humidity(.clk (clk), .rst_n (rst_n),
       .humidity_sensor ({humidity_sensor_r[7:2], DFT_sdo_1,
       humidity_sensor_r[0]}), .humidifier_on (humidifier_on_int),
       .dehumidifier_on (dehumidifier_on_int), .DFT_sdi
       (volume_level_int[3]), .DFT_sen (scan_en));
  luminosity_controller u_lum_ctrl(.clk (clk), .rst_n (rst_n),
       .light_sensor (light_sensor_r), .led_brightness
       (led_brightness_int), .DFT_sdi (humidifier_on_int), .DFT_sen
       (scan_en));
  temperature_controller u_temp_ctrl(.clk (clk), .rst_n (rst_n),
       .temp_sensor (temp_sensor_r), .temp_setpoint (temp_setpoint_r),
       .heater_on (heater_on_int), .cooler_on (cooler_on_int), .DFT_sdi
       (led_brightness_int[7]), .DFT_sen (scan_en), .DFT_sdo (n_90));
  visitor_counter u_visitor(.clk (clk), .rst_n (rst_n), .entry_sensor
       (entry_sensor_r), .exit_sensor (exit_sensor_r), .count
       (visitor_count_int), .DFT_sdi (n_90), .DFT_sen (scan_en),
       .DFT_sdo (n_91));
  water_level_controller u_water_ctrl(.clk (clk), .rst_n (rst_n),
       .water_level (water_level_r), .pump_on (water_pump_on_int),
       .valve_close (water_valve_close_int), .DFT_sdi (n_91), .DFT_sen
       (scan_en));
  window_treatment u_window(.clk (clk), .rst_n (rst_n), .auto_mode
       (window_auto_mode_r), .light_level (light_sensor_r),
       .manual_open (window_manual_open_r), .manual_close
       (window_manual_close_r), .window_state (window_state_int),
       .DFT_sdi (water_valve_close_int), .DFT_sen (scan_en));
  SDFFRHQX8 water_valve_close_r_reg(.RN (rst_n), .CK (clk), .D
       (water_valve_close_int), .SI (n_3), .SE (scan_en), .Q
       (water_valve_close));
  SDFFRHQX8 tv_on_r_reg(.RN (rst_n), .CK (clk), .D (tv_on_int), .SI
       (tv_on_cmd_r), .SE (scan_en), .Q (tv_on));
  SDFFRHQX8 music_on_r_reg(.RN (rst_n), .CK (clk), .D (music_on_int),
       .SI (music_on_cmd_r), .SE (scan_en), .Q (music_on));
  CLKINVX8 g44(.A (lights_on_r_377), .Y (lights_on));
  CLKINVX8 g45(.A (lights_on_r_377), .Y (system_status[2]));
  CLKINVX8 g74(.A (ac_on_r_375), .Y (ac_on));
  CLKINVX8 g75(.A (ac_on_r_375), .Y (system_status[4]));
  CLKINVX8 g76(.A (fan_on_r_376), .Y (fan_on));
  CLKINVX8 g77(.A (fan_on_r_376), .Y (system_status[3]));
  SDFFRHQX8 \led_brightness_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[2]), .SI (led_brightness[1]), .SE (scan_en),
       .Q (led_brightness[2]));
  SDFFRHQX8 \led_brightness_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[7]), .SI (led_brightness[6]), .SE (scan_en),
       .Q (led_brightness[7]));
  SDFFRHQX8 \led_brightness_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[3]), .SI (led_brightness[2]), .SE (scan_en),
       .Q (led_brightness[3]));
  SDFFRHQX8 humidifier_on_r_reg(.RN (rst_n), .CK (clk), .D
       (humidifier_on_int), .SI (n_2), .SE (scan_en), .Q
       (humidifier_on));
  SDFFRHQX8 dehumidifier_on_r_reg(.RN (rst_n), .CK (clk), .D
       (dehumidifier_on_int), .SI (n_0), .SE (scan_en), .Q
       (dehumidifier_on));
  SDFFRX1 lights_on_r_reg(.RN (rst_n), .CK (clk), .D (lights_on_int),
       .SI (light_sensor_r[7]), .SE (scan_en), .Q (n_7), .QN
       (lights_on_r_377));
  SDFFRHQX8 \led_brightness_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[1]), .SI (led_brightness[0]), .SE (scan_en),
       .Q (led_brightness[1]));
  SDFFRHQX8 \led_brightness_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[0]), .SI (humidity_sensor_r[7]), .SE
       (scan_en), .Q (led_brightness[0]));
  SDFFRHQX8 \led_brightness_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[6]), .SI (led_brightness[5]), .SE (scan_en),
       .Q (led_brightness[6]));
  SDFFRHQX8 \led_brightness_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[5]), .SI (led_brightness[4]), .SE (scan_en),
       .Q (led_brightness[5]));
  SDFFRHQX8 \led_brightness_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[4]), .SI (led_brightness[3]), .SE (scan_en),
       .Q (led_brightness[4]));
  SDFFRX1 ac_on_r_reg(.RN (rst_n), .CK (clk), .D (ac_on_int), .SI
       (ac_cmd_r), .SE (scan_en), .Q (n_6), .QN (ac_on_r_375));
  SDFFRX1 fan_on_r_reg(.RN (rst_n), .CK (clk), .D (fan_on_int), .SI
       (fan_cmd_r), .SE (scan_en), .Q (n_5), .QN (fan_on_r_376));
  CLKINVX8 g46(.A (door_locked_r_378), .Y (door_locked));
  CLKINVX8 g47(.A (door_locked_r_378), .Y (system_status[5]));
  SDFFRHQX8 \lock_status_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (lock_status_int[0]), .SI (n_7), .SE (scan_en), .Q
       (lock_status[0]));
  SDFFRHQX8 \lock_status_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (lock_status_int[1]), .SI (lock_status[0]), .SE (scan_en), .Q
       (lock_status[1]));
  SDFFRX1 door_locked_r_reg(.RN (rst_n), .CK (clk), .D
       (door_locked_int), .SI (door_lock_cmd_r), .SE (scan_en), .Q
       (n_4), .QN (door_locked_r_378));
  CLKINVX8 g72(.A (water_pump_on_r_370), .Y (water_pump_on));
  CLKINVX8 g73(.A (water_pump_on_r_370), .Y (system_status[6]));
  CLKINVX8 g48(.A (heater_on_r_368), .Y (heater_on));
  SDFFRHQX8 \volume_level_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (volume_level_int[2]), .SI (volume_level[1]), .SE (scan_en), .Q
       (volume_level[2]));
  SDFFRHQX8 \volume_level_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (volume_level_int[3]), .SI (volume_level[2]), .SE (scan_en), .Q
       (volume_level[3]));
  SDFFRHQX8 \volume_level_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (volume_level_int[1]), .SI (volume_level[0]), .SE (scan_en), .Q
       (volume_level[1]));
  SDFFRHQX8 \volume_level_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (volume_level_int[0]), .SI (volume_cmd_r[3]), .SE (scan_en), .Q
       (volume_level[0]));
  CLKINVX8 g49(.A (heater_on_r_368), .Y (system_status[1]));
  CLKINVX8 g50(.A (cooler_on_r_369), .Y (cooler_on));
  CLKINVX8 g51(.A (cooler_on_r_369), .Y (system_status[0]));
  CLKINVX8 g70(.A (burglar_alarm_out_r_372), .Y (burglar_alarm_out));
  CLKINVX8 g71(.A (burglar_alarm_out_r_372), .Y (system_status[7]));
  SDFFRX1 water_pump_on_r_reg(.RN (rst_n), .CK (clk), .D
       (water_pump_on_int), .SI (water_level_r[3]), .SE (scan_en), .Q
       (n_3), .QN (water_pump_on_r_370));
  SDFFRHQX4 \pin_input_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (pin_input[3]), .SI (pin_input_r[2]), .SE (scan_en), .Q
       (pin_input_r[3]));
  SDFFRHQX4 ac_cmd_r_reg(.RN (rst_n), .CK (clk), .D (ac_cmd), .SI
       (window_state_int[1]), .SE (scan_en), .Q (ac_cmd_r));
  SDFFRHQX8 \visitor_count_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[1]), .SI (visitor_count[0]), .SE (scan_en),
       .Q (visitor_count[1]));
  SDFFRHQX8 \visitor_count_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[5]), .SI (visitor_count[4]), .SE (scan_en),
       .Q (visitor_count[5]));
  SDFFRHQX8 \visitor_count_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[4]), .SI (visitor_count[3]), .SE (scan_en),
       .Q (visitor_count[4]));
  SDFFRHQX8 \visitor_count_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[2]), .SI (visitor_count[1]), .SE (scan_en),
       .Q (visitor_count[2]));
  SDFFRHQX8 \visitor_count_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[3]), .SI (visitor_count[2]), .SE (scan_en),
       .Q (visitor_count[3]));
  SDFFRHQX8 \window_state_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (window_state_int[1]), .SI (window_state[0]), .SE (scan_en), .Q
       (window_state[1]));
  SDFFRHQX8 \visitor_count_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[0]), .SI (tv_on), .SE (scan_en), .Q
       (visitor_count[0]));
  SDFFRHQX8 \window_state_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (window_state_int[0]), .SI (window_sensor_r), .SE (scan_en), .Q
       (window_state[0]));
  SDFFRHQX8 \visitor_count_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[7]), .SI (visitor_count[6]), .SE (scan_en),
       .Q (visitor_count[7]));
  SDFFRHQX8 \visitor_count_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[6]), .SI (visitor_count[5]), .SE (scan_en),
       .Q (visitor_count[6]));
  SDFFRHQX4 window_manual_open_r_reg(.RN (rst_n), .CK (clk), .D
       (window_manual_open), .SI (window_manual_close_r), .SE
       (scan_en), .Q (window_manual_open_r));
  SDFFRHQX4 motion_sensor_r_reg(.RN (rst_n), .CK (clk), .D
       (motion_sensor), .SI (lock_status[1]), .SE (scan_en), .Q
       (motion_sensor_r));
  SDFFRHQX4 \temp_sensor_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[0]), .SI (pin_input_r[3]), .SE (scan_en), .Q
       (temp_sensor_r[0]));
  SDFFRHQX4 \temp_sensor_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[1]), .SI (temp_sensor_r[0]), .SE (scan_en), .Q
       (temp_sensor_r[1]));
  SDFFRHQX4 \temp_sensor_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[2]), .SI (temp_sensor_r[1]), .SE (scan_en), .Q
       (temp_sensor_r[2]));
  SDFFRHQX4 \temp_sensor_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[3]), .SI (temp_sensor_r[2]), .SE (scan_en), .Q
       (temp_sensor_r[3]));
  SDFFRHQX4 \temp_sensor_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[4]), .SI (temp_sensor_r[3]), .SE (scan_en), .Q
       (temp_sensor_r[4]));
  SDFFRHQX4 \temp_sensor_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[5]), .SI (temp_sensor_r[4]), .SE (scan_en), .Q
       (temp_sensor_r[5]));
  SDFFRHQX4 \pin_input_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (pin_input[0]), .SI (music_on), .SE (scan_en), .Q
       (pin_input_r[0]));
  SDFFRHQX4 \temp_sensor_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[7]), .SI (temp_sensor_r[6]), .SE (scan_en), .Q
       (temp_sensor_r[7]));
  SDFFRHQX4 \temp_setpoint_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[7]), .SI (temp_setpoint_r[6]), .SE (scan_en), .Q
       (temp_setpoint_r[7]));
  SDFFRHQX4 \temp_setpoint_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[0]), .SI (temp_sensor_r[7]), .SE (scan_en), .Q
       (temp_setpoint_r[0]));
  SDFFRHQX4 \temp_setpoint_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[2]), .SI (temp_setpoint_r[1]), .SE (scan_en), .Q
       (temp_setpoint_r[2]));
  SDFFRHQX4 \temp_setpoint_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[3]), .SI (temp_setpoint_r[2]), .SE (scan_en), .Q
       (temp_setpoint_r[3]));
  SDFFRHQX4 \temp_setpoint_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[4]), .SI (temp_setpoint_r[3]), .SE (scan_en), .Q
       (temp_setpoint_r[4]));
  SDFFRHQX4 \temp_setpoint_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[6]), .SI (temp_setpoint_r[5]), .SE (scan_en), .Q
       (temp_setpoint_r[6]));
  SDFFRHQX4 window_sensor_r_reg(.RN (rst_n), .CK (clk), .D
       (window_sensor), .SI (window_manual_open_r), .SE (scan_en), .Q
       (window_sensor_r));
  SDFFRHQX4 window_auto_mode_r_reg(.RN (rst_n), .CK (clk), .D
       (window_auto_mode), .SI (water_valve_close), .SE (scan_en), .Q
       (window_auto_mode_r));
  SDFFRHQX4 alarm_arm_r_reg(.RN (rst_n), .CK (clk), .D (alarm_arm), .SI
       (n_6), .SE (scan_en), .Q (alarm_arm_r));
  SDFFRHQX4 door_sensor_r_reg(.RN (rst_n), .CK (clk), .D (door_sensor),
       .SI (n_4), .SE (scan_en), .Q (door_sensor_r));
  SDFFRHQX4 entry_sensor_r_reg(.RN (rst_n), .CK (clk), .D
       (entry_sensor), .SI (door_unlock_cmd_r), .SE (scan_en), .Q
       (entry_sensor_r));
  SDFFRHQX4 exit_sensor_r_reg(.RN (rst_n), .CK (clk), .D (exit_sensor),
       .SI (entry_sensor_r), .SE (scan_en), .Q (exit_sensor_r));
  SDFFRHQX4 \humidity_sensor_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[3]), .SI (humidity_sensor_r[2]), .SE (scan_en),
       .Q (humidity_sensor_r[3]));
  SDFFRHQX4 \pin_input_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (pin_input[2]), .SI (pin_input_r[1]), .SE (scan_en), .Q
       (pin_input_r[2]));
  SDFFRHQX4 \pin_input_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (pin_input[1]), .SI (pin_input_r[0]), .SE (scan_en), .Q
       (pin_input_r[1]));
  SDFFRX1 heater_on_r_reg(.RN (rst_n), .CK (clk), .D (heater_on_int),
       .SI (n_5), .SE (scan_en), .Q (n_2), .QN (heater_on_r_368));
  SDFFRHQX4 \volume_cmd_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (volume_cmd[0]), .SI (visitor_count[7]), .SE (scan_en), .Q
       (volume_cmd_r[0]));
  SDFFRHQX4 \volume_cmd_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (volume_cmd[1]), .SI (volume_cmd_r[0]), .SE (scan_en), .Q
       (volume_cmd_r[1]));
  SDFFRHQX4 door_unlock_cmd_r_reg(.RN (rst_n), .CK (clk), .D
       (door_unlock_cmd), .SI (door_sensor_r), .SE (scan_en), .Q
       (door_unlock_cmd_r));
  SDFFRHQX4 window_manual_close_r_reg(.RN (rst_n), .CK (clk), .D
       (window_manual_close), .SI (window_auto_mode_r), .SE (scan_en),
       .Q (window_manual_close_r));
  SDFFRHQX4 \volume_cmd_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (volume_cmd[2]), .SI (volume_cmd_r[1]), .SE (scan_en), .Q
       (volume_cmd_r[2]));
  SDFFRHQX4 door_lock_cmd_r_reg(.RN (rst_n), .CK (clk), .D
       (door_lock_cmd), .SI (dehumidifier_on), .SE (scan_en), .Q
       (door_lock_cmd_r));
  SDFFRHQX4 \humidity_sensor_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[6]), .SI (humidity_sensor_r[5]), .SE (scan_en),
       .Q (humidity_sensor_r[6]));
  SDFFRHQX4 light_cmd_r_reg(.RN (rst_n), .CK (clk), .D (light_cmd), .SI
       (led_brightness[7]), .SE (scan_en), .Q (light_cmd_r));
  SDFFRHQX4 \humidity_sensor_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[0]), .SI (humidifier_on), .SE (scan_en), .Q
       (humidity_sensor_r[0]));
  SDFFRHQX4 \volume_cmd_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (volume_cmd[3]), .SI (volume_cmd_r[2]), .SE (scan_en), .Q
       (volume_cmd_r[3]));
  SDFFRHQX4 \temp_setpoint_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[1]), .SI (temp_setpoint_r[0]), .SE (scan_en), .Q
       (temp_setpoint_r[1]));
  SDFFRHQX4 \temp_setpoint_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[5]), .SI (temp_setpoint_r[4]), .SE (scan_en), .Q
       (temp_setpoint_r[5]));
  SDFFRHQX4 \water_level_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (water_level[0]), .SI (volume_level[3]), .SE (scan_en), .Q
       (water_level_r[0]));
  SDFFRHQX4 \temp_sensor_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[6]), .SI (temp_sensor_r[5]), .SE (scan_en), .Q
       (temp_sensor_r[6]));
  SDFFRHQX4 fan_cmd_r_reg(.RN (rst_n), .CK (clk), .D (fan_cmd), .SI
       (exit_sensor_r), .SE (scan_en), .Q (fan_cmd_r));
  SDFFRHQX4 \humidity_sensor_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[1]), .SI (humidity_sensor_r[0]), .SE (scan_en),
       .Q (DFT_sdo_1));
  SDFFRHQX4 \humidity_sensor_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[2]), .SI (DFT_sdi_2), .SE (scan_en), .Q
       (humidity_sensor_r[2]));
  SDFFRHQX4 \humidity_sensor_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[4]), .SI (humidity_sensor_r[3]), .SE (scan_en),
       .Q (humidity_sensor_r[4]));
  SDFFRHQX4 \humidity_sensor_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[5]), .SI (humidity_sensor_r[4]), .SE (scan_en),
       .Q (humidity_sensor_r[5]));
  SDFFRHQX4 \humidity_sensor_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[7]), .SI (humidity_sensor_r[6]), .SE (scan_en),
       .Q (humidity_sensor_r[7]));
  SDFFRHQX4 music_on_cmd_r_reg(.RN (rst_n), .CK (clk), .D
       (music_on_cmd), .SI (motion_sensor_r), .SE (scan_en), .Q
       (music_on_cmd_r));
  SDFFRHQX4 tv_on_cmd_r_reg(.RN (rst_n), .CK (clk), .D (tv_on_cmd), .SI
       (temp_setpoint_r[7]), .SE (scan_en), .Q (tv_on_cmd_r));
  SDFFRHQX4 \water_level_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (water_level[3]), .SI (water_level_r[2]), .SE (scan_en), .Q
       (water_level_r[3]));
  SDFFRHQX4 \water_level_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (water_level[1]), .SI (water_level_r[0]), .SE (scan_en), .Q
       (water_level_r[1]));
  SDFFRHQX4 \water_level_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (water_level[2]), .SI (water_level_r[1]), .SE (scan_en), .Q
       (water_level_r[2]));
  SDFFRX1 burglar_alarm_out_r_reg(.RN (rst_n), .CK (clk), .D
       (burglar_alarm_out_int), .SI (alarm_arm_r), .SE (scan_en), .Q
       (n_1), .QN (burglar_alarm_out_r_372));
  SDFFRHQX4 \light_sensor_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (light_sensor[5]), .SI (light_sensor_r[4]), .SE (scan_en), .Q
       (light_sensor_r[5]));
  SDFFRHQX4 \light_sensor_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (light_sensor[6]), .SI (light_sensor_r[5]), .SE (scan_en), .Q
       (light_sensor_r[6]));
  SDFFRHQX4 \light_sensor_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (light_sensor[4]), .SI (light_sensor_r[3]), .SE (scan_en), .Q
       (light_sensor_r[4]));
  SDFFRHQX4 \light_sensor_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (light_sensor[3]), .SI (light_sensor_r[2]), .SE (scan_en), .Q
       (light_sensor_r[3]));
  SDFFRX1 cooler_on_r_reg(.RN (rst_n), .CK (clk), .D (cooler_on_int),
       .SI (n_1), .SE (scan_en), .Q (n_0), .QN (cooler_on_r_369));
  SDFFRHQX4 \light_sensor_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (light_sensor[1]), .SI (light_sensor_r[0]), .SE (scan_en), .Q
       (light_sensor_r[1]));
  SDFFRHQX4 \light_sensor_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (light_sensor[2]), .SI (light_sensor_r[1]), .SE (scan_en), .Q
       (light_sensor_r[2]));
  SDFFRHQX4 \light_sensor_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (light_sensor[7]), .SI (light_sensor_r[6]), .SE (scan_en), .Q
       (light_sensor_r[7]));
  SDFFRHQX4 \light_sensor_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (light_sensor[0]), .SI (light_cmd_r), .SE (scan_en), .Q
       (light_sensor_r[0]));
endmodule
