# ####################################################################

#  Created by Genus(TM) Synthesis Solution 19.13-s073_1 on Tue Nov 18 12:22:11 IST 2025

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design HA

create_clock -name "clk" -period 5.0 -waveform {0.0 2.0} [get_ports clk]
set_clock_transition -rise -min 0.01 [get_clocks clk]
set_clock_transition -rise -max 0.02 [get_clocks clk]
set_clock_transition -fall 0.05 [get_clocks clk]
set_clock_gating_check -setup 0.0 
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports heater_on]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports cooler_on]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports water_pump_on]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports water_valve_close]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {led_brightness[7]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {led_brightness[6]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {led_brightness[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {led_brightness[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {led_brightness[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {led_brightness[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {led_brightness[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {led_brightness[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports burglar_alarm_out]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {visitor_count[7]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {visitor_count[6]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {visitor_count[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {visitor_count[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {visitor_count[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {visitor_count[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {visitor_count[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {visitor_count[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {window_state[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {window_state[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports tv_on]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports music_on]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {volume_level[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {volume_level[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {volume_level[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {volume_level[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports ac_on]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports fan_on]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports lights_on]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports door_locked]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {lock_status[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {lock_status[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports humidifier_on]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports dehumidifier_on]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {system_status[7]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {system_status[6]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {system_status[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {system_status[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {system_status[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {system_status[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {system_status[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {system_status[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports rst_n]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {temp_sensor[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {temp_sensor[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {temp_sensor[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {temp_sensor[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {temp_sensor[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {temp_sensor[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {temp_sensor[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {temp_sensor[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {temp_setpoint[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {temp_setpoint[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {temp_setpoint[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {temp_setpoint[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {temp_setpoint[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {temp_setpoint[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {temp_setpoint[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {temp_setpoint[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {water_level[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {water_level[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {water_level[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {water_level[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {light_sensor[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {light_sensor[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {light_sensor[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {light_sensor[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {light_sensor[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {light_sensor[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {light_sensor[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {light_sensor[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports motion_sensor]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports door_sensor]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports window_sensor]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports alarm_arm]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports entry_sensor]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports exit_sensor]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports window_auto_mode]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports window_manual_open]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports window_manual_close]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports tv_on_cmd]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports music_on_cmd]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {volume_cmd[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {volume_cmd[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {volume_cmd[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {volume_cmd[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports ac_cmd]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports fan_cmd]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports light_cmd]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports door_lock_cmd]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports door_unlock_cmd]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {pin_input[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {pin_input[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {pin_input[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {pin_input[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {humidity_sensor[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {humidity_sensor[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {humidity_sensor[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {humidity_sensor[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {humidity_sensor[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {humidity_sensor[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {humidity_sensor[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {humidity_sensor[0]}]
set_wire_load_mode "enclosed"
set_clock_uncertainty -setup 0.1 [get_clocks clk]
set_clock_uncertainty -hold 0.1 [get_clocks clk]
