
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Nov 18 2025 12:26:56 IST (Nov 18 2025 06:56:56 UTC)

// Verification Directory fv/HA 

module appliances_controller(clk, rst_n, ac_cmd, fan_cmd, light_cmd,
     ac_on, fan_on, lights_on);
  input clk, rst_n, ac_cmd, fan_cmd, light_cmd;
  output ac_on, fan_on, lights_on;
  wire clk, rst_n, ac_cmd, fan_cmd, light_cmd;
  wire ac_on, fan_on, lights_on;
  DFFRHQX1 ac_on_reg(.RN (rst_n), .CK (clk), .D (ac_cmd), .Q (ac_on));
  DFFRHQX1 fan_on_reg(.RN (rst_n), .CK (clk), .D (fan_cmd), .Q
       (fan_on));
  DFFRHQX1 lights_on_reg(.RN (rst_n), .CK (clk), .D (light_cmd), .Q
       (lights_on));
endmodule

module burglar_alarm(clk, rst_n, motion_sensor, door_sensor,
     window_sensor, alarm_arm, alarm_out);
  input clk, rst_n, motion_sensor, door_sensor, window_sensor,
       alarm_arm;
  output alarm_out;
  wire clk, rst_n, motion_sensor, door_sensor, window_sensor, alarm_arm;
  wire alarm_out;
  wire [8:0] delay_counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34;
  DFFRHQX1 \delay_counter_reg[8] (.RN (rst_n), .CK (clk), .D (n_31), .Q
       (delay_counter[8]));
  DFFRHQX1 \delay_counter_reg[5] (.RN (rst_n), .CK (clk), .D (n_32), .Q
       (delay_counter[5]));
  OAI32X1 g686(.A0 (delay_counter[6]), .A1 (n_26), .A2 (n_12), .B0
       (n_2), .B1 (n_30), .Y (n_34));
  OAI22X1 g687(.A0 (n_3), .A1 (n_30), .B0 (n_12), .B1 (n_29), .Y
       (n_33));
  SDFFRHQX1 \delay_counter_reg[4] (.RN (rst_n), .CK (clk), .D (n_20),
       .SI (n_22), .SE (delay_counter[4]), .Q (delay_counter[4]));
  AO22XL g689(.A0 (delay_counter[5]), .A1 (n_27), .B0
       (delay_counter[4]), .B1 (n_24), .Y (n_32));
  AO22XL g690(.A0 (delay_counter[8]), .A1 (n_28), .B0 (n_6), .B1
       (n_20), .Y (n_31));
  AOI21X1 g691(.A0 (n_26), .A1 (n_11), .B0 (n_14), .Y (n_30));
  AOI32X1 g692(.A0 (delay_counter[6]), .A1 (n_3), .A2 (n_25), .B0
       (delay_counter[7]), .B1 (n_2), .Y (n_29));
  DFFRHQX1 \delay_counter_reg[3] (.RN (rst_n), .CK (clk), .D (n_21), .Q
       (delay_counter[3]));
  NAND2XL g694(.A (n_12), .B (n_23), .Y (n_28));
  OAI21XL g695(.A0 (n_12), .A1 (delay_counter[4]), .B0 (n_23), .Y
       (n_27));
  INVXL g696(.A (n_26), .Y (n_25));
  NOR2BXL g697(.AN (n_20), .B (delay_counter[5]), .Y (n_24));
  NAND3X1 g698(.A (delay_counter[4]), .B (delay_counter[5]), .C (n_0),
       .Y (n_26));
  CLKINVX1 g699(.A (n_22), .Y (n_23));
  AO22XL g700(.A0 (n_18), .A1 (n_11), .B0 (delay_counter[3]), .B1
       (n_14), .Y (n_21));
  OAI21X1 g701(.A0 (n_0), .A1 (n_12), .B0 (n_13), .Y (n_22));
  NOR2BX1 g702(.AN (n_0), .B (n_12), .Y (n_20));
  DFFRHQX1 \delay_counter_reg[1] (.RN (rst_n), .CK (clk), .D (n_17), .Q
       (delay_counter[1]));
  DFFRHQX1 alarm_out_reg(.RN (rst_n), .CK (clk), .D (n_19), .Q
       (alarm_out));
  SDFFRHQX1 \delay_counter_reg[0] (.RN (rst_n), .CK (clk), .D (n_11),
       .SI (n_14), .SE (delay_counter[0]), .Q (delay_counter[0]));
  OAI2BB1XL g707(.A0N (alarm_out), .A1N (n_11), .B0 (n_13), .Y (n_19));
  OAI21X1 g708(.A0 (delay_counter[3]), .A1 (n_8), .B0 (n_15), .Y
       (n_18));
  AO22XL g709(.A0 (n_5), .A1 (n_11), .B0 (delay_counter[1]), .B1
       (n_14), .Y (n_17));
  OAI22X1 g710(.A0 (n_9), .A1 (n_12), .B0 (n_1), .B1 (n_13), .Y (n_16));
  NAND2XL g711(.A (delay_counter[3]), .B (n_8), .Y (n_15));
  CLKINVX1 g713(.A (n_14), .Y (n_13));
  NOR2XL g714(.A (n_7), .B (n_10), .Y (n_14));
  CLKINVX1 g715(.A (n_12), .Y (n_11));
  NAND2BX1 g716(.AN (n_7), .B (n_10), .Y (n_12));
  OAI211X1 g717(.A0 (delay_counter[2]), .A1 (delay_counter[3]), .B0
       (delay_counter[8]), .C0 (n_6), .Y (n_10));
  MXI2XL g718(.A (n_1), .B (delay_counter[2]), .S0 (n_4), .Y (n_9));
  OR2X1 g719(.A (n_1), .B (n_4), .Y (n_8));
  OAI31X1 g720(.A0 (window_sensor), .A1 (motion_sensor), .A2
       (door_sensor), .B0 (alarm_arm), .Y (n_7));
  AND4XL g721(.A (delay_counter[7]), .B (delay_counter[5]), .C
       (delay_counter[6]), .D (delay_counter[4]), .Y (n_6));
  XOR2XL g722(.A (delay_counter[0]), .B (delay_counter[1]), .Y (n_5));
  NAND2XL g723(.A (delay_counter[0]), .B (delay_counter[1]), .Y (n_4));
  NOR2BX1 g2(.AN (delay_counter[3]), .B (n_8), .Y (n_0));
  DFFRX1 \delay_counter_reg[7] (.RN (rst_n), .CK (clk), .D (n_33), .Q
       (delay_counter[7]), .QN (n_3));
  DFFRX1 \delay_counter_reg[6] (.RN (rst_n), .CK (clk), .D (n_34), .Q
       (delay_counter[6]), .QN (n_2));
  DFFRX1 \delay_counter_reg[2] (.RN (rst_n), .CK (clk), .D (n_16), .Q
       (delay_counter[2]), .QN (n_1));
endmodule

module door_lock_controller(clk, rst_n, lock_cmd, unlock_cmd,
     pin_input, door_locked, lock_status);
  input clk, rst_n, lock_cmd, unlock_cmd;
  input [3:0] pin_input;
  output door_locked;
  output [1:0] lock_status;
  wire clk, rst_n, lock_cmd, unlock_cmd;
  wire [3:0] pin_input;
  wire door_locked;
  wire [1:0] lock_status;
  wire [1:0] state;
  wire [7:0] timeout_counter;
  wire [2:0] attempt_counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  DFFRHQX1 door_locked_reg(.RN (rst_n), .CK (clk), .D (n_54), .Q
       (door_locked));
  DFFRHQX1 \lock_status_reg[1] (.RN (rst_n), .CK (clk), .D (state[1]),
       .Q (lock_status[1]));
  DFFRHQX1 \lock_status_reg[0] (.RN (rst_n), .CK (clk), .D (state[0]),
       .Q (lock_status[0]));
  OR2XL g754(.A (state[0]), .B (state[1]), .Y (n_54));
  DFFRHQX1 \timeout_counter_reg[7] (.RN (rst_n), .CK (clk), .D (n_53),
       .Q (timeout_counter[7]));
  DFFRHQX1 \timeout_counter_reg[6] (.RN (rst_n), .CK (clk), .D (n_51),
       .Q (timeout_counter[6]));
  NOR2XL g2228(.A (n_29), .B (n_52), .Y (n_53));
  AOI21XL g2229(.A0 (timeout_counter[6]), .A1 (n_48), .B0
       (timeout_counter[7]), .Y (n_52));
  NOR2XL g2230(.A (n_29), .B (n_50), .Y (n_51));
  DFFRHQX1 \timeout_counter_reg[5] (.RN (rst_n), .CK (clk), .D (n_49),
       .Q (timeout_counter[5]));
  MXI2XL g2232(.A (n_48), .B (n_45), .S0 (timeout_counter[6]), .Y
       (n_50));
  NOR2XL g2233(.A (n_47), .B (n_29), .Y (n_49));
  CLKINVX1 g2234(.A (n_45), .Y (n_48));
  DFFRHQX1 \timeout_counter_reg[4] (.RN (rst_n), .CK (clk), .D (n_44),
       .Q (timeout_counter[4]));
  AOI21XL g2236(.A0 (timeout_counter[5]), .A1 (n_41), .B0 (n_46), .Y
       (n_47));
  NOR2XL g2237(.A (timeout_counter[5]), .B (n_41), .Y (n_46));
  NOR2XL g2238(.A (n_43), .B (n_29), .Y (n_44));
  NAND2BX1 g2239(.AN (n_41), .B (timeout_counter[5]), .Y (n_45));
  DFFRHQX1 \timeout_counter_reg[3] (.RN (rst_n), .CK (clk), .D (n_40),
       .Q (timeout_counter[3]));
  AOI21XL g2241(.A0 (timeout_counter[4]), .A1 (n_30), .B0 (n_42), .Y
       (n_43));
  NOR2XL g2242(.A (timeout_counter[4]), .B (n_30), .Y (n_42));
  NOR2XL g2243(.A (n_35), .B (n_29), .Y (n_40));
  NAND2BX1 g2244(.AN (n_30), .B (timeout_counter[4]), .Y (n_41));
  DFFRHQX1 \timeout_counter_reg[1] (.RN (rst_n), .CK (clk), .D (n_39),
       .Q (timeout_counter[1]));
  DFFRHQX1 \timeout_counter_reg[2] (.RN (rst_n), .CK (clk), .D (n_34),
       .Q (timeout_counter[2]));
  DFFRHQX1 \timeout_counter_reg[0] (.RN (rst_n), .CK (clk), .D (n_38),
       .Q (timeout_counter[0]));
  NOR2XL g2252(.A (n_11), .B (n_29), .Y (n_39));
  NOR2XL g2253(.A (timeout_counter[0]), .B (n_29), .Y (n_38));
  NAND2XL g2254(.A (n_18), .B (n_29), .Y (n_37));
  AO21X1 g2255(.A0 (attempt_counter[0]), .A1 (n_27), .B0 (n_23), .Y
       (n_36));
  AOI21X1 g2256(.A0 (timeout_counter[3]), .A1 (n_20), .B0 (n_31), .Y
       (n_35));
  NOR2XL g2257(.A (n_21), .B (n_29), .Y (n_34));
  OAI221X1 g2258(.A0 (n_1), .A1 (n_25), .B0 (state[0]), .B1 (n_9), .C0
       (n_22), .Y (n_33));
  OAI21X1 g2259(.A0 (n_15), .A1 (n_18), .B0 (n_28), .Y (n_32));
  NOR2XL g2260(.A (timeout_counter[3]), .B (n_20), .Y (n_31));
  NAND2XL g2262(.A (attempt_counter[1]), .B (n_27), .Y (n_28));
  NAND2BX1 g2263(.AN (n_20), .B (timeout_counter[3]), .Y (n_30));
  OAI21X1 g2264(.A0 (n_24), .A1 (n_25), .B0 (state[1]), .Y (n_29));
  OAI21X1 g2265(.A0 (n_3), .A1 (n_18), .B0 (n_12), .Y (n_27));
  OAI32X1 g2266(.A0 (n_2), .A1 (n_7), .A2 (n_16), .B0 (n_3), .B1
       (n_12), .Y (n_26));
  AOI31X1 g2267(.A0 (timeout_counter[7]), .A1 (timeout_counter[6]), .A2
       (n_0), .B0 (n_2), .Y (n_24));
  AOI31X1 g2268(.A0 (timeout_counter[5]), .A1 (timeout_counter[6]), .A2
       (n_14), .B0 (timeout_counter[7]), .Y (n_25));
  AOI211X1 g2269(.A0 (attempt_counter[1]), .A1 (attempt_counter[2]),
       .B0 (attempt_counter[0]), .C0 (n_18), .Y (n_23));
  NAND2XL g2270(.A (state[0]), .B (n_17), .Y (n_22));
  AOI21XL g2271(.A0 (timeout_counter[2]), .A1 (n_6), .B0 (n_19), .Y
       (n_21));
  NOR2XL g2272(.A (timeout_counter[2]), .B (n_6), .Y (n_19));
  NAND2BX1 g2273(.AN (n_6), .B (timeout_counter[2]), .Y (n_20));
  NAND2BXL g2274(.AN (n_7), .B (n_16), .Y (n_17));
  NAND3BX1 g2275(.AN (n_7), .B (n_13), .C (state[0]), .Y (n_18));
  OAI2BB1X1 g2276(.A0N (n_3), .A1N (n_10), .B0 (n_13), .Y (n_16));
  AOI32X1 g2277(.A0 (attempt_counter[0]), .A1 (n_3), .A2 (n_4), .B0
       (attempt_counter[1]), .B1 (n_5), .Y (n_15));
  NAND2BX1 g2279(.AN (timeout_counter[2]), .B (n_8), .Y (n_14));
  XNOR2XL g2280(.A (timeout_counter[0]), .B (timeout_counter[1]), .Y
       (n_11));
  NAND4BXL g2281(.AN (pin_input[3]), .B (pin_input[0]), .C
       (pin_input[1]), .D (pin_input[2]), .Y (n_13));
  AOI2BB1X1 g2282(.A0N (unlock_cmd), .A1N (n_2), .B0 (state[1]), .Y
       (n_12));
  NAND2XL g2283(.A (attempt_counter[0]), .B (attempt_counter[1]), .Y
       (n_10));
  NAND2XL g2284(.A (lock_cmd), .B (n_1), .Y (n_9));
  NOR2XL g2285(.A (timeout_counter[3]), .B (timeout_counter[4]), .Y
       (n_8));
  NAND2XL g2286(.A (unlock_cmd), .B (n_1), .Y (n_7));
  NAND2XL g2287(.A (timeout_counter[0]), .B (timeout_counter[1]), .Y
       (n_6));
  NAND2BX1 g2(.AN (timeout_counter[5]), .B (n_8), .Y (n_0));
  DFFRX1 \attempt_counter_reg[0] (.RN (rst_n), .CK (clk), .D (n_36), .Q
       (attempt_counter[0]), .QN (n_5));
  DFFRX1 \state_reg[0] (.RN (rst_n), .CK (clk), .D (n_33), .Q
       (state[0]), .QN (n_2));
  DFFRX1 \attempt_counter_reg[1] (.RN (rst_n), .CK (clk), .D (n_32), .Q
       (attempt_counter[1]), .QN (n_4));
  DFFRX1 \attempt_counter_reg[2] (.RN (rst_n), .CK (clk), .D (n_26), .Q
       (attempt_counter[2]), .QN (n_3));
  DFFRX1 \state_reg[1] (.RN (rst_n), .CK (clk), .D (n_37), .Q
       (state[1]), .QN (n_1));
endmodule

module entertainment_system(clk, rst_n, tv_on_cmd, music_on_cmd,
     volume_cmd, tv_on, music_on, volume_level);
  input clk, rst_n, tv_on_cmd, music_on_cmd;
  input [3:0] volume_cmd;
  output tv_on, music_on;
  output [3:0] volume_level;
  wire clk, rst_n, tv_on_cmd, music_on_cmd;
  wire [3:0] volume_cmd;
  wire tv_on, music_on;
  wire [3:0] volume_level;
  wire n_0;
  DFFRHQX1 tv_on_reg(.RN (rst_n), .CK (clk), .D (tv_on_cmd), .Q
       (tv_on));
  DFFRHQX1 music_on_reg(.RN (rst_n), .CK (clk), .D (music_on_cmd), .Q
       (music_on));
  SDFFSHQX1 \volume_level_reg[0] (.SN (rst_n), .CK (clk), .D
       (volume_cmd[0]), .SI (volume_level[0]), .SE (n_0), .Q
       (volume_level[0]));
  SDFFSHQX1 \volume_level_reg[2] (.SN (rst_n), .CK (clk), .D
       (volume_cmd[2]), .SI (volume_level[2]), .SE (n_0), .Q
       (volume_level[2]));
  SDFFRHQX1 \volume_level_reg[1] (.RN (rst_n), .CK (clk), .D
       (volume_cmd[1]), .SI (volume_level[1]), .SE (n_0), .Q
       (volume_level[1]));
  SDFFRHQX1 \volume_level_reg[3] (.RN (rst_n), .CK (clk), .D
       (volume_cmd[3]), .SI (volume_level[3]), .SE (n_0), .Q
       (volume_level[3]));
  NOR4X1 g53(.A (volume_cmd[1]), .B (volume_cmd[0]), .C
       (volume_cmd[3]), .D (volume_cmd[2]), .Y (n_0));
endmodule

module humidity_controller(clk, rst_n, humidity_sensor, humidifier_on,
     dehumidifier_on);
  input clk, rst_n;
  input [7:0] humidity_sensor;
  output humidifier_on, dehumidifier_on;
  wire clk, rst_n;
  wire [7:0] humidity_sensor;
  wire humidifier_on, dehumidifier_on;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  DFFRHQX1 dehumidifier_on_reg(.RN (rst_n), .CK (clk), .D (n_5), .Q
       (dehumidifier_on));
  AOI21XL g204(.A0 (n_0), .A1 (n_4), .B0 (n_2), .Y (n_5));
  DFFRHQX1 humidifier_on_reg(.RN (rst_n), .CK (clk), .D (n_3), .Q
       (humidifier_on));
  OAI211X1 g206(.A0 (humidity_sensor[1]), .A1 (humidity_sensor[0]), .B0
       (humidity_sensor[2]), .C0 (humidity_sensor[3]), .Y (n_4));
  AOI21X1 g207(.A0 (humidity_sensor[5]), .A1 (humidity_sensor[3]), .B0
       (n_1), .Y (n_3));
  INVXL g208(.A (n_1), .Y (n_2));
  OAI2BB1X1 g209(.A0N (humidity_sensor[4]), .A1N (humidity_sensor[5]),
       .B0 (n_0), .Y (n_1));
  NOR2XL g210(.A (humidity_sensor[7]), .B (humidity_sensor[6]), .Y
       (n_0));
endmodule

module luminosity_controller(clk, rst_n, light_sensor, led_brightness);
  input clk, rst_n;
  input [7:0] light_sensor;
  output [7:0] led_brightness;
  wire clk, rst_n;
  wire [7:0] light_sensor;
  wire [7:0] led_brightness;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  DFFRHQX1 \led_brightness_reg[4] (.RN (rst_n), .CK (clk), .D (n_5), .Q
       (led_brightness[4]));
  DFFRHQX1 \led_brightness_reg[6] (.RN (rst_n), .CK (clk), .D (n_6), .Q
       (led_brightness[6]));
  DFFRHQX1 \led_brightness_reg[7] (.RN (rst_n), .CK (clk), .D (n_7), .Q
       (led_brightness[7]));
  DFFRHQX1 \led_brightness_reg[0] (.RN (rst_n), .CK (clk), .D (n_4), .Q
       (led_brightness[0]));
  DFFRHQX1 \led_brightness_reg[2] (.RN (rst_n), .CK (clk), .D (n_0), .Q
       (led_brightness[2]));
  DFFRHQX1 \led_brightness_reg[5] (.RN (rst_n), .CK (clk), .D (n_1), .Q
       (led_brightness[5]));
  DFFRHQX1 \led_brightness_reg[3] (.RN (rst_n), .CK (clk), .D (n_2), .Q
       (led_brightness[3]));
  DFFRHQX1 \led_brightness_reg[1] (.RN (rst_n), .CK (clk), .D (n_3), .Q
       (led_brightness[1]));
  INVXL g95(.A (light_sensor[7]), .Y (n_7));
  INVXL g96(.A (light_sensor[6]), .Y (n_6));
  INVXL g97(.A (light_sensor[4]), .Y (n_5));
  INVXL g98(.A (light_sensor[0]), .Y (n_4));
  INVXL g99(.A (light_sensor[1]), .Y (n_3));
  INVXL g100(.A (light_sensor[3]), .Y (n_2));
  INVXL g101(.A (light_sensor[5]), .Y (n_1));
  INVXL g102(.A (light_sensor[2]), .Y (n_0));
endmodule

module temperature_controller(clk, rst_n, temp_sensor, temp_setpoint,
     heater_on, cooler_on);
  input clk, rst_n;
  input [7:0] temp_sensor, temp_setpoint;
  output heater_on, cooler_on;
  wire clk, rst_n;
  wire [7:0] temp_sensor, temp_setpoint;
  wire heater_on, cooler_on;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  SDFFRHQX1 cooler_on_reg(.RN (rst_n), .CK (clk), .D (n_66), .SI
       (n_39), .SE (n_69), .Q (cooler_on));
  DFFRHQX1 heater_on_reg(.RN (rst_n), .CK (clk), .D (n_70), .Q
       (heater_on));
  MXI2XL g2427(.A (n_66), .B (n_40), .S0 (n_69), .Y (n_70));
  NOR2BX1 g2428(.AN (n_66), .B (n_68), .Y (n_69));
  AOI211X1 g2429(.A0 (n_58), .A1 (n_61), .B0 (n_65), .C0 (n_67), .Y
       (n_68));
  OAI32X1 g2430(.A0 (temp_sensor[4]), .A1 (n_34), .A2 (n_62), .B0
       (temp_sensor[5]), .B1 (n_63), .Y (n_67));
  OAI2BB1X1 g2431(.A0N (temp_sensor[7]), .A1N (n_60), .B0 (n_64), .Y
       (n_66));
  AOI211X1 g2432(.A0 (temp_sensor[4]), .A1 (n_34), .B0 (n_44), .C0
       (n_62), .Y (n_65));
  OAI222XL g2433(.A0 (temp_setpoint[7]), .A1 (n_54), .B0
       (temp_sensor[7]), .B1 (n_60), .C0 (n_50), .C1 (n_8), .Y (n_64));
  NAND2XL g2434(.A (n_46), .B (n_59), .Y (n_63));
  OAI21X1 g2435(.A0 (n_4), .A1 (n_46), .B0 (n_59), .Y (n_62));
  OAI31X1 g2436(.A0 (temp_sensor[7]), .A1 (temp_sensor[6]), .A2 (n_51),
       .B0 (n_56), .Y (n_61));
  OAI2BB1X1 g2437(.A0N (temp_sensor[6]), .A1N (n_52), .B0 (n_57), .Y
       (n_60));
  AOI22X1 g2438(.A0 (temp_sensor[6]), .A1 (n_51), .B0 (temp_sensor[7]),
       .B1 (n_56), .Y (n_59));
  OAI21X1 g2439(.A0 (temp_sensor[6]), .A1 (n_51), .B0 (temp_sensor[7]),
       .Y (n_58));
  OAI21X1 g2440(.A0 (temp_sensor[6]), .A1 (n_52), .B0 (n_55), .Y
       (n_57));
  AOI21X1 g2441(.A0 (temp_setpoint[6]), .A1 (n_43), .B0
       (temp_setpoint[7]), .Y (n_56));
  OAI21X1 g2442(.A0 (n_4), .A1 (n_47), .B0 (n_53), .Y (n_55));
  INVXL g2443(.A (n_50), .Y (n_54));
  OAI211X1 g2444(.A0 (temp_sensor[4]), .A1 (n_33), .B0 (n_49), .C0
       (n_48), .Y (n_53));
  AOI21XL g2445(.A0 (temp_setpoint[6]), .A1 (n_41), .B0 (n_50), .Y
       (n_52));
  MXI2XL g2446(.A (temp_setpoint[6]), .B (n_2), .S0 (n_43), .Y (n_51));
  NOR2XL g2447(.A (temp_setpoint[6]), .B (n_41), .Y (n_50));
  NAND2XL g2448(.A (n_4), .B (n_47), .Y (n_49));
  OAI211X1 g2449(.A0 (n_7), .A1 (n_38), .B0 (n_42), .C0 (n_45), .Y
       (n_48));
  OAI21X1 g2450(.A0 (n_3), .A1 (n_30), .B0 (n_41), .Y (n_47));
  AOI21X1 g2451(.A0 (n_3), .A1 (n_29), .B0 (n_43), .Y (n_46));
  OAI221X1 g2452(.A0 (temp_sensor[3]), .A1 (n_37), .B0 (n_6), .B1
       (n_12), .C0 (n_21), .Y (n_45));
  AOI221X1 g2453(.A0 (n_11), .A1 (n_31), .B0 (n_7), .B1 (n_23), .C0
       (n_35), .Y (n_44));
  NAND2XL g2454(.A (temp_sensor[4]), .B (n_33), .Y (n_42));
  NOR2XL g2455(.A (n_3), .B (n_29), .Y (n_43));
  NAND2XL g2456(.A (n_36), .B (heater_on), .Y (n_40));
  AND2X1 g2457(.A (n_36), .B (cooler_on), .Y (n_39));
  NAND2XL g2458(.A (n_3), .B (n_30), .Y (n_41));
  INVXL g2459(.A (n_37), .Y (n_38));
  OAI2BB1X1 g2460(.A0N (temp_sensor[2]), .A1N (n_26), .B0 (n_32), .Y
       (n_37));
  NOR3X1 g2461(.A (temp_sensor[2]), .B (n_20), .C (n_28), .Y (n_35));
  NAND4XL g2462(.A (n_15), .B (n_18), .C (n_0), .D (n_27), .Y (n_36));
  OAI21X1 g2463(.A0 (temp_setpoint[4]), .A1 (n_22), .B0 (n_29), .Y
       (n_34));
  AOI21X1 g2464(.A0 (temp_setpoint[4]), .A1 (n_21), .B0 (n_30), .Y
       (n_33));
  OAI21X1 g2465(.A0 (temp_sensor[2]), .A1 (n_26), .B0 (n_19), .Y
       (n_32));
  AOI211X1 g2466(.A0 (temp_sensor[2]), .A1 (n_20), .B0 (n_25), .C0
       (n_28), .Y (n_31));
  NOR2XL g2467(.A (temp_setpoint[4]), .B (n_21), .Y (n_30));
  NAND2XL g2468(.A (temp_setpoint[4]), .B (n_22), .Y (n_29));
  NOR3X1 g2469(.A (n_16), .B (n_1), .C (n_24), .Y (n_27));
  NOR2XL g2470(.A (n_7), .B (n_23), .Y (n_28));
  AOI31X1 g2471(.A0 (temp_setpoint[0]), .A1 (n_5), .A2 (n_11), .B0
       (n_13), .Y (n_26));
  NOR3X1 g2472(.A (temp_setpoint[0]), .B (n_5), .C (n_13), .Y (n_25));
  OAI211X1 g2473(.A0 (n_13), .A1 (n_10), .B0 (n_14), .C0 (n_17), .Y
       (n_24));
  AOI21X1 g2474(.A0 (n_6), .A1 (n_9), .B0 (n_22), .Y (n_23));
  INVX1 g2475(.A (n_19), .Y (n_20));
  MXI2XL g2476(.A (temp_sensor[0]), .B (n_5), .S0 (temp_setpoint[0]),
       .Y (n_18));
  NOR2XL g2478(.A (n_6), .B (n_9), .Y (n_22));
  NAND2XL g2479(.A (n_6), .B (n_12), .Y (n_21));
  NOR2BX1 g2480(.AN (n_9), .B (n_12), .Y (n_19));
  MXI2XL g2481(.A (temp_setpoint[6]), .B (n_2), .S0 (temp_sensor[6]),
       .Y (n_17));
  MXI2XL g2482(.A (n_8), .B (temp_setpoint[7]), .S0 (temp_sensor[7]),
       .Y (n_16));
  OAI22X1 g2483(.A0 (temp_sensor[3]), .A1 (temp_setpoint[3]), .B0
       (n_7), .B1 (n_6), .Y (n_15));
  AOI22X1 g2485(.A0 (temp_sensor[5]), .A1 (n_3), .B0
       (temp_setpoint[5]), .B1 (n_4), .Y (n_14));
  NOR2XL g2486(.A (temp_sensor[1]), .B (temp_setpoint[1]), .Y (n_13));
  NOR2XL g2487(.A (temp_setpoint[1]), .B (temp_setpoint[2]), .Y (n_12));
  INVXL g2488(.A (n_11), .Y (n_10));
  NAND2XL g2489(.A (temp_sensor[1]), .B (temp_setpoint[1]), .Y (n_11));
  NAND2XL g2490(.A (temp_setpoint[1]), .B (temp_setpoint[2]), .Y (n_9));
  CLKINVX1 g2491(.A (temp_setpoint[7]), .Y (n_8));
  CLKINVX1 g2492(.A (temp_sensor[3]), .Y (n_7));
  CLKINVX1 g2494(.A (temp_setpoint[3]), .Y (n_6));
  CLKINVX1 g2495(.A (temp_sensor[0]), .Y (n_5));
  CLKINVX1 g2497(.A (temp_sensor[5]), .Y (n_4));
  CLKINVX1 g2498(.A (temp_setpoint[5]), .Y (n_3));
  CLKINVX1 g2499(.A (temp_setpoint[6]), .Y (n_2));
  XOR2XL g2(.A (temp_sensor[4]), .B (temp_setpoint[4]), .Y (n_1));
  XNOR2XL g2500(.A (temp_sensor[2]), .B (temp_setpoint[2]), .Y (n_0));
endmodule

module visitor_counter(clk, rst_n, entry_sensor, exit_sensor, count);
  input clk, rst_n, entry_sensor, exit_sensor;
  output [7:0] count;
  wire clk, rst_n, entry_sensor, exit_sensor;
  wire [7:0] count;
  wire UNCONNECTED, entry_prev, exit_prev, n_0, n_1, n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50;
  DFFRHQX1 \count_reg[2] (.RN (rst_n), .CK (clk), .D (n_46), .Q
       (count[2]));
  DFFRHQX1 \count_reg[4] (.RN (rst_n), .CK (clk), .D (n_50), .Q
       (count[4]));
  INVXL g813(.A (n_48), .Y (n_50));
  INVXL g814(.A (n_47), .Y (n_49));
  AOI222XL g815(.A0 (n_14), .A1 (n_30), .B0 (n_13), .B1 (n_22), .C0
       (n_36), .C1 (count[4]), .Y (n_48));
  AOI222XL g816(.A0 (n_19), .A1 (n_30), .B0 (n_17), .B1 (n_22), .C0
       (n_37), .C1 (count[6]), .Y (n_47));
  DFFRHQX1 \count_reg[7] (.RN (rst_n), .CK (clk), .D (n_42), .Q
       (count[7]));
  INVXL g818(.A (n_45), .Y (n_46));
  AOI222XL g819(.A0 (n_10), .A1 (n_30), .B0 (n_8), .B1 (n_22), .C0
       (n_38), .C1 (count[2]), .Y (n_45));
  OAI2BB1XL g820(.A0N (count[5]), .A1N (n_39), .B0 (n_33), .Y (n_44));
  OAI2BB1XL g821(.A0N (count[3]), .A1N (n_41), .B0 (n_32), .Y (n_43));
  DFFRHQX1 \count_reg[1] (.RN (rst_n), .CK (clk), .D (n_35), .Q
       (count[1]));
  OAI2BB1XL g823(.A0N (n_20), .A1N (n_22), .B0 (n_40), .Y (n_42));
  OAI221X1 g824(.A0 (n_10), .A1 (n_29), .B0 (n_0), .B1 (n_21), .C0
       (n_27), .Y (n_41));
  OAI21X1 g825(.A0 (n_22), .A1 (n_31), .B0 (count[7]), .Y (n_40));
  OAI221X1 g826(.A0 (n_14), .A1 (n_29), .B0 (n_1), .B1 (n_21), .C0
       (n_27), .Y (n_39));
  SDFFRHQX1 \count_reg[0] (.RN (rst_n), .CK (clk), .D (n_27), .SI
       (n_26), .SE (count[0]), .Q (count[0]));
  OAI211X1 g828(.A0 (n_7), .A1 (n_29), .B0 (n_25), .C0 (n_27), .Y
       (n_38));
  OAI211X1 g829(.A0 (n_15), .A1 (n_29), .B0 (n_24), .C0 (n_27), .Y
       (n_37));
  OAI211X1 g830(.A0 (n_12), .A1 (n_29), .B0 (n_28), .C0 (n_27), .Y
       (n_36));
  OAI21X1 g831(.A0 (n_9), .A1 (n_21), .B0 (n_34), .Y (n_35));
  AOI22X1 g832(.A0 (n_9), .A1 (n_30), .B0 (count[1]), .B1 (n_26), .Y
       (n_34));
  AOI32X1 g833(.A0 (n_4), .A1 (n_1), .A2 (n_22), .B0 (n_15), .B1
       (n_30), .Y (n_33));
  AOI32X1 g834(.A0 (n_3), .A1 (n_0), .A2 (n_22), .B0 (n_12), .B1
       (n_30), .Y (n_32));
  NAND2XL g835(.A (n_19), .B (n_27), .Y (n_31));
  CLKINVX1 g836(.A (n_30), .Y (n_29));
  NAND2XL g837(.A (n_11), .B (n_22), .Y (n_28));
  NOR2XL g838(.A (n_22), .B (n_23), .Y (n_30));
  INVX1 g839(.A (n_27), .Y (n_26));
  NAND2XL g840(.A (n_6), .B (n_22), .Y (n_25));
  NAND2XL g841(.A (n_16), .B (n_22), .Y (n_24));
  NAND2XL g842(.A (n_21), .B (n_23), .Y (n_27));
  OAI211X1 g843(.A0 (count[7]), .A1 (n_18), .B0 (exit_sensor), .C0
       (exit_prev), .Y (n_23));
  CLKINVX1 g844(.A (n_22), .Y (n_21));
  AOI211X1 g845(.A0 (count[7]), .A1 (n_20), .B0 (entry_prev), .C0
       (n_5), .Y (n_22));
  NOR2XL g846(.A (n_2), .B (n_16), .Y (n_20));
  CLKINVX1 g847(.A (n_18), .Y (n_19));
  NOR2XL g848(.A (count[6]), .B (n_16), .Y (n_17));
  NAND2XL g849(.A (n_2), .B (n_15), .Y (n_18));
  NAND2XL g850(.A (count[5]), .B (n_1), .Y (n_16));
  AND2X1 g851(.A (n_4), .B (n_14), .Y (n_15));
  NOR2BX1 g852(.AN (n_12), .B (count[4]), .Y (n_14));
  NOR2XL g853(.A (count[4]), .B (n_11), .Y (n_13));
  AND2X1 g855(.A (n_3), .B (n_10), .Y (n_12));
  NAND2XL g856(.A (count[3]), .B (n_0), .Y (n_11));
  NOR2BX1 g858(.AN (n_7), .B (count[2]), .Y (n_10));
  NOR2XL g859(.A (count[2]), .B (n_6), .Y (n_8));
  NAND2BX1 g860(.AN (n_7), .B (n_6), .Y (n_9));
  DFFRXL exit_prev_reg(.RN (rst_n), .CK (clk), .D (exit_sensor), .Q
       (UNCONNECTED), .QN (exit_prev));
  DFFRHQX1 entry_prev_reg(.RN (rst_n), .CK (clk), .D (entry_sensor), .Q
       (entry_prev));
  NOR2XL g863(.A (count[0]), .B (count[1]), .Y (n_7));
  NAND2XL g864(.A (count[0]), .B (count[1]), .Y (n_6));
  INVX1 g879(.A (entry_sensor), .Y (n_5));
  NOR2BX1 g2(.AN (count[4]), .B (n_11), .Y (n_1));
  NOR2BX1 g882(.AN (count[2]), .B (n_6), .Y (n_0));
  DFFRX1 \count_reg[6] (.RN (rst_n), .CK (clk), .D (n_49), .Q
       (count[6]), .QN (n_2));
  DFFRX1 \count_reg[5] (.RN (rst_n), .CK (clk), .D (n_44), .Q
       (count[5]), .QN (n_4));
  DFFRX1 \count_reg[3] (.RN (rst_n), .CK (clk), .D (n_43), .Q
       (count[3]), .QN (n_3));
endmodule

module water_level_controller(clk, rst_n, water_level, pump_on,
     valve_close);
  input clk, rst_n;
  input [3:0] water_level;
  output pump_on, valve_close;
  wire clk, rst_n;
  wire [3:0] water_level;
  wire pump_on, valve_close;
  wire n_0, n_1, n_11;
  DFFRHQX1 valve_close_reg(.RN (rst_n), .CK (clk), .D (n_0), .Q
       (valve_close));
  AOI211X1 g81(.A0 (water_level[1]), .A1 (water_level[0]), .B0
       (water_level[2]), .C0 (water_level[3]), .Y (n_1));
  NOR2BXL g2(.AN (n_11), .B (n_1), .Y (n_0));
  SDFFRHQX1 pump_on_reg(.RN (rst_n), .CK (clk), .D (pump_on), .SI
       (n_1), .SE (n_11), .Q (pump_on));
  AO21X1 g82(.A0 (water_level[2]), .A1 (water_level[3]), .B0 (n_1), .Y
       (n_11));
endmodule

module window_treatment(clk, rst_n, auto_mode, light_level,
     manual_open, manual_close, window_state);
  input clk, rst_n, auto_mode, manual_open, manual_close;
  input [7:0] light_level;
  output [1:0] window_state;
  wire clk, rst_n, auto_mode, manual_open, manual_close;
  wire [7:0] light_level;
  wire [1:0] window_state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11;
  SDFFRHQX1 \window_state_reg[0] (.RN (rst_n), .CK (clk), .D (n_2), .SI
       (n_11), .SE (auto_mode), .Q (window_state[0]));
  DFFRHQX1 \window_state_reg[1] (.RN (rst_n), .CK (clk), .D (n_10), .Q
       (window_state[1]));
  MXI2XL g375(.A (n_7), .B (n_8), .S0 (light_level[6]), .Y (n_11));
  OAI22X1 g376(.A0 (light_level[6]), .A1 (n_9), .B0 (auto_mode), .B1
       (n_3), .Y (n_10));
  NAND2XL g377(.A (auto_mode), .B (n_7), .Y (n_9));
  NOR2BXL g378(.AN (light_level[7]), .B (n_6), .Y (n_8));
  AOI31X1 g379(.A0 (light_level[4]), .A1 (light_level[5]), .A2 (n_4),
       .B0 (light_level[7]), .Y (n_7));
  AOI211X1 g380(.A0 (light_level[3]), .A1 (n_5), .B0 (light_level[4]),
       .C0 (light_level[5]), .Y (n_6));
  NAND2BX1 g381(.AN (light_level[0]), .B (n_1), .Y (n_5));
  NAND2BX1 g382(.AN (light_level[3]), .B (n_1), .Y (n_4));
  AOI21X1 g383(.A0 (n_0), .A1 (window_state[1]), .B0 (manual_open), .Y
       (n_3));
  NOR3BX1 g384(.AN (window_state[0]), .B (manual_close), .C
       (manual_open), .Y (n_2));
  NOR2XL g385(.A (light_level[2]), .B (light_level[1]), .Y (n_1));
  INVXL g386(.A (manual_close), .Y (n_0));
endmodule

module HA(clk, rst_n, temp_sensor, temp_setpoint, water_level,
     light_sensor, motion_sensor, door_sensor, window_sensor,
     alarm_arm, entry_sensor, exit_sensor, window_auto_mode,
     window_manual_open, window_manual_close, tv_on_cmd, music_on_cmd,
     volume_cmd, ac_cmd, fan_cmd, light_cmd, door_lock_cmd,
     door_unlock_cmd, pin_input, humidity_sensor, heater_on, cooler_on,
     water_pump_on, water_valve_close, led_brightness,
     burglar_alarm_out, visitor_count, window_state, tv_on, music_on,
     volume_level, ac_on, fan_on, lights_on, door_locked, lock_status,
     humidifier_on, dehumidifier_on, system_status);
  input clk, rst_n, motion_sensor, door_sensor, window_sensor,
       alarm_arm, entry_sensor, exit_sensor, window_auto_mode,
       window_manual_open, window_manual_close, tv_on_cmd,
       music_on_cmd, ac_cmd, fan_cmd, light_cmd, door_lock_cmd,
       door_unlock_cmd;
  input [7:0] temp_sensor, temp_setpoint, light_sensor, humidity_sensor;
  input [3:0] water_level, volume_cmd, pin_input;
  output heater_on, cooler_on, water_pump_on, water_valve_close,
       burglar_alarm_out, tv_on, music_on, ac_on, fan_on, lights_on,
       door_locked, humidifier_on, dehumidifier_on;
  output [7:0] led_brightness, visitor_count, system_status;
  output [1:0] window_state, lock_status;
  output [3:0] volume_level;
  wire clk, rst_n, motion_sensor, door_sensor, window_sensor,
       alarm_arm, entry_sensor, exit_sensor, window_auto_mode,
       window_manual_open, window_manual_close, tv_on_cmd,
       music_on_cmd, ac_cmd, fan_cmd, light_cmd, door_lock_cmd,
       door_unlock_cmd;
  wire [7:0] temp_sensor, temp_setpoint, light_sensor, humidity_sensor;
  wire [3:0] water_level, volume_cmd, pin_input;
  wire heater_on, cooler_on, water_pump_on, water_valve_close,
       burglar_alarm_out, tv_on, music_on, ac_on, fan_on, lights_on,
       door_locked, humidifier_on, dehumidifier_on;
  wire [7:0] led_brightness, visitor_count, system_status;
  wire [1:0] window_state, lock_status;
  wire [3:0] volume_level;
  wire [3:0] pin_input_r;
  wire [1:0] lock_status_int;
  wire [3:0] volume_cmd_r;
  wire [3:0] volume_level_int;
  wire [7:0] humidity_sensor_r;
  wire [7:0] light_sensor_r;
  wire [7:0] led_brightness_int;
  wire [7:0] temp_sensor_r;
  wire [7:0] temp_setpoint_r;
  wire [7:0] visitor_count_int;
  wire [3:0] water_level_r;
  wire [1:0] window_state_int;
  wire ac_cmd_r, ac_on_int, alarm_arm_r, burglar_alarm_out_int,
       cooler_on_int, dehumidifier_on_int, door_lock_cmd_r,
       door_locked_int;
  wire door_sensor_r, door_unlock_cmd_r, entry_sensor_r, exit_sensor_r,
       fan_cmd_r, fan_on_int, heater_on_int, humidifier_on_int;
  wire light_cmd_r, lights_on_int, motion_sensor_r, music_on_cmd_r,
       music_on_int, tv_on_cmd_r, tv_on_int, water_pump_on_int;
  wire water_valve_close_int, window_auto_mode_r,
       window_manual_close_r, window_manual_open_r, window_sensor_r;
  assign system_status[0] = cooler_on;
  assign system_status[1] = heater_on;
  assign system_status[2] = lights_on;
  assign system_status[3] = fan_on;
  assign system_status[4] = ac_on;
  assign system_status[5] = door_locked;
  assign system_status[6] = water_pump_on;
  assign system_status[7] = burglar_alarm_out;
  appliances_controller u_appliances(.clk (clk), .rst_n (rst_n),
       .ac_cmd (ac_cmd_r), .fan_cmd (fan_cmd_r), .light_cmd
       (light_cmd_r), .ac_on (ac_on_int), .fan_on (fan_on_int),
       .lights_on (lights_on_int));
  burglar_alarm u_burglar(.clk (clk), .rst_n (rst_n), .motion_sensor
       (motion_sensor_r), .door_sensor (door_sensor_r), .window_sensor
       (window_sensor_r), .alarm_arm (alarm_arm_r), .alarm_out
       (burglar_alarm_out_int));
  door_lock_controller u_door_lock(.clk (clk), .rst_n (rst_n),
       .lock_cmd (door_lock_cmd_r), .unlock_cmd (door_unlock_cmd_r),
       .pin_input (pin_input_r), .door_locked (door_locked_int),
       .lock_status (lock_status_int));
  entertainment_system u_entertainment(.clk (clk), .rst_n (rst_n),
       .tv_on_cmd (tv_on_cmd_r), .music_on_cmd (music_on_cmd_r),
       .volume_cmd (volume_cmd_r), .tv_on (tv_on_int), .music_on
       (music_on_int), .volume_level (volume_level_int));
  humidity_controller u_humidity(.clk (clk), .rst_n (rst_n),
       .humidity_sensor (humidity_sensor_r), .humidifier_on
       (humidifier_on_int), .dehumidifier_on (dehumidifier_on_int));
  luminosity_controller u_lum_ctrl(.clk (clk), .rst_n (rst_n),
       .light_sensor (light_sensor_r), .led_brightness
       (led_brightness_int));
  temperature_controller u_temp_ctrl(.clk (clk), .rst_n (rst_n),
       .temp_sensor (temp_sensor_r), .temp_setpoint (temp_setpoint_r),
       .heater_on (heater_on_int), .cooler_on (cooler_on_int));
  visitor_counter u_visitor(.clk (clk), .rst_n (rst_n), .entry_sensor
       (entry_sensor_r), .exit_sensor (exit_sensor_r), .count
       (visitor_count_int));
  water_level_controller u_water_ctrl(.clk (clk), .rst_n (rst_n),
       .water_level (water_level_r), .pump_on (water_pump_on_int),
       .valve_close (water_valve_close_int));
  window_treatment u_window(.clk (clk), .rst_n (rst_n), .auto_mode
       (window_auto_mode_r), .light_level (light_sensor_r),
       .manual_open (window_manual_open_r), .manual_close
       (window_manual_close_r), .window_state (window_state_int));
  DFFRHQX1 water_valve_close_r_reg(.RN (rst_n), .CK (clk), .D
       (water_valve_close_int), .Q (water_valve_close));
  DFFRHQX1 tv_on_r_reg(.RN (rst_n), .CK (clk), .D (tv_on_int), .Q
       (tv_on));
  DFFRHQX1 music_on_r_reg(.RN (rst_n), .CK (clk), .D (music_on_int), .Q
       (music_on));
  DFFRHQX1 \led_brightness_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[2]), .Q (led_brightness[2]));
  DFFRHQX1 \led_brightness_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[7]), .Q (led_brightness[7]));
  DFFRHQX1 \lock_status_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (lock_status_int[1]), .Q (lock_status[1]));
  DFFRHQX1 \lock_status_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (lock_status_int[0]), .Q (lock_status[0]));
  DFFRHQX1 humidifier_on_r_reg(.RN (rst_n), .CK (clk), .D
       (humidifier_on_int), .Q (humidifier_on));
  DFFRHQX1 dehumidifier_on_r_reg(.RN (rst_n), .CK (clk), .D
       (dehumidifier_on_int), .Q (dehumidifier_on));
  DFFRHQX1 \led_brightness_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[4]), .Q (led_brightness[4]));
  DFFRHQX1 \led_brightness_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[3]), .Q (led_brightness[3]));
  DFFRHQX1 \led_brightness_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[6]), .Q (led_brightness[6]));
  DFFRHQX1 \led_brightness_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[0]), .Q (led_brightness[0]));
  DFFRHQX1 \led_brightness_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[1]), .Q (led_brightness[1]));
  DFFRHQX1 \led_brightness_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (led_brightness_int[5]), .Q (led_brightness[5]));
  DFFRHQX1 lights_on_r_reg(.RN (rst_n), .CK (clk), .D (lights_on_int),
       .Q (lights_on));
  DFFRHQX1 door_locked_r_reg(.RN (rst_n), .CK (clk), .D
       (door_locked_int), .Q (door_locked));
  DFFRHQX1 ac_on_r_reg(.RN (rst_n), .CK (clk), .D (ac_on_int), .Q
       (ac_on));
  DFFRHQX1 fan_on_r_reg(.RN (rst_n), .CK (clk), .D (fan_on_int), .Q
       (fan_on));
  DFFRHQX1 \volume_level_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (volume_level_int[3]), .Q (volume_level[3]));
  DFFRHQX1 \volume_level_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (volume_level_int[1]), .Q (volume_level[1]));
  DFFRHQX1 \volume_level_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (volume_level_int[0]), .Q (volume_level[0]));
  DFFRHQX1 \volume_level_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (volume_level_int[2]), .Q (volume_level[2]));
  DFFRHQX1 water_pump_on_r_reg(.RN (rst_n), .CK (clk), .D
       (water_pump_on_int), .Q (water_pump_on));
  DFFRHQX1 \humidity_sensor_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[7]), .Q (humidity_sensor_r[7]));
  DFFRHQX1 alarm_arm_r_reg(.RN (rst_n), .CK (clk), .D (alarm_arm), .Q
       (alarm_arm_r));
  DFFRHQX1 door_unlock_cmd_r_reg(.RN (rst_n), .CK (clk), .D
       (door_unlock_cmd), .Q (door_unlock_cmd_r));
  DFFRHQX1 \volume_cmd_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (volume_cmd[0]), .Q (volume_cmd_r[0]));
  DFFRHQX1 motion_sensor_r_reg(.RN (rst_n), .CK (clk), .D
       (motion_sensor), .Q (motion_sensor_r));
  DFFRHQX1 fan_cmd_r_reg(.RN (rst_n), .CK (clk), .D (fan_cmd), .Q
       (fan_cmd_r));
  DFFRHQX1 \pin_input_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (pin_input[1]), .Q (pin_input_r[1]));
  DFFRHQX1 \visitor_count_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[1]), .Q (visitor_count[1]));
  DFFRHQX1 window_auto_mode_r_reg(.RN (rst_n), .CK (clk), .D
       (window_auto_mode), .Q (window_auto_mode_r));
  DFFRHQX1 \visitor_count_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[5]), .Q (visitor_count[5]));
  DFFRHQX1 \visitor_count_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[4]), .Q (visitor_count[4]));
  DFFRHQX1 \visitor_count_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[2]), .Q (visitor_count[2]));
  DFFRHQX1 \visitor_count_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[3]), .Q (visitor_count[3]));
  DFFRHQX1 \temp_sensor_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[1]), .Q (temp_sensor_r[1]));
  DFFRHQX1 \visitor_count_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[0]), .Q (visitor_count[0]));
  DFFRHQX1 \window_state_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (window_state_int[1]), .Q (window_state[1]));
  DFFRHQX1 \window_state_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (window_state_int[0]), .Q (window_state[0]));
  DFFRHQX1 \temp_sensor_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[0]), .Q (temp_sensor_r[0]));
  DFFRHQX1 \temp_sensor_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[2]), .Q (temp_sensor_r[2]));
  DFFRHQX1 \visitor_count_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[7]), .Q (visitor_count[7]));
  DFFRHQX1 \visitor_count_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (visitor_count_int[6]), .Q (visitor_count[6]));
  DFFRHQX1 \temp_sensor_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[7]), .Q (temp_sensor_r[7]));
  DFFRHQX1 window_manual_close_r_reg(.RN (rst_n), .CK (clk), .D
       (window_manual_close), .Q (window_manual_close_r));
  DFFRHQX1 light_cmd_r_reg(.RN (rst_n), .CK (clk), .D (light_cmd), .Q
       (light_cmd_r));
  DFFRHQX1 ac_cmd_r_reg(.RN (rst_n), .CK (clk), .D (ac_cmd), .Q
       (ac_cmd_r));
  DFFRHQX1 window_manual_open_r_reg(.RN (rst_n), .CK (clk), .D
       (window_manual_open), .Q (window_manual_open_r));
  DFFRHQX1 \temp_setpoint_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[7]), .Q (temp_setpoint_r[7]));
  DFFRHQX1 window_sensor_r_reg(.RN (rst_n), .CK (clk), .D
       (window_sensor), .Q (window_sensor_r));
  DFFRHQX1 \temp_setpoint_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[6]), .Q (temp_setpoint_r[6]));
  DFFRHQX1 \temp_setpoint_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[5]), .Q (temp_setpoint_r[5]));
  DFFRHQX1 \temp_setpoint_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[4]), .Q (temp_setpoint_r[4]));
  DFFRHQX1 \temp_setpoint_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[3]), .Q (temp_setpoint_r[3]));
  DFFRHQX1 cooler_on_r_reg(.RN (rst_n), .CK (clk), .D (cooler_on_int),
       .Q (cooler_on));
  DFFRHQX1 \light_sensor_r_reg[7] (.RN (rst_n), .CK (clk), .D
       (light_sensor[7]), .Q (light_sensor_r[7]));
  DFFRHQX1 burglar_alarm_out_r_reg(.RN (rst_n), .CK (clk), .D
       (burglar_alarm_out_int), .Q (burglar_alarm_out));
  DFFRHQX1 heater_on_r_reg(.RN (rst_n), .CK (clk), .D (heater_on_int),
       .Q (heater_on));
  DFFRHQX1 \water_level_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (water_level[2]), .Q (water_level_r[2]));
  DFFRHQX1 \temp_sensor_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[4]), .Q (temp_sensor_r[4]));
  DFFRHQX1 \temp_sensor_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[5]), .Q (temp_sensor_r[5]));
  DFFRHQX1 \temp_setpoint_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[0]), .Q (temp_setpoint_r[0]));
  DFFRHQX1 \temp_setpoint_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[1]), .Q (temp_setpoint_r[1]));
  DFFRHQX1 \temp_setpoint_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (temp_setpoint[2]), .Q (temp_setpoint_r[2]));
  DFFRHQX1 \temp_sensor_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[3]), .Q (temp_sensor_r[3]));
  DFFRHQX1 \temp_sensor_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (temp_sensor[6]), .Q (temp_sensor_r[6]));
  DFFRHQX1 \water_level_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (water_level[1]), .Q (water_level_r[1]));
  DFFRHQX1 \water_level_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (water_level[3]), .Q (water_level_r[3]));
  DFFRHQX1 \water_level_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (water_level[0]), .Q (water_level_r[0]));
  DFFRHQX1 door_lock_cmd_r_reg(.RN (rst_n), .CK (clk), .D
       (door_lock_cmd), .Q (door_lock_cmd_r));
  DFFRHQX1 \volume_cmd_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (volume_cmd[2]), .Q (volume_cmd_r[2]));
  DFFRHQX1 door_sensor_r_reg(.RN (rst_n), .CK (clk), .D (door_sensor),
       .Q (door_sensor_r));
  DFFRHQX1 entry_sensor_r_reg(.RN (rst_n), .CK (clk), .D
       (entry_sensor), .Q (entry_sensor_r));
  DFFRHQX1 exit_sensor_r_reg(.RN (rst_n), .CK (clk), .D (exit_sensor),
       .Q (exit_sensor_r));
  DFFRHQX1 \humidity_sensor_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[0]), .Q (humidity_sensor_r[0]));
  DFFRHQX1 \humidity_sensor_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[1]), .Q (humidity_sensor_r[1]));
  DFFRHQX1 \humidity_sensor_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[2]), .Q (humidity_sensor_r[2]));
  DFFRHQX1 \humidity_sensor_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[3]), .Q (humidity_sensor_r[3]));
  DFFRHQX1 \humidity_sensor_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[4]), .Q (humidity_sensor_r[4]));
  DFFRHQX1 \humidity_sensor_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[5]), .Q (humidity_sensor_r[5]));
  DFFRHQX1 \humidity_sensor_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (humidity_sensor[6]), .Q (humidity_sensor_r[6]));
  DFFRHQX1 \volume_cmd_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (volume_cmd[3]), .Q (volume_cmd_r[3]));
  DFFRHQX1 music_on_cmd_r_reg(.RN (rst_n), .CK (clk), .D
       (music_on_cmd), .Q (music_on_cmd_r));
  DFFRHQX1 \pin_input_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (pin_input[0]), .Q (pin_input_r[0]));
  DFFRHQX1 \pin_input_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (pin_input[2]), .Q (pin_input_r[2]));
  DFFRHQX1 \pin_input_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (pin_input[3]), .Q (pin_input_r[3]));
  DFFRHQX1 tv_on_cmd_r_reg(.RN (rst_n), .CK (clk), .D (tv_on_cmd), .Q
       (tv_on_cmd_r));
  DFFRHQX1 \volume_cmd_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (volume_cmd[1]), .Q (volume_cmd_r[1]));
  DFFRHQX1 \light_sensor_r_reg[3] (.RN (rst_n), .CK (clk), .D
       (light_sensor[3]), .Q (light_sensor_r[3]));
  DFFRHQX1 \light_sensor_r_reg[1] (.RN (rst_n), .CK (clk), .D
       (light_sensor[1]), .Q (light_sensor_r[1]));
  DFFRHQX1 \light_sensor_r_reg[2] (.RN (rst_n), .CK (clk), .D
       (light_sensor[2]), .Q (light_sensor_r[2]));
  DFFRHQX1 \light_sensor_r_reg[4] (.RN (rst_n), .CK (clk), .D
       (light_sensor[4]), .Q (light_sensor_r[4]));
  DFFRHQX1 \light_sensor_r_reg[5] (.RN (rst_n), .CK (clk), .D
       (light_sensor[5]), .Q (light_sensor_r[5]));
  DFFRHQX1 \light_sensor_r_reg[6] (.RN (rst_n), .CK (clk), .D
       (light_sensor[6]), .Q (light_sensor_r[6]));
  DFFRHQX1 \light_sensor_r_reg[0] (.RN (rst_n), .CK (clk), .D
       (light_sensor[0]), .Q (light_sensor_r[0]));
endmodule

